### ISSUE TITLE
Can I use graphql in browser

### ISSUE THREAD

**Issue by cesarve77** [19majkel94/type-graphql#100]
I'm looking the way to share my schema between server and client

Something like: https://github.com/typeorm/typeorm/issues/1602

Thanks

**Comment by 19majkel94** [comment]
GraphQL schema by itself is shared by server and client. What code do you need to share?

**Comment by cesarve77** [comment]
Thanks for a quick answer, and sorry for my english
I get this error from webpack

```
ERROR in ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/cesarramos/Documents/projects/futbol/node_modules/fs.realpath'
 @ ./node_modules/fs.realpath/index.js 8:9-22
 @ ./node_modules/glob/glob.js
 @ ./node_modules/type-graphql/helpers/loadResolversFromGlob.js
 @ ./node_modules/type-graphql/utils/buildSchema.js
 @ ./node_modules/type-graphql/index.js
 @ ./src/lib/entities/Video.js
 @ ./src/client/index.js
 @ multi babel-polyfill ./src/client/index.js
```

and this is the code Im trying to share:
```

import {Column, Entity, PrimaryGeneratedColumn} from "typeorm"
import {Field, ID, InputType, ObjectType} from "type-graphql";
import {Length} from "class-validator";

@InputType("videoInput")
@ObjectType()
@Entity()
export class Video {

    @Field(type => ID, {nullable: true})
    @PrimaryGeneratedColumn()
    id: number;

    @Field()
    @Column()
    url: string;

    @Field({nullable: true})
    urlLocal: string;

    @Field()
    @Column()
    @Length(0, 1000)
    description: string

    constructor(init?: Partial<Video>) {
        Object.assign(this, init)
    }
}



```

**Comment by 19majkel94** [comment]
Why you are trying to build the schema on client side? Your webpack entry point is incorrect in that case.

**Comment by cesarve77** [comment]
I really don't need the schema I need the class and the validation to be
used in https://github.com/vazco/uniforms.


Thanks again.

2018-06-17 3:11 GMT+10:00 Michał Lytek <notifications@github.com>:

**Comment by 19majkel94** [comment]
@cesarve77 Have you tried fixing the error by adding this to your webpack config?
```
node: {
   fs: "empty"
}
```

I haven't thought about actually using the decorated classes as JS objects on client side. I think it's a bad idea as GraphQL doesn't work on classes, just plain objects, the schema is strongly typed so you can generate data interfaces for every query you make.

If you have your business logic inside the type classes - don't do it, don't break the single responsibility principle, don't mix domain model with infrastructure code.

I will have to write a guide how to use GraphQL on frontend when you have TypeGraphQL on backend. For now all I can do is to provide a shim for browser to remove the webpack error and making the bundle bigger, [just like TypeORM does](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js).

**Comment by 19majkel94** [comment]
Closing via 2bb93b1 🎉 

@cesarve77 Please check out this docs and tell me if it works for you 😉 
https://19majkel94.github.io/type-graphql/docs/browser-usage.html#using-classes-in-client-app

**Comment by cesarve77** [comment]
Ohh thanks, that's works!!

**Comment by arifdigibaad** [comment]
```
bundle.js:150071 Uncaught TypeError: decorator is not a function
    at bundle.js:150071
    at __decorate (bundle.js:150064)
    at Object.defineProperty.value (bundle.js:150114)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:145745)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:145598)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:92320)
    at __webpack_require__ (bundle.js:20)

```

**Comment by 19majkel94** [comment]
@arifdigibaad Do you use babel instead of `ts-loader`?

**Comment by arifdigibaad** [comment]
Hi thanks for responding... 
No I don't use babel.

**Comment by arifdigibaad** [comment]
### Input
``` typescript
import {Field, ObjectType, Float, InputType} from "type-graphql";
import {ObjectScalarType} from "./AnyType"


@InputType()
export class UserInput {

    @Field()
    firebaseAuthID: string;

    @Field()
    firstName: string;

    @Field()
    lastName: string;

    @Field()
    userName: string;

    @Field()
    password: string;

    @Field()
    emailAddress: string;

}

```


### Output
``` javascript
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
const type_graphql_1 = require("type-graphql");
let UserInput = class UserInput {
};
__decorate([
    type_graphql_1.Field(),
    __metadata("design:type", String)
], UserInput.prototype, "firebaseAuthID", void 0);
__decorate([
    type_graphql_1.Field(),
    __metadata("design:type", String)
], UserInput.prototype, "firstName", void 0);
__decorate([
    type_graphql_1.Field(),
    __metadata("design:type", String)
], UserInput.prototype, "lastName", void 0);
__decorate([
    type_graphql_1.Field(),
    __metadata("design:type", String)
], UserInput.prototype, "userName", void 0);
__decorate([
    type_graphql_1.Field(),
    __metadata("design:type", String)
], UserInput.prototype, "password", void 0);
__decorate([
    type_graphql_1.Field(),
    __metadata("design:type", String)
], UserInput.prototype, "emailAddress", void 0);
UserInput = __decorate([
    type_graphql_1.InputType()
], UserInput);
exports.UserInput = UserInput;

```

**Comment by 19majkel94** [comment]
So you are trying to bundle whole TypeGraphQL into your browser app? It makes no sense, browser-shim is to slim down the bundle using dummy decorators.

And I don't see any `decorator` call in your transpiled file. Please create a repository w reproducible code example, it's hard to guess what's wrong with your config.

**Comment by DerekHill** [comment]
Just a note that the docs mentioned by MichalLytek are now at https://typegraphql.ml/docs/browser-usage.html

**Comment by MentalGear** [comment]
> will have to write a guide how to use GraphQL on frontend when you have TypeGraphQL on backend. For now all I can do is to provide a shim for browser to remove the webpack error and making the bundle bigger, [just like TypeORM does](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js).

Did you ever get around to write a short post on using 'GraphQL on frontend when you have TypeGraphQL on backend' ? It would be mighty helpful to have a practical starting point/example how type-graphql classes could be used to do front-end validation. @MichalLytek

**Comment by MichalLytek** [comment]
@MentalGear https://github.com/MichalLytek/type-graphql/tree/master/examples/apollo-client
