### ISSUE TITLE
External PubSub?

### ISSUE THREAD

**Issue by stevefan1999** [19majkel94/type-graphql#104]
Is it possible to inject PubSubEngine externally?

It's currently incompatible with TypeORM, I tried to combine resolvers with `EntitySubscriberInterface<T>` but the injected PubSub argument in `EventSubscriber` derived methods like `afterInsert` or `afterUpdate` stays undefined.

I know I could have redirected it to Redis, but doing it internally in Node makes me feel that there were lesser overheads.

**Comment by 19majkel94** [comment]
You can create own pub sub, use it externally in TypeORM or sth and then register in TypeGraphQL using pubSub option of buildSchema.

**Comment by stevefan1999** [comment]
@19majkel94 I figured out the solution using your advice ;)

So basically, we had to use TypeDI anyway, we could just dump the PubSub on the service resolver. (Heck, even a global object is okay I think?)

However, PubSubEngine is an interface (!!) so it is not a valid prototype construct. Therefore the usual `Container.set(T)` wouldn't work, to workaround that we trivially set it as a named resolve instead, you could either call it 'pubsub' or 'PubSubEngine', here I call it 'pubsub' for demonstration reference.
```js
...
import { PubSub, PubSubEngine } from 'graphql-subscriptions'
import * as TypeGraphQL from 'type-graphql'
import { Container } from 'typedi'
import * as TypeORM from 'typeorm'
...
TypeORM.useContainer(Container)
TypeGraphQL.useContainer(Container)
...
async function main () {
   Container.set('pubsub', new PubSub() as PubSubEngine)
   ...
   const schema = await TypeGraphQL.buildSchema({
   ...
     pubSub: Container.get<PubSubEngine>('pubsub'),
...
```

Then hook up `AfterInsert`/`AfterUpdate`:
```js
...
import { PubSubEngine, Resolver, Root, Subscription } from 'type-graphql'
import { Container } from 'typedi'
import { AfterInsert } from 'typeorm'
...

@Entity()
@ObjectType()
export class Foo {
  ...
  @AfterInsert()
  async afterInsert () {
    return Container.get<PubSubEngine>('pubsub').publish(Foo.name, {
      event: 'INSERT',
      sender: this
    })
  }
  ...
```

Finally the resolvers:
```js
...
@Resolver(() => Foo)
export class FooResolver {
  ...
  @Subscription(() => Foo, {
    topics: Foo.name,
    filter: ({ payload: { event } }) => event === 'INSERT'
  })
  async listenForInsert (
    @Root() event
  ): Promise<Foo> {
    return event.sender
  }
  ...
```
Voila! You should be able to see the definition of the subscription, try to subscribe it and go create a new entry to see if it streamed.

Drawbacks:
1. There will be no re-entrancy
   - But who uses multiple databases anyway?
2. Double passing
   - Yes, you repeated the same thing twice. This violated DRY principle but we have to cope with the magical AsyncIterator.
   - The sender object might lost its state since it's asynchronous so any you must account for wild reference, especially on concurrency environment it is highly dangerous

Closing as solved. Thanks.

**Comment by 19majkel94** [comment]
> So basically, we had to use TypeDI anyway.

No, you can just `import myPubSub from './myPubSub'` and use it in your app + provide it to `buildSchema`.

> PubSubEngine is an interface

Of course, why should I demand and concrete implementation? I just expect some methods, you can provide the redis-based, event-emitter-based or custom one.

> Yes, you repeated the same thing twice. This violated DRY principle but we have to cope with the magical AsyncIterator.

What do you mean?

Using `Container` inside a entity class is a horrible idea 😵 
Entity listeners are good for things like incrementing edit counter, timestamp or sth simple. For business logic it's better to create a Subscriber class:
https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#what-is-a-subscriber

**Comment by stevefan1999** [comment]
@19majkel94 

> Yes, you repeated the same thing twice. This violated DRY principle but we have to cope with the magical AsyncIterator.

Because TypeORM pumped event to event subscribers or listeners first, then it flows into PubSubEngine and AsyncIterator, so the actual PubSub message loop is delayed for one tick.

> Using Container inside a entity class is a horrible idea 😵
It's okay, fetching container metadata information might take a little bit of time and it is not cached if I do this class-by-class

> Entity listeners are good for things like incrementing edit counter, timestamp or sth simple. For business logic it's better to create a Subscriber class:
Ha. Then I got this global subscriber class:
```ts
export enum EventType {
  Insert,
  Update,
  Remove
}

export enum EventOrder {
  Pre,
  Post
}

@EventSubscriber()
export class GlobalSubscriber implements EntitySubscriberInterface {
  constructor (
    @Inject('pubsub') private readonly pubSub: PubSubEngine
  ) {}

  beforeInsert (event: InsertEvent<any>) {
    this.pubSub.publish(event.entity.constructor.name, {
      event: EventType.Insert,
      order: EventOrder.Pre,
      sender: event.entity
    })
  }

  beforeUpdate (event: UpdateEvent<any>) {
    const { updatedColumns, updatedRelations } = event
    this.pubSub.publish(event.entity.constructor.name, {
      event: EventType.Update,
      order: EventOrder.Pre,
      sender: event.entity,
      args: {
        updatedColumns,
        updatedRelations
      }
    })
  }

  beforeRemove (event: RemoveEvent<any>) {
    this.pubSub.publish(event.entity.constructor.name, {
      event: EventType.Update,
      order: EventOrder.Pre,
      sender: event.entity
    })
  }

  afterInsert (event: InsertEvent<any>) {
    this.pubSub.publish(event.entity.constructor.name, {
      event: EventType.Insert,
      order: EventOrder.Post,
      sender: event.entity
    })
  }

  afterUpdate (event: UpdateEvent<any>) {
    const { updatedColumns, updatedRelations } = event
    this.pubSub.publish(event.entity.constructor.name, {
      event: EventType.Update,
      order: EventOrder.Post,
      sender: event.entity,
      args: {
        updatedColumns,
        updatedRelations
      }
    })
  }

  afterRemove (event: RemoveEvent<any>) {
    this.pubSub.publish(event.entity.constructor.name, {
      event: EventType.Remove,
      order: EventOrder.Post,
      sender: event.entity
    })
  }
}
```
😝. Although the performance is impacted a little, but making subscriber resolvers are no worries now:
```ts
@Subscription(() => Foo, {
    topics: Foo.name,
    filter: ({ payload: { event, order } }) => event === EventType.Insert && order === EventOrder.Post
  })
  async listenForInsert (
    @Root() event
  ): Promise<Foo> {
    return event.sender
  }
```

**Comment by 19majkel94** [comment]
> It's okay, fetching container metadata information might take a little bit of time and it is not cached if I do this class-by-class

It's not ok, service locator is an anti-pattern. Treat TypeORM entities and TypeGraphQL types as DTO objects, no a domain model.

> Because TypeORM pumped event to event subscribers or listeners first, then it flows into PubSubEngine and AsyncIterator, so the actual PubSub message loop is delayed for one tick.

That's really weird, so you receive your first subscribe data after second entity insert?
