### ISSUE TITLE
Question: Serialize schema

### ISSUE THREAD

**Issue by mendrik** [19majkel94/type-graphql#107]
Hi,

I'm new to graphql but I managed to set up a project and it works nicely, so thanks for the great work!
The only thing I'd like to improve is that intellij would suggest types automatically. I have found a graphql plugin which is supposed to help with that, however it requires a local file holding the schema.

So my question is if I have a simple schema like this:
```
 const schema = await TypeGraphQL.buildSchema({
      resolvers: [...]
 })
```
What's the easiest way to serialize this into a local file?

**Comment by 19majkel94** [comment]
The best way is to run your server and generate the `schema.json`:
https://github.com/apollographql/apollo-cli#apollo-schemadownload-output
