### ISSUE TITLE
@types/graphql conflicts

### ISSUE THREAD

**Issue by mikebm** [19majkel94/type-graphql#112]
**Describe the bug**
When using graphql-tools to perform schema stitching with a schema generated from type-graphql and another schema not coming from type-graphql, then you get errors of Invalid Schema Passed.

It appears this is due to the fact that @types/graphql is a dependency and not a dev dependency in both type-graphql and apollo-link projects. Apollo-link is using 0.12.6 where as type-graphql is using 0.13.3.

Is there a reason this is a dependency and not a devDependency?

**To Reproduce**
Create a simple type-graphql schema and run buildSchema on it, then create a standard schema using makeExecutableSchema from graphql-tools. Once done, merge the schemas using mergeSchemas from graphql-tools.

The version in use of graphql-tools is graphql-tools@3.0.5.

**Expected behavior**
type-graphql should be combinable with existing schemas using graphql-tools schema stitching.

**Comment by 19majkel94** [comment]
Do you have an compilation error or runtime error?
`@types/graphql` is a devDep of `graphql-tools` so it's not downloaded by npm at all.

If you have runtime error, try `npm dedupe` and `npm prune` as `graphql-tools` has peerDependency `"graphql": "^0.12.0 || ^0.13.0"` so it should accept `"graphql": "^0.13.2"` that comes with TypeGraphQL and be merged into one package in `node_modules`.

**Comment by mikebm** [comment]
I get a runtime error of "Invalid Schema Passed" because if is trying to check if my schema is typeof GraphQLSchema, which comes from @types/graphql. That type has changed between 0.12 and 0.13.

GraphQLTools has a a peerDependency of "graphql", but I am talking about "@types/graphql". 

It has a dependency of "apollo-link": "1.2.2" 
https://github.com/apollographql/graphql-tools/blob/master/package.json#L51

which has a dependency of:
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link/package.json#L41

See related open bug for apollo-link.
https://github.com/apollographql/apollo-link/issues/601

**Comment by 19majkel94** [comment]
>  get a runtime error (...) which comes from @types/graphql

nope, types are pruned on compilation and have no affect on runtime

> it has a dependency of "apollo-link": "1.2.2"
> which has a dependency of "@types/graphql": "0.12.6",

So there's nothing I can do - I use graphql-js 0.13 with types for 0.13, you need to ignore the types conflict with `skipLibCheck` and ping guys from apollo to update their types :wink:

**Comment by 19majkel94** [comment]
Hi @pablocarreraest!
No it's not possible. Please describe your use case in more details.

**Comment by pablocarreraest** [comment]
Sure, makeExecutableSchema you must know is from Apollo and also do a slightly different things than buildSchema. [I found this stackoverflow](https://stackoverflow.com/questions/47381519/what-is-the-difference-between-buildschema-and-makeexecutableschema)

The main reason I search for this difference is because I have one project using makeExecutableSchema and with that it handles the relationships independently (also using typeorm).
I just give the functions to get all and by id. here's an example:
```typescript
// Repository of User
public findAll$ (): Observable<User[]> {
   return from(this.manager.find(User))
            .pipe(catchError((error) => Observable.throw(error)));
}
// Repository of Photo
public findById$ (id: string): Observable<Photo> {
    return from(this.manager.findOne(Photo, {id}))
            .pipe(catchError((error) => Observable.throw(error)));
}
```
```typescript
// Query Resolvers
users (root, args, ctx): Promise<Movie[]> {
    const repository: MovieRepository = ctx.db.getCustomRepository(MovieRepository);
    return repository.findAll$().toPromise();
},
photo (root, args, ctx): Promise<Photo> {
    const repository: PhotoRepository = ctx.db.getCustomRepository(PhotoRepository);
    return repository.findById$(args.id).toPromise();
},
```
with that when I query they give me the relationships with no problema using makeExecutableSchema (magic 🧚‍♀️).
``` graphql
query {
  users {
    photos {
      id
      format
    }
  }
}
```

now in other project that I was playing with this library (that's amazing 😎).
I define the same way as above but to get the relationships I have to specify in the repository or I will get null.
```typescript
// Repository of User
public findAll$ (): Observable< User[]> {
   return from(this.manager.find(User, {relations: ['photos']))
            .pipe(catchError((error) => Observable.throw(error)));
}
```
And for get more inner relationship inside the `photos.types` in other words you have to put the relationship by hand ✍️. using buildSchema

Tell me what do you thing... about it. ✌️

**Comment by 19majkel94** [comment]
I will blow your mind once more time: TypeGraphQL is not using `buildSchema` from `graphql-js`, only `new GraphQLSchema`:
https://github.com/19majkel94/type-graphql/blob/7cf044c84939fef854437b1c7a62d0bc99ddbf5d/src/schema/schema-generator.ts#L86-L91

And `makeExecutableSchema` is a helper from `apollo` that allows you to decouple types definitions (using SDL) from their implementations (resolvers map).
It doesn't make any magic with automatically resolving TypeORM entities relations. The only framework that do this is [`vesper`](https://github.com/vesper-framework/vesper) 😉 

And why you asked this question here? Please continue the discussion on [gitter](gitter.im/type-graphql/Lobby) or create a separate issue.
