### ISSUE TITLE
Property 'TypeGraphQLMetadataStorage' does not exist on type 'Global'.

### ISSUE THREAD

**Issue by arolson101** [19majkel94/type-graphql#114]
**Describe the bug**
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: » Unable to compile TypeScript:
node_modules/type-graphql/src/metadata/getMetadataStorage.ts(5,12): error TS2339: Property 'TypeGraphQLMetadataStorage' does not exist on type 'Global'.
node_modules/type-graphql/src/metadata/getMetadataStorage.ts(5,50): error TS2339: Property 'TypeGraphQLMetadataStorage' does not exist on type 'Global'.

**To Reproduce**
I'm on typescript@next, so it's probably because of that, but seems like it should be fixed

**Expected behavior**
no error

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node (e.g. 10.5.0)
 - Package version 0.12.2
 - TypeScript version 3.0.0-dev.20180712

**Comment by arolson101** [comment]
note that it's probably related to @types/node overriding the global declaration

**Comment by arolson101** [comment]
using transpile only did solve the problem
perhaps you would have problems in this depot if you installed @types/node?

**Comment by 19majkel94** [comment]
No, I've updated `@types/node` yesterday :wink:
This is issue with ambient module declarations that aren't working in ts-node@7:
https://github.com/TypeStrong/ts-node/issues/615
