### ISSUE TITLE
Adding description to fields

### ISSUE THREAD

**Issue by darkmantle** [19majkel94/type-graphql#115]
Is there a way that we can add descriptions to the objects/fields as in the GQL specification?

```graphql
type Person {
  """name of a person"""
  name: String
}
```

**Comment by 19majkel94** [comment]
Just use `description` decorator option. See examples:
https://github.com/19majkel94/type-graphql/blob/master/examples/simple-usage/recipe-type.ts

**Comment by darkmantle** [comment]
Don't now how I missed that - thanks!

**Comment by zhenwenc** [comment]
The descriptions are rendered as [comments](https://facebook.github.io/graphql/draft/#sec-Comments) instead of [description](https://facebook.github.io/graphql/draft/#sec-Descriptions). Any idea why?

**Comment by 19majkel94** [comment]
It was intended to emit this as comments for a better readability:
https://github.com/19majkel94/type-graphql/blob/48f728a177567d4ba9d2c21010cb1db852857ddb/src/utils/emitSchemaDefinitionFile.ts#L19

If you like the awful descriptions blocks:
```graphql
type User {
  """
  The user's first name.
  """
  name: String!

  """
  The user's surname.
  """
  surname: String!
}
```

You can just pass your options to emitSchemaFile:
```ts
await emitSchemaDefinitionFile("./schema.gql", schema, { commentDescriptions: false });
```

**Comment by zhenwenc** [comment]
@19majkel94 Thanks a lot for the help!
