### ISSUE TITLE
String enum not returning their keys key instead of their internal value

### ISSUE THREAD

**Issue by ericmatte** [19majkel94/type-graphql#116]
**Describe the bug**
According to the docs on https://19majkel94.github.io/type-graphql/docs/enums.html,

> internal value of enums will be taken from enums definition values and the public names from the enum keys

But, whenever I call a simple query that returns a value from `Direction`, I receive the key instead of the internal value.

Example:
Calling `query { getDirectionValue { left } }` returns "Left" instead of "LEFT"

**To Reproduce**
```
export enum Direction {
    Up = "UP",
    Down = "DOWN",
    Left = "LEFT",
    Right = "RIGHT"
}

registerEnumType(Direction, {
    name: "Direction", // this one is mandatory
    description: "The basic directions" // this one is optional
});

@Resolver()
export class SampleResolver {
    @Query(_returns => Direction)
    public getDirectionLeftValue() {
        return Direction.Left; // returns "Left"
    }
}
```

**Expected behavior**
Calling `query { getDirectionLeftValue { left } }` should return "LEFT".

**Enviorment**
 - OS: Windows 10
 - Node 8.11.1
 - Package version 0.12.3
 - TypeScript version 2.9.2

**Comment by 19majkel94** [comment]
> internal value of enums will be taken from enums definition values and the public names from the enum keys

That's right - `Direction.Left` in your resolver returns `"LEFT"` but this is your internal value. It's converted to public value `Left`, the same that you would have to use in your query:
```gql
query {
  move(direction: Left)
}
```

It makes no sense to return internal value by GraphQL - `Left` is a meaningful public value, while `4` or `"DIRECTION_LEFT"` is your internal value.

**Comment by ericmatte** [comment]
Ok, so this was my misunderstanding then. Thank you.
