### ISSUE TITLE
ObjectType field with same type?

### ISSUE THREAD

**Issue by miro4994** [19majkel94/type-graphql#126]
**Describe the bug**
Hey, I don't know if its a bug or not. but i would like to have some child types same as parent, for example: I have a CategoryType, which has childCategories field that returns list of CategoryType but it throws an error ``CategoryType is not defined``

**To Reproduce**
Try to create a type like this which has a field that returns a list of same type.
```
@ObjectType()
export class CategoryType {
  @Field(type => [CategoryType])
  childCategories: CategoryType[];
} 
```
**Expected behavior**
There must be some way how to do this.  Any help or workaround?

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node 8.9.4
 - Package version 0.13.0
 - TypeScript version 2.9.2

**Comment by 19majkel94** [comment]
Sorry, but I'm not able to reproduce it. I have even added a test case for that:
https://github.com/19majkel94/type-graphql/blob/8720670b391516617826acb2a670062a67918672/tests/functional/circular-refs.ts#L72-L104

**Comment by miro4994** [comment]
Thank you for a quick response, at least i know its a problem on my side. I think i have something wrong with my webpack configuration...  May I post the webpack.config.js here to figure out what is causing the problem? If not, you may close the issue.

**Comment by 19majkel94** [comment]
Sure, let's try to figure out what's wrong with webpack. Maybe someone will experience that issue too in the future, so he will have an answer here 😉

**Comment by 19majkel94** [comment]
I bet the problem is with babel - first, you don't need this when you use TypeScript (it's type checker and compiler in one), second, `@babel/plugin-proposal-decorators` is for newer propsal of decorators that's not compatible with current TypeScript one.

**Comment by miro4994** [comment]
Works like a charm! I just removed all babel stuff because i didnt know Typescript is checker and compiler in one ... Now i have simple webpack script with ts-loader included and its working great! For others there is my current simple webpack configuration 
```const path = require("path");
const nodemonPlugin = require("nodemon-webpack-plugin");

module.exports = {
  entry: "./src/index.ts",
  resolve: {
    extensions: [".mjs", ".js", ".ts"]
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js"
  },
  target: "node",
  mode: "development",
  devtool: "source-map",
  plugins: [new nodemonPlugin()],
  module: {
    rules: [{ test: /\.ts?$/, loader: "ts-loader" }]
  },
  node: {
    fs: "empty"
  }
};
```

I'm closing this issue. Thank you for your help.
