### ISSUE TITLE
Example with file upload / download endpoint API

### ISSUE THREAD

**Issue by avkonst** [19majkel94/type-graphql#129]
First of all, I would like to say: nice job done! I have discovered your framework after exploring prisma and postgraphile. Yours is 10 times better!

**Describe the issue**
I have not found in the documentation how to implement client- to-server file upload API and server-to-client download API. I understand GraphQL allows this. How is it possible with TypeGraphQL. Example would be also good.

**Are you able to make a PR that fix this?**
Unlikely.

**Comment by 19majkel94** [comment]
> server-to-client download API. I understand GraphQL allows this. 

No, GraphQL always returns objects (JSONs), so you can stream video file or sth. You need to fallback to good old HTTP and maybe REST API with express.js for things like images or files download (or use base64 😆).

For uploading files, there is an issue for this:
https://github.com/19majkel94/type-graphql/issues/37

**Comment by 19majkel94** [comment]
Closing as the example and docs for apollo-upload will be done along with the integration itself.

**Comment by AlexLeung** [comment]
Here is a definitely terrible idea: you could base64 encode the file, and split it up into chunks, then send the chunks as a GraphQL paginated response.
