### ISSUE TITLE
Objects with FieldResolvers get constructed multiple times.

### ISSUE THREAD

**Issue by j** [19majkel94/type-graphql#131]
```typescript
import {
  Field,
  FieldResolver,
  ObjectType,
  Query,
  Resolver,
  Root
} from 'type-graphql';

@ObjectType()
class Example {
  public static create(field1: string, field2: string) {
    const example = new Example();

    example.field1 = field1;
    example.field2 = field2;

    return example;
  }

  @Field()
  public field1!: string;

  @Field()
  public field2!: string;

  constructor() {
    console.log('Constructor');
  }
}

@Resolver(() => Example)
export class ExampleResolver {
  @Query(() => [Example])
  public async examples(): Promise<Example[]> {
    return [Example.create('a1', 'a2'), Example.create('b1', 'b2')];
  }

  @FieldResolver(() => String)
  public async field3(@Root() example: Example): Promise<string> {
    return `${example.field1} + ${example.field2}`;
  }
}
```

The following logs "Constructor" 4 times when only 2 examples were actually constructed.
```sh
query:
{
  examples {
    field1
    field2
    field3
  }
}

console:
Constructor
Constructor
Constructor
Constructor
```

The following logs "Constructor" twice (removing field3):
```sh
query:
{
  examples {
    field1
    field2
  }
}

console:
Constructor
Constructor
```

The following logs "Constructor" 6 times when only 2 examples were actually constructed.
```sh
query:
{
  examples {
    field1
    field2
    field3Renamed: field3
    field4: field3
  }
}

console:
Constructor
Constructor
Constructor
Constructor
Constructor
Constructor
```

Is this on purpose or should field resolvers root not be reconstructed every time?

**Comment by 19majkel94** [comment]
@j
Do you consider this behavior as a bug that broke your app and has to be fixed? Or you just wanted to clarify some things about how this works and why?

**Comment by 19majkel94** [comment]
Long time ago I had similar OOP feeling that entities and DTO's should be rich model with methods, constructor injection, etc.:
https://github.com/typeorm/typeorm-typedi-extensions/issues/2

But this doesn't solve problems, only introduce more problems. You should just don't use constructors in TypeORM entites and TypeGraphQL types, use the services pattern or separate model classes with adapters to convert from entity/input type to entity/object type.

Closing this issue for housekeeping purposes 🔒 Feel free to reopen if you want to discuss on that.

**Comment by danwoodbury** [comment]
Hi, I am having this exact problem but am new to graphql so im not sure on the best pattern to fix it.

Resulting in the error: `Error: Schema must contain unique named types but contains multiple types named "CloverLineSummaryItemModel"`

FieldResolver:
```
@FieldResolver()
    summary(@Root() codeCoverage: CodeCoverageModel): CloverLineSummaryModel {
        return this.codeCoverageService.generateLineSummary(codeCoverage.report.metrics._attributes);
    }
```

Service.ts function:
```
generateLineSummary(line: CloverLineSummaryType): CloverLineSummaryModel {
        const statements = CloverLineSummaryItemModel.create(line.coveredstatements, line.statements);
        const conditionals = CloverLineSummaryItemModel.create(line.coveredconditionals, line.conditionals);
        const methods = CloverLineSummaryItemModel.create(line.coveredmethods, line.methods);

        return CloverLineSummaryModel.create(statements, conditionals, methods);
    }
```

Does anybody have an idea on how to fix this?

Thanks

**Comment by 19majkel94** [comment]
@danwoodbury
It's a different error, probably you named your input class the same as object type class.

**Comment by mahaben** [comment]
Hello @MichalLytek, I'm facing a memory leak issue using type-graphql. I have a query that returns 1200 records which is called every 5minutes. Memory keeps increasing over the time and when I stop the query and take a memory snapshot, I realized the presence of a huge object of `TypeGraphqlMetadataStorage`. I'm new to graphql and dont know what I'm doing wrong. 

Any help would be appreciated!

<img width="1177" alt="Capture d’écran 2019-10-19 à 15 07 43" src="https://user-images.githubusercontent.com/12132174/67145510-6a069f80-f282-11e9-8452-ddafe06492bc.png">

**Comment by MichalLytek** [comment]
Don't build the schema on every request - cache the built schema e.g. in `global` property. This will lower the memory usage and response time.

**Comment by mahaben** [comment]
Thank you for you response. The schema is built once at server start. It is a singleton.

**Comment by MichalLytek** [comment]
So the problem is that the metadata storage has 153 kB?

**Comment by mahaben** [comment]
More ...Retained size shows 600MB

<img width="1171" alt="Capture d’écran 2019-10-19 à 15 20 50" src="https://user-images.githubusercontent.com/12132174/67145730-139a6080-f284-11e9-897d-714dbce684fe.png">

**Comment by trubi** [comment]
We are having the very same issue... any idea or progress? @mahaben @MichalLytek ? Thanks

**Comment by MichalLytek** [comment]
> We are having the very same issue...

This issue contains 3 different reports... what is your issue about?

**Comment by trubi** [comment]
Sorry, I am talking about the issue from @mahaben , huge memory consumption of typegraphql. Without typegraphql, this container was ok with 192MB of memory, with typegraphql, it's crashing all the time with 1GB

**Comment by MichalLytek** [comment]
So please write in #449 issue - it's propablby a Node.js leak in some 12.x versions.

**Comment by trubi** [comment]
We are using node 10.17.0
