### ISSUE TITLE
Schema documentation

### ISSUE THREAD

**Issue by dverlik** [19majkel94/type-graphql#143]
In graphql we can leave comments inside .graphql files which then are nicely displayed in graphiql or the playground. However, I can't get it to work with type-graphql.

**Comment by 19majkel94** [comment]
Comments? Do you mean descriptions?

https://19majkel94.github.io/type-graphql/docs/types-and-fields.html
```ts
@ObjectType({ description: "The recipe model" })
class Recipe {
  @Field(type => ID)
  id: string;

  @Field({ description: "The title of the recipe" })
  title: string;
}
```

**Comment by dverlik** [comment]
Oh.
