### ISSUE TITLE
No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.

### ISSUE THREAD

**Issue by theorye** [19majkel94/type-graphql#150]
**Describe the bug**
Warning while using ArgType or InputType that causes requests to materialize this warning:

No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.

**To Reproduce**
https://github.com/19majkel94/type-graphql/tree/master/examples/using-scoped-container

**Expected behavior**
No warning

**Enviorment (please complete the following information):**
 - OS: Windows 10 Pro
 - Node 10.4.0
 - Package version "^0.14.0"
 - TypeScript version 3.0.1

**Additional context**

**Comment by 19majkel94** [comment]
It's related to `class-validator` and this commit:
https://github.com/typestack/class-validator/commit/3b7c79a8bcb6bd88d84d8d1e15f958be534997d3

Basically, it warns that you don't have any metadatas in the storage, which means you haven't used any decorator from `class-validator`. That means you don't perform any validation, so you should just pass `validate: false` option to `buildSchema` to disable automatic validation.

**Comment by theorye** [comment]
I see.  That resolves the issue.  Thank you

**Comment by aishstha** [comment]
> It's related to `class-validator` and this commit:
> [typestack/class-validator@3b7c79a](https://github.com/typestack/class-validator/commit/3b7c79a8bcb6bd88d84d8d1e15f958be534997d3)
> 
> Basically, it warns that you don't have any metadatas in the storage, which means you haven't used any decorator from `class-validator`. That means you don't perform any validation, so you should just pass `validate: false` option to `buildSchema` to disable automatic validation.

Thanks for sharing. This is helpful!

**Comment by fsevenm** [comment]
> It's related to `class-validator` and this commit: [typestack/class-validator@3b7c79a](https://github.com/typestack/class-validator/commit/3b7c79a8bcb6bd88d84d8d1e15f958be534997d3)
> 
> Basically, it warns that you don't have any metadatas in the storage, which means you haven't used any decorator from `class-validator`. That means you don't perform any validation, so you should just pass `validate: false` option to `buildSchema` to disable automatic validation.

What is `buildSchema` and how can I find it to modify?
