### ISSUE TITLE
Default implicit resolvers for undefined properties return undesirable values

### ISSUE THREAD

**Issue by avkonst** [19majkel94/type-graphql#153]
**Describe the bug & Expected behavior**
I am not quite sure if it is a bug or intentional default behaviour. If it is intentional, I would like to know how to change it with some global setting.

The first issue is that the property of type `string | undefined` (field is declared as nullable) is resolved to `Hello world` string, when value of a property is not set on the instance, which is returned by a resolver. I would expect it to be resolved to `null of graphql`.

The second issue is that the property of type `string` (field is declared as non-nullable) is also resolved to `Hello world` string, when value of a property is not set on the instance, which is returned by a resolver. I would expect it to throw internal error (because such an error is actually trapped by typescript when it is used right).

Similar for properties of type `number`: resolvers return random numbers when values of properties are not defined. I would expect internal error thrown for non-nullable property and `null of graphql` for nullable property.

I have not checked what properties of types `boolean` and `array` return, but would expect consistent behaviour with the proposed above

**To Reproduce**

Source code to reproduce:
```typescript

@ObjectType()
@InputType('DescribedPlaceInput')
export abstract class DescribedPlace {
    @Column() // from typeorm, but it should not influence the behaviour of type-graphql
    @Field()
    name: string;

    @Column({ nullable: true })  // from typeorm, but it should not influence the behaviour of type-graphql
    @Field({ nullable: true })
    description?: string;
}

@ObjectType()
@InputType('PlaceInfoInput')
export abstract class PlaceInfo extends DescribedPlace { }

@Entity() // from typeorm, but it should not influence the behaviour of type-graphql
@ObjectType()
export default class Place extends PlaceInfo { }

// resolver
@Mutation(returns => PlaceInfo) // intentionally returns subtype of a Place
async createPlace(): Promise<Place> {
    return new Place();
}
```

**Logs**
The resolver returns the following:
```
{
  "data": {
    "createPlace": {
      "name": "Hello World",
      "description": "Hello World"
    }
  }
}
```

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node: 8.9.1
 - Package version: 0.13.1
 - TypeScript version: 2.9.2

**Comment by 19majkel94** [comment]
That's definitely not TypeGraphQL isssue as there's no `Hello World` string in the codebase 😆 

I bet you've set some kind of mocking that replace null/undefined with "Hello world":
https://www.apollographql.com/docs/graphql-tools/mocking.html

**Comment by avkonst** [comment]
I thought too, but could not find any in my code too. I will see if I can come up with the reproducer.

**Comment by avkonst** [comment]
My bad. Cancel this. It is wrong report. It was ApolloServer mocking, which I was not aware about when copied code sample from a tutorial. Thanks. All work as expected.
