### ISSUE TITLE
It should be possible to apply default InputType and ObjectType decorators to the same class

### ISSUE THREAD

**Issue by avkonst** [19majkel94/type-graphql#154]
**Is your feature request related to a problem? Please describe.**
I would like to use the same structure as input and output data. So, I attempted to annotate it like the following:
```typescript
@ObjectType()
@InputType()
export abstract class DescribedPlace {
    @Field()
    name: string;

    @Field({ nullable: true })
    description?: string;
}
```
This failed compilation of graphql schema with an error telling that DescribedPlace type is already defined. My workaround was the following:

```typescript
@ObjectType()
@InputType('DescribedPlaceInput') // <-- notice non-default name addition
export abstract class DescribedPlace {
    @Field()
    name: string;

    @Field({ nullable: true })
    description?: string;
}
```

**Describe the solution you'd like**
I would like the first code snippet to work without the workaround.

**Comment by 19majkel94** [comment]
RTFM! 😉 
https://19majkel94.github.io/type-graphql/docs/faq.html#in-many-cases-i-have-a-situation-where-inputtype-and-objecttype-have-exactly-the-same-shape-how-can-i-share-the-definitions

**Comment by avkonst** [comment]
Thanks. I have missed it in FAQ

**Comment by joseym** [comment]
Whew! I also overlooked the FAQ and embarrassingly spent way longer than I should have to try to make a class work as an input and an object. Embarrassingly because I never thought to pass a name as a parameter.

I hang my head in shame (and embarrassment, as previously stated).
