### ISSUE TITLE
Add the project to hacktoberfest

### ISSUE THREAD

**Issue by galkin** [19majkel94/type-graphql#161]
Thank you for awesome project!
Could you add this project to [hacktoberfest](https://hacktoberfest.digitalocean.com/)?
It's very simple, only `hacktoberfest` label creation is required.

**Comment by 19majkel94** [comment]
Sure! Thanks for the info 😉 
I've found only one issue for beginners for now (#53). Maybe in the future there will be more simple tasks to do.
Of course the easiest way to contribute is to find typos and grammar issues in docs 😄
