### ISSUE TITLE
Merge resolvers and types

### ISSUE THREAD

**Issue by lukejagodzinski** [19majkel94/type-graphql#165]
Cześć :)
Hi!

Great project but would have a few ideas how to improve it. I don't know if you're open for such radical changes but I will suggest them anyway. Just to give you a little bit of background. I'm the author of the [Astronomy](https://github.com/jagi/meteor-astronomy/) package for [Meteor](https://github.com/meteor/meteor). It's just the ORM inspired by PHP's Doctrine. So I work with the models/schemas a lot. A few years ago I switched to GraphQL and was planing on creating something similar to Astronomy but for GraphQL. I've discovered typeORM which is great library but doesn't solve all the problem of defining schema for GraphQL and I discovered your library which is almost perfect. So I could offer my help with development of your library if you're interested.

Ok, now let's move on to the problem. Right now you define all your resolvers in the class that is correlated with some type. If it's `Recipe` type then all its resolvers are defined in the `RecipeResolver` class. Which for most cases is ok. But I was developing some projects where there was no clear correlation between type and top level resolver. Something that would more likely be a part of the `QueryResolver` class.

The next problem is still having two separate classes, one for type and another for resolvers. As you know, in GraphQL you define all the types and resolvers just in one place and it would be great to have similar thing in `type-graphql`. There is nothing wrong about standard way of defining schema in GraphQL, it's just API that requires you to write a lot of code. With TypeScript and TypeGraphQL you make it simpler.

So I would like to suggest introducing the `Query` type (as well as `Mutation`) and move resolvers into types. Example could look as follows:

```ts
@ObjectType()
class Query {
  @Resolver(returns => Post, { nullable: true })
  post(@Arg("id") id: string) {
    return PostsRepository.findById(id);
  }

  @Resolver(returns => [Post])
  posts() {
    return PostsRepository.findAll();
  }
}

@ObjectType()
class Post {
  @Field()
  id: string;

  @Field()
  name: string;

  @Field()
  userId: string;

  @Resolver(returns => User)
  user() {
    return UsersRepository.findById(this.userId);
  }
}

@ObjectType()
class User {
  @Field()
  id: string;

  @Field()
  firstName: string;

  @Field()
  lastName: string;

  @Resolver(returns => [Post])
  posts() {
    return PostsRepository.findByUserId(this.id);
  }
}
```

Such approach would simplify API a lot. Right now you have `@Resolvers`, `@FieldResolvers` which are actually the same things but are used in different context.

I would probably create something like this by myself but don't want to reinvent the wheel and instead I would like to combine efforts.

Maybe this change would be impossible to implement and I'm missing some important detail of your design. So, I'm not saying that it's the perfect solution. Just started playing with your library and I see that API is a little bit too complicated to just create field resolver. And I don't mind having resolvers and field's definition in one place. Actually, I think it's a good thing. If you want to create separation you can always extract resolver functions into separate files.

Daj znać co o tym myślisz :)

**Comment by lukejagodzinski** [comment]
@19majkel94 thanks for the explanation. Right now it makes sense why you made such a design decisions. Actually I was planning on using DTO in the next version of my library because it's just a better way of doing things. So, just using DTO forces you to decouple types from resolvers.

However, does the DTO give you any benefits here? If it would be ORM then ok, but it's just a schema definition. You're not gonna work with objects of these types. Even in the example of mutation (in docs) you're using some utility function to create the `Recipe` object and store it in database.

If it goes about dependency injection, originally, I was thinking about using the context object to store repositories and access data and eventually mock context when testing. This is a pattern that I'm using currently and I've seen it being used widely.

Probably naming convention is not the most intuitive right now, but maybe it's just for me, because I didn't spend enough time with the library. I will play with it a little bit more. 

I just have a quick question. When I was playing with the lib, I've noticed that it's probably not possible to create type like:

```gql
type Post {
  tags: [String]!
}
```

Where the `tags` field can't be null but values in the array can (I know example is ridiculous but couldn't quickly come up with the better one :P). Is it possible or I'm just missing something?

**Comment by 19majkel94** [comment]
TypeGraphQL and other decorator based libraries (TypeORM, class-validators) are class oriented. So e.g. every args type or input type is converted to class instance to make validation work. The same goes to interfaces - object types implement `isTypeOf` using `x instanceof X` syntax, no `__typename` or other weird hacks. Without using instance, object types methods or getters would not be able to work.

I have no time to deliberate about DI vs. mocking context and DTO classes. That's how it's designed, it works well and if you don't like it - you can go back to `graphql-js` / `graphql-tools`, the same as some people don't like Nest and they stick to express/koa/restify.
