### ISSUE TITLE
In subscriptions, what should happen when a client webscoket disconnects without an unsubscribe

### ISSUE THREAD

**Issue by gae123** [19majkel94/type-graphql#176]
I have gotten the subscription decorators to work as expected, but now I notice that when the clients go away abnormally (eg the user closes the browser), the server side subscription code keeps being executed. I assume that this means that pubsub subscriptions are leaked when the client is disconnected this way.

Is there a way to catch this on the websocket disconnect and terminate those graphql subscriptions so that the pubsub mechanism subscriptions are freed as well? Is there any example code?

**Comment by 19majkel94** [comment]
Try to reproduce the error with pure `graphql-subscriptions`:
https://github.com/apollographql/graphql-subscriptions

TypeGraphQL only wraps it API, so as there's no `unsubscribe` property on `GraphQLFieldConfig`, I can't expose any hooks for that.

**Comment by 19majkel94** [comment]
Try to reproduce the error with pure `graphql-subscriptions`:
https://github.com/apollographql/graphql-subscriptions

TypeGraphQL only wraps it's API, so as there's no `unsubscribe` property on `GraphQLFieldConfig`, I can't expose any hooks for that.

**Comment by 19majkel94** [comment]
> the server side subscription code keeps being executed

What do you mean? Is the subscription method in resolver class is called n times where there's no connected client?

Can you show some of your code or more details about the issue and how to reproduce the error? 🤔

**Comment by gae123** [comment]
Thanks for the replies, I did restructure my code and do not see the issue any more. I will keep an eye on it, like you said earlier if there is an issue with subscriptions leaking it is probably in another module this module depends on. Thanks for the great work.

**Comment by 19majkel94** [comment]
Thanks! So feel free to reopen this issue when the problem appears again 🔒
