### ISSUE TITLE
Declare list is arg parameters.

### ISSUE THREAD

**Issue by yantrab** [19majkel94/type-graphql#177]
I get error when it try to declare list in arg type.
```

  @Query(returns => [Asset], { description: "Get assets by ids" })
  async assets(@Arg("ids") title: AssetInput[]): Promise<Asset[]> {
    return await Asset.findAll({where:{id:{[Op.in]:[]}}})
  }
```

AssetInput is {id:string, type:string}, but i get error in string[] too.

the error is : 

`Error: You need to provide explicit type for AssetResolver#assets parameter #0 !`

Thanks.

**Comment by 19majkel94** [comment]
https://19majkel94.github.io/type-graphql/docs/types-and-fields.html

`assets(@Arg("ids", type => [AssetInput]) title: AssetInput[])`
