### ISSUE TITLE
Give a type for the @Field type parameter, not a class

### ISSUE THREAD

**Issue by OwenCalvin** [19majkel94/type-graphql#178]
Hello,
Is it possible to give a type to the @Field() type parameter ?
Is it possible now ? Or in the future ?

# Whats do I want to do:
To just use:
`RakkitQueryArgs<PageArgs>`
(PageArgs is described in the next screenshot)

![Example](https://user-images.githubusercontent.com/17951357/47287274-f8a1fb80-d5f1-11e8-8e40-f79888c8ea57.png)

# What I need to do to now:
![image](https://user-images.githubusercontent.com/17951357/47287380-5898a200-d5f2-11e8-8ebd-dfd59d5631c1.png)
![image](https://user-images.githubusercontent.com/17951357/47287438-81b93280-d5f2-11e8-9e74-8f6805bc6659.png)

**Comment by 19majkel94** [comment]
Right now it's not possible, you can only extend the base class and add some properties to it.

Covered by #180 📈
