### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by 19majkel94** [19majkel94/type-graphql#18]
- [x] introduction/getting started guide
- [x] simpler and better readme
- [x] docs folder on repo with feature descriptions and usage samples
  - [x] scalars @19majkel94
  - [x] automatic validation @19majkel94
  - [x] DI @19majkel94
  - [x] interfaces and inheritance @19majkel94
  - [x] types (fields) @19majkel94
  - [x] resolvers @19majkel94
  - [x] others (new features should have docs created in time)

**Comment by pablocarreraest** [comment]
hi @19majkel94, 
I love you protect also If you need a extra hand I'm here to collaborate

**Comment by 19majkel94** [comment]
Hi @pablocarreraest! It's nice to hear that! 😊 

Today I will try to do the `custom scalars` docs so you will see what is my vision of the docs. 
So then we can collaborate on docs together, PRs are welcome 😉

**Comment by 19majkel94** [comment]
@pablocarreraest 
I've just created the first doc page 😃 
https://github.com/19majkel94/type-graphql/blob/master/docs/scalars.md

**Comment by pablocarreraest** [comment]
nice I will make resolver and types

**Comment by 19majkel94** [comment]
@pablocarreraest 
I don't hustle, just asking about the docs status - do you plan to help me with this in near feature, or you've rejected usage of this framework in your projects by now? 😉

**Comment by pablocarreraest** [comment]
I’m in... just I Get very busy this days for Sunday I will give you the PR if that is alright for you...

**Comment by 19majkel94** [comment]
That's cool! No need to hurry, I have many other tasks to do 😉

**Comment by stonecold123** [comment]
The resolver is missing this useful feature:

````
    const schema = await buildSchema({
        resolvers: ['../../resolver/*.js'],
    });
````

**Comment by 19majkel94** [comment]
@stonecold123 
It's not merged yet:
https://github.com/19majkel94/type-graphql/blob/docs/docs/bootstrap.md#create-executable-schema
