### ISSUE TITLE
Customizing the schema build process

### ISSUE THREAD

**Issue by tonyxiao** [19majkel94/type-graphql#186]
In a given class, i have resolver methods and non-resolver methods. i wanted to be able to at a glance / in other classes easily tell which method is a resolver method and which method is not. So I was thinking of adding a `$` in front of all the resolver methods without having to individually set the `name` option for every resolver. This turns out not to work due to GeneratingSchemaError -> `Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"$resolverMethod\" does not`. 

Is there a way to customize the schema build process and wholesale remove illegal symbols from resolver names?

**Comment by 19majkel94** [comment]
> Is there a way to customize the schema build process and wholesale remove illegal symbols from resolver names?

No. You can only overwrite the method name by providing new name in decorator.
This issue is related to #156 where you provide a custom function that will receive method and class name and produce the name in schema.
