### ISSUE TITLE
How to get data without funtion name in data

### ISSUE THREAD

**Issue by chengjia0807** [19majkel94/type-graphql#187]
Hi,

Now I can make the graphql query working on my project and it show result like this:

{
  "data": {
    "getUser": {
      "firstName": "JJJJ",
      "lastName": "fff"
    }
  }
}

getUser is actually the function name in Resolver, I don't want this layer to be shown on my final output.

Is there a way to avoid that?

Thanks
CJ

**Comment by 19majkel94** [comment]
> Is there a way to avoid that?

No. That's how GraphQL works and it's described in specification of GraphQL.

> You can see immediately that the query has exactly the same shape as the result. This is essential to GraphQL, because you always get back what you expect, and the server knows exactly what fields the client is asking for.

https://graphql.org/learn/queries/

So, because you may ask for a few things in one query:
```graphql
query {
  categories {
    id
    name
  }
  recipes {
    title
    ingredients {
      name
    }
  }
}
```

You have to be able to distinguish the returned data:
```json
{
  "data": {
    "categories": [...],
	"recipes": [...]
  }
}
```
