### ISSUE TITLE
Best way to write tests with Inversify?

### ISSUE THREAD

**Issue by j** [19majkel94/type-graphql#191]
Is it sufficient to write functional tests with Inversify + type-graphql like so:

```typescript
  // ...

  let schema;

  beforeEach(() => {
    jest.clearAllMocks();
    container.snapshot();

    schema = buildSchema({
      resolvers: [/* all my resolvers */]
    });
  });

  afterEach(() => {
    container.restore();
  });

  // ... tests here
```

I'm running into weird issues where I query the GraphQL with the created schema, in my resolver, It's returning the correct object, but in my test, returns GraphQL errors & null data which makes no sense...

**Comment by 19majkel94** [comment]
you can build the schema once, there's no need to clear it each time

**Comment by 19majkel94** [comment]
>  It's returning the correct object, but in my test, returns GraphQL errors & null data which makes no sense...

Hard to say what is a problem, I would need a simple reproduction repo as I've never used inversify.

**Comment by 19majkel94** [comment]
Closing for housekeeping purposes as the issue looks abandoned 🔒
