### ISSUE TITLE
make graphql a peer-dependency

### ISSUE THREAD

**Issue by mechanical-turk** [19majkel94/type-graphql#192]
**Is your feature request related to a problem? Please describe.**

I've been having issues with using libraries from the rich graphql ecosystem along with type-graphql. I believe as the ecosystem is moving to v 14.0.0, not all the packages are moving as fast as the rest. This creates a very messy node_modules folder with duplicate instances (and different versions) of the graphql package. deduping and flat installs help, but not always. 

**Describe the solution you'd like**
You can also propose how the new API should looks like.

The solution seems to be moving graphql to a peer dependency, but I dont know how much work that would entail, or if it's feasible at all. Recently, I came across this article by one of the co-authors of graphql: https://medium.com/@leeb/graphql-js-preparing-for-v14-0-0-839f823c144e. He asks that as the ecosystem moves towards v14, companion projects (such as this one) list graphql as a peer dependency, in hopes that package resolution becomes less hectic.

Thanks for your attention. Just wanted to bring this to your attention. Keep up the good work!

**Comment by 19majkel94** [comment]
If you read the comments of this article, you will see my question and Leo's answer:
> Presumably if you’re completely hiding away the graphql-js API, then your users will not be using graphql-js in any other way so it’s probably safe to continue to use a normal dependency.

And as other packages are hiding `graphql-js` package from user by making it a dependency:
https://github.com/prisma/graphql-yoga/blob/46a69d3f9ab3e0e58d887867e5c409b5b3fa6aeb/package.json#L49
switching to peer-dependency by TypeGraphQL won't solve that problem.

Already discussed in #140 and #144, we won't switch to peer-dependency for now. I will keep an eye on the ecosystem and reconsider this again in the future.
