### ISSUE TITLE
Subscription invocation scope

### ISSUE THREAD

**Issue by urossmolnik** [19majkel94/type-graphql#214]
**Is your feature request related to a problem? Please describe.**
I want to use DataLoader scoped to subscription invocation (topic event).   
Why: because subscription function gets invoked for every connected client. I want to cache possible queries I have to do in subscription function between these invocations.  

**Describe the solution you'd like**
DI Container can be scoped with help of context.  
For queries and mutations we can scope it per request.  
For subscriptions we can only scoped it per connection. It would be great if we could scope it per subscription invocation (topic event).  

**Describe alternatives you've considered**
I don't see a way how to do this currently. Am I missing something?

**Additional context**
/

**Comment by 19majkel94** [comment]
I'm not sure if it's possible at all. If the context is the same, how can I detect that it's an another topic trigger for this client?

The idea behind scoped containers is that they are per request, so per user, isolated, no potential data leaks. So as the subscription is scoped per connection, it solves this problem.

You have to show me your use case, when you need a fresh instance of the resolver class with fresh services for each subscription trigger for each trigger. It sounds like horrible things from the performance and memory usage perspective.

**Comment by urossmolnik** [comment]
@19majkel94 
Yes, it can't be context based and yes, scoped container on this level is probably a bad idea.  
As you pointed out, it would not be clear they are shared between users and would bring big performance/memory usage.

My use case is I want to cache some results between function invocations for the same trigger and clear that cache after all invocations are done.  

For example, I have news feed and 1000 users are listening for new items.  
Event is fired that new item exists but event does not contain all the data needed for the response.  
Extra data has to be fetched before forming response and this data can be cached between these 1000 invocations.  
To complicate it further I was trying to fetch this extra data in FieldResolver function so it is fetched only if needed 🙉. This is how I came to scoped container, since I have to inject something in Resolver with lifetime of trigger.    

Since we agree scoped container on trigger level is a bad idea, would there be a way to have "cache object" with lifetime of trigger injected in Subscription function?  
Or maybe have ability to define "event resolver" that would get fired once per trigger if subscription function is actually fired. That's where you could supplement event data. Scoping container for this "event resolver" would be an issue again, but it could just be decided it can't have custom scopes and has only global scope.

**Comment by 19majkel94** [comment]
> Since we agree scoped container on trigger level is a bad idea, would there be a way to have "cache object" with lifetime of trigger injected in Subscription function?

This shouldn't be TypeGraphQL responsibility.

> Extra data has to be fetched before forming response and this data can be cached between these 1000 invocations.

Why you can't just cache the data on the service side?

```ts
@Resolver()
class SampleResolver {
  constructor(
    private subscriptionDataService: SubscriptionDataService,
  ) {}

  @Subscription(type => Item, { topics: "newItem" })
  newItem(@Root() itemId: number) {
    // it will be called 1000 times
    // but will call the DB only once per 5-10-15s
    // (return the result from it's own cache)
    return this.subscriptionDataService.getData(itemId);
  }
```
