### ISSUE TITLE
Thrown Errors in Resolvers Swallow Original Error Type

### ISSUE THREAD

**Issue by benawad** [19majkel94/type-graphql#215]
**Describe the bug**
Thrown Errors are losing their class.

In my resolver:

```
  @Query(() => String)
  hello() {
    throw new ApolloError("bad stuff");
  }
```

The error is not an instance of `ApolloError` in `formatError`

```
  const server = new ApolloServer({
    schema,
    formatError: (e: GraphQLError) => {
      if (e instanceof ApolloError) {
        console.log("you should see me");
      }

      return e;
    }
  });
```

**To Reproduce**
https://github.com/benawad/type-graphql-swallow-error

**Comment by 19majkel94** [comment]
That's how `graphql-js` works - it wraps the original error into a `GraphQLError` instance to provide metadata about the query (location, path, etc.).

But you can still access the original error (`ApolloError`) by reading the `e.originalError` property:
```ts
if (e.originalError instanceof ApolloError) {
  console.log("you should see me");
}
```
