### ISSUE TITLE
Add onSubscribe / onUnsubscribe or an alternative

### ISSUE THREAD

**Issue by ForsakenHarmony** [19majkel94/type-graphql#220]
**Is your feature request related to a problem? Please describe.**
My events come from an external source and I'd like to subscribe to / unsubscribe from it when the clients starts / stops a subscription

**Describe the solution you'd like**
I haven't found anything, but I'd like to have some kind of handler i.e. `onSubscribe` `onUnsubscribe` if it doesn't exist yet

**Comment by ForsakenHarmony** [comment]
oh yeah, that works, would be nice if you could somehow set that per `@Subscription`

**Comment by 19majkel94** [comment]
@ForsakenHarmony 
Unfortunately, all I can expose is `onSubscribe`. There's no `onUnsubscribe` hook in `graphql-js` or `graphql-subscriptions`:
https://github.com/graphql/graphql-js/blob/383c0d16b062d06b54ab29a841e762db92f296dd/src/type/definition.js#L810-L822

I think you need to have a custom pubSub that collects all subscriptions registering and then clean it manually on `websockets` disconnect.

**Comment by ForsakenHarmony** [comment]
oh, right you just pass the schema to apollo server, sorry didn't think about that

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒

**Comment by Adam-Burke** [comment]
> https://github.com/graphql/graphql-js/blob/383c0d16b062d06b54ab29a841e762db92f296dd/src/type/definition.js#L810-L822

is there any plan for this?

**Comment by Adam-Burke** [comment]
> @ForsakenHarmony
> Unfortunately, all I can expose is `onSubscribe`. There's no `onUnsubscribe` hook in `graphql-js` or `graphql-subscriptions`:
> https://github.com/graphql/graphql-js/blob/383c0d16b062d06b54ab29a841e762db92f296dd/src/type/definition.js#L810-L822
> 
> I think you need to have a custom pubSub that collects all subscriptions registering and then clean it manually on websocket disconnect.

Is there any plan for this?

**Comment by MichalLytek** [comment]
Plans for what @Adam-Burke?

**Comment by guotie** [comment]
How to add onSubscribe hook?
