### ISSUE TITLE
Prisma Client "User" Type conflict with TypeGraphQL "User" Type 

### ISSUE THREAD

**Issue by Artimal** [19majkel94/type-graphql#223]
Hi, I create simple app with GraphQL Yoga, Prisma and TypeGraphQL.

Context TS interface with Prisma type:
```ts
export interface Context {
  user?: AuthUser;
  prisma: Prisma;
}
```

Box TS type:
```ts
@ObjectType()
export class Box {
  @Field(type => ID)
  id: string

  @Field({ nullable: true })
  name?: string

  @Field(type => Int, { nullable: true })
  items?: number
    
  @Field(type => User)
  owner: User
}
```

Prisma datamodel Box:
```graphql
type Box {
  id: ID! @id
  name: String @default(value: “”)
  items: Int @default(value: 0)
  owner: User
}
```

In Box resolver:
```ts
@Authorized()
@Mutation(returns => Box)
async deleteBox(@Args() args: DeleteBoxArgs, @Ctx() context: Context): Promise<Box> {
  return context.prisma.deleteBox({ id: args.id });
}
```

PROBLEM:
```
[ts]
Type ‘Box’ is not assignable to type ‘Box’. Two different types with this name exist, but they are unrelated.
Property ‘owner’ is missing in type ‘Box’.
```

How to avoid this kind of type conflicts? Please for help.

**Comment by 19majkel94** [comment]
> Property ‘owner’ is missing in type ‘Box’.

I don't get it 😕 
@Artimal Please create a repository with a minimal reproducible code example. I haven't used Prisma, #217 will probably use the new datamodel api.

**Comment by Artimal** [comment]
Prisma Client was incongruent with Prisma Server. After adding manually `owner: WhereUserInput;` it started to work. I already leaved Prisma and got TypeORM instead, it is going to fit much better with TypeGraphQL.
