### ISSUE TITLE
Skip superfluous type conversion

### ISSUE THREAD

**Issue by lenartbezek** [19majkel94/type-graphql#229]
`convertToType` helper from `helpers/types.ts` will convert type, even if `data` is already of `Target` type.

https://github.com/19majkel94/type-graphql/blob/master/src/helpers/types.ts#L80

Could be avoided by adding
```ts
  if (data instanceof Target) {
    return data;
  }
```
and potentially fix issues when using any kind of logic in object type constructors.

**Comment by 19majkel94** [comment]
@lenartbezek 	
Feel free to make a PR with that change 😉 
But remember to add a test case about this feature (and fix other tests if it brokes them).

**Comment by Agreon** [comment]
Hey I would like to create my first PR with this ticket :) Can you move it to "In Progress"? I don't think i have the right to do so.

**Comment by 19majkel94** [comment]
Closing as fixed via 7bddb04 🔒
