### ISSUE TITLE
How to write tests for resolvers

### ISSUE THREAD

**Issue by 4ware** [19majkel94/type-graphql#231]
Hi!

I just wanted to write tests for my resolvers but don't know how to start. I'm using ts-jest...

Do you have an example and could you integrate something into the documentation?

Cheers, Kai

**Comment by 19majkel94** [comment]
@4ware 
Integration tests are the same as with any other graphql framework - execute a query against the built schema. You can see plenty of this kind of functional tests here in the `tests` folder:
https://github.com/19majkel94/type-graphql/blob/master/tests/functional/validation.ts#L93

You can also follow the @benawad video series with tutorials about testing TypeGraphQL's app:
https://www.youtube.com/watch?v=zR8jKR9hnFA

**Comment by 4ware** [comment]
I see. Thanks a lot!

**Comment by Siafu** [comment]
> @4ware
> Integration tests are the same as with any other graphql framework - execute a query against the built schema. You can see plenty of this kind of functional tests here in the `tests` folder:
> https://github.com/19majkel94/type-graphql/blob/master/tests/functional/validation.ts#L93
> 
> You can also follow the @benawad video series with tutorials about testing TypeGraphQL's app:
> https://www.youtube.com/watch?v=zR8jKR9hnFA

I'm struggling with testing a service I created with property injection using @Inject decorator. 

I have tried both constructor and property injection. 
```
@Service()
export class AuthOktaService {
  constructor(@Inject("OktaConfig") private oktaConfig: OKTAConfigOptions) {}
  @Inject("OktaConfig")
  OktaConfig: OKTAConfigOptions;
  @Inject("OktaJwtVerifier")
  oktaJwtVerifier: OktaJwtVerifier;
  @Inject("OktaAuthClient")
  authClient: OktaAuthClient;
```
Test
```
describe("Okta Service", () => {
  it("signIn should return redirect url with code", ()=> {
    const oktaService = new AuthOktaService();
    fetchMock.mockResponseOnce(JSON.stringify({ data: '12345' }))
    oktaService.getAuthCodeResponse('user','pass').then(res => {
      expect(res).toEqual(authMock.redirectUrl)
    })
    console.log(fetchMock.mock.calls.length)
  });
```

logout 
```
 console.log(this.OktaConfig
```

Error

```
console.log src/services/auth-okta.ts:3166
    undefined

```

**Comment by MichalLytek** [comment]
If you use:
> `constructor(@Inject("OktaConfig") private oktaConfig: OKTAConfigOptions) {}`

This won't work:
> `const oktaService = new AuthOktaService();`

I assume you use NestJS, so in that case you need to do `const oktaService= testingModule.get(AuthOktaService);`
https://docs.nestjs.com/fundamentals/testing
