### ISSUE TITLE
Get list of requested fields

### ISSUE THREAD

**Issue by RevanScript** [19majkel94/type-graphql#232]
Hi!

Is it possible to get a list of requested fields? For example, user performs the following query:

```gql
{
    id
    user {
        id
        firstName
    }
}
```

And I would like to know what fields were requested by user, in `FieldResolver` for example:

```typescript
@FieldResolver()
user(
    @Root() parent: ParentEntity,
    @RequestedFields() fields: string[],
) {
    /** if only id is requested, there's no need to execute unnecessary
      * request to the database, so I can just return:
      * { id: parent.user }
     **/
}
```

Maybe there's a better way to do it, but I couldn't find it yet.

Thanks!

**Comment by 19majkel94** [comment]
See #10 - for now use `@Info()` and parse it manually.
