### ISSUE TITLE
Optional middleware

### ISSUE THREAD

**Issue by smithki** [19majkel94/type-graphql#252]
**Is your feature request related to a problem? Please describe.**
I would really like to have optional middleware! I've come up against a corner case where I have a resolver that shares/composes the functionality of another resolver. With dependency injection, accessing those common methods is simple, but applying middleware is not 😞. Optional middleware that is applied based on the query context solves my problem. For instance, I can apply `x` middleware only when the return type is `y`.

**Describe the solution you'd like**
Here's what I'm currently doing to achieve this... I think it would be great to add at a framework level:

```ts
function isConstructor(o: any) {
  try {
    Reflect.construct(String, [], o);
  } catch (err) {
    return false;
  }
  return true;
}

/**
 * Selectively use middlewares based on a condition.
 */
function OptionalMiddleware<TContext = {}>(
  condition: ((action: ResolverData<TContext>) => boolean) | boolean,
  ...middleware: Middleware[]
) {
  const middlewareProxies = middleware.map(m => {
    const isConstructable = isConstructor(m);
    const middlewareInst = isConstructable ? new (m as any)() : m;
    const isClassMiddleware = !!Object.getPrototypeOf(middlewareInst).use;
    const middlewareHandler = isClassMiddleware
      ? Object.getPrototypeOf(middlewareInst).use.bind(middlewareInst)
      : middlewareInst;

    const resolveCondition = (_: ResolverData<TContext>) =>
      typeof condition === 'function' ? (condition as any)(_) : condition;

    return new Proxy(middlewareHandler, {
      apply: (target, thisArg, argArray) => {
        return resolveCondition(argArray[0])
          ? Reflect.apply(target, thisArg, argArray)
          : Reflect.apply((_: ResolverData<TContext>, next: NextFn) => next(), thisArg, argArray);
      },
    });
  });

  return UseMiddleware(...middlewareProxies);
}
```

**Comment by 19majkel94** [comment]
> Optional middleware that is applied based on the query context solves my problem

Why not just wrap other middleware with custom middleware that checks the context and do:
```ts
if (ctx.foo === "bar) return next()
return middleware(resolverData);
```

I don't understand what is your use case, what are you trying to achieve and how the API should look like for you 😉

**Comment by smithki** [comment]
Yeah, I've "over-engineered" a bit. Writing a wrapper middleware is easier ;)

I'll close for now, but if something else comes up I'll re-open.
