### ISSUE TITLE
@Args decorator + argument destructuring breaks linting with eslint

### ISSUE THREAD

**Issue by rfermann** [19majkel94/type-graphql#256]
**Describe the bug**
When linting code with `eslint` and the `@typescript-eslint/parser`, the process breaks, if destructuring is used for the `@Args` argument. Linting runs fine, if the argument isn't destructured.

**To Reproduce**
A minimal repository to reproduce: https://github.com/rfermann/args-decorator-parser-error.

`async something(@Arg("data") { email }: SomeInput): Promise<boolean> {` breaks linting.
`async something(@Arg("data") data: SomeInput): Promise<boolean> {` does not break linting.

Replacing the `@Args` decorator with another decorator, e.g. the `@Ctx` decorator, works fine. This indicates some issue with this `@Args` decorator instead of the `@typescript-eslint/parser`.

**Expected behavior**
Linting should work with and without destructuring.

**Logs**

> eslint index.ts
>
>TypeError: Cannot read property 'type' of undefined
>    at isForInRef (C:\Users\parser-issue\node_modules\eslint\lib\rules\no-unused-vars.js:434:24)
>    at variable.references.some.ref (C:\Users\parser-issue\node_modules\eslint\lib\rules\no-unused-vars.js:471:21)
>    at Array.some (<anonymous>)
>    at isUsedVariable (C:\Users\parser-issue\node_modules\eslint\lib\rules\no-unused-vars.js:470:40)
>    at collectUnusedVariables (C:\Users\parser-issue\node_modules\eslint\lib\rules\no-unused-vars.js:582:26)
>    at collectUnusedVariables (C:\Users\parser-issue\node_modules\eslint\lib\rules\no-unused-vars.js:589:17)
>    at Program:exit (C:\Users\parser-issue\node_modules\eslint\lib\rules\no-unused-vars.js:634:36)
>    at listeners.(anonymous function).forEach.listener (C:\Users\parser-issue\node_modules\eslint\lib\util\safe-emitter.js:45:58)
>    at Array.forEach (<anonymous>)
>    at Object.emit (C:\Users\parser-issue\node_modules\eslint\lib\util\safe-emitter.js:45:38)

**Enviorment:**
 - OS: Windows 10
 - Node v10.11.0
 - Package version 0.16.0
 - TypeScript version 3.3.1

**Comment by 19majkel94** [comment]
> This indicates some issue with this `@Args` decorator

No, it indicates that eslint parser has problem with arguments of decorator factory. Please open an issue in `@typescript-eslint/parser` repository instead.

**Comment by rfermann** [comment]
Why does it work with the `@Ctx` decorator, then? Shouldn't the same problem appear here, if it is a parser issue?

**Comment by 19majkel94** [comment]
`@Args` is a normal decorator, I can't do anything about it, sorry.

Try to reproduce the issue with renaming the arg, creating own decorator with similar signature, etc.
