### ISSUE TITLE
Is it possible to use with apollo-client and react

### ISSUE THREAD

**Issue by dharric** [19majkel94/type-graphql#257]
Is it possible to use type-graphql in react with apollo-client?

**Comment by 19majkel94** [comment]
No, Apollo Client is for fetching GraphQL data to client, while TypeGraphQL is for building the GraphQL server.

However, you might be interested in `apollo-link-state` (#197) or `[apollo-link-schema](https://www.apollographql.com/docs/link/links/schema.html)` - it should work using the `type-graphql@next` version.

**Comment by 19majkel94** [comment]
Closing this for a housekeeping purposes 🔒

**Comment by austineshimenga** [comment]
xdddssdsdsdsd
