### ISSUE TITLE
Succinct Docs on Decorators

### ISSUE THREAD

**Issue by Altrum** [19majkel94/type-graphql#262]
**Describe the issue**
I'm trying to find succinct information on decorators that can be used for type-graphql. For example, I see that `@Args()` can take in one or more arguments--but I couldn't find any information on what these arguments are and what order they should be in.

Is it that I can't find a page on the docs or is this just lacking?

**Comment by xanaxx** [comment]
That's WIP. Already there's issue for that. #17

**Comment by 19majkel94** [comment]
> but I couldn't find any information on what these arguments are and what order they should be in.

Just use "Go to Definition (F12)" or click the verb with CTRL in VSCode - it will show you all the overloads and the signature. It's very simple - `ReturnTypeFunc` when the reflection can't handle the type and `ValidateOptions` for `class-validator` options:

```ts
export function Args(
  paramTypeFunction: ReturnTypeFunc,
  options?: ValidateOptions,
): ParameterDecorator;
```

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
