### ISSUE TITLE
emitSchemaFile: Create directory automatic

### ISSUE THREAD

**Issue by mszekiel** [19majkel94/type-graphql#266]
Using `emitSchemaFile` from `buildSchema` I want to show directory in which `.gql` file will be stored. But target location is not being created, I have to create it by myself.  I'd like to use it simple by passing directory only, with automatic directory creation.

**Comment by xanaxx** [comment]
@19majkel94 what's the node version requirement? Node `v10.12.0` implements recursive mkdir so `emitSchemaDefinitionFile` functions could be clean and stay native.

**Comment by 19majkel94** [comment]
@xanaxx 
https://github.com/19majkel94/type-graphql/blob/40d86913ba30411d000d02b27d4f3c7c16463786/.travis.yml#L5-L9

I will drop v6 in the end of April 2019.

**Comment by 19majkel94** [comment]
Closed by #269 🔒
