### ISSUE TITLE
Initialization of class properties in an InputType throws a ConflictingDefaultValuesError 

### ISSUE THREAD

**Issue by k0rn1** [19majkel94/type-graphql#273]
**Describe the bug**
I am getting a ConflictingDefaultValuesError using the following input type. My guess is that this line [schema-generator.ts](https://github.com/19majkel94/type-graphql/blob/37a2d10a246de9bc86fa3e162b89750702914b95/src/schema/schema-generator.ts#L123) should not check equality, but instead check for the same type.

If I remove the assignment to template Typescript throws a warning the this property is not properly initialized. If I add the default option in the Field decorator the Error still occurs.
Now I could add an ! at the end, but I would also like to use this class for elsewhere in the the code without using type-graphql for the object generation and therefore use the default initialization of properties.

**To Reproduce**
My input type :
```
@InputType()
class CreateSlideInput implements Partial<Slide> {
  @Field(() => [CreateSlideContentInput], { nullable: true })
  public contents?: CreateSlideContentInput[];

  @Field(() => CreateSlideTemplatesInput)
  public template: CreateSlideTemplatesInput = new CreateSlideTemplatesInput();

  @Field(() => [Constants.Slide.TYPE])
  public types?: Constants.Slide.TYPE[];

  @Field(() => StructureFields)
  public structure: StructureFields = new StructureFields();

  @Field(() => ResponsibleFields, { nullable: true })
  public responsible?: ResponsibleFields = new ResponsibleFields();
}
```

**Expected behavior**
I would expect that the initialization of template in the input type with `new CreateSlideTemplatesInput()` is valid

**Logs**
 (The 'template' field of 'CreateSlideInput' has conflicting default values. Default value from decorator ('[object Object]') is not equal to the property initializer value ('[object Object]').")

**Enviorment (please complete the following information):**
 - OS: Linux
 - Node 8.10
 - Package version 0.17.0
 - TypeScript version 3.3.3

**Additional context**
none

**Comment by k0rn1** [comment]
The error disappeared when I deleted all node_modules  and reinstalled all again. I am closing this.

**Comment by 19majkel94** [comment]
Right, I can confirm that initializing nested inputs works:

```ts
  @Field()
  nested: NestedInput = new NestedInput();
```

```graphql
input NestedInput {
  field: String!
}

input RecipeInput {
  title: String!
  description: String
  nested: NestedInput = {}
}
```
