### ISSUE TITLE
Validation breaks when using class-validators useContainer

### ISSUE THREAD

**Issue by otbe** [19majkel94/type-graphql#274]
**Describe the bug**
Im evaluating switching from a classic apollo server + SDL setup to `type-graphql`. For validating input objects I use `class-validator`in a lot of resolvers with custom validators. I followed your example (https://github.com/19majkel94/type-graphql/blob/master/examples/automatic-validation/recipe-input.ts) and added some basic validations to my input objects, but I observed no validation at all. Even simple validations like `@MinLength(2)` dont throw an error.

The only notiecable difference between your example and my code is that I am using `useContainer(Container)` from `class-validator` and after commenting out this peace it starts working.

I guess is it somehow related to this [line](https://github.com/19majkel94/type-graphql/blob/master/src/resolvers/validate-arg.ts#L24). The Validator should be instantiated by the IoC container (if used), see https://github.com/typestack/class-validator#using-service-container

**To Reproduce**
Use my fork here https://github.com/otbe/type-graphql/blob/broken-validation/examples/automatic-validation/index.ts#L8 to verify this behavior. Use an exmaple query like this one (which should fail validation)
```
mutation {
  addRecipe(input: { title: "foo", description: "short" }) {
    title
  }
}
```

Note: I was able to verify my guess from above by replacing 
```
const { validateOrReject } = await import("class-validator");
```

with

```
const { validateOrReject } = Container.get(Validator);
```

**Expected behavior**
It should work :)

Thank you very much :)

**Comment by 19majkel94** [comment]
It shouldn't be a problem - that's what `class-validator` is doing internally.

https://github.com/typestack/class-validator/blob/95916a33abb077c3c63eb30eeeafc7cd19eb7c24/src/index.ts#L43-L51

Are you sure that you set `useContainer(Container)` before you import some files with `class-validator` decorators?

**Comment by otbe** [comment]
Thats obviously true 🙈
An "Organize imports" in our index.ts destroyed the proper order. 
Closeing it...thanks 👍

**Comment by 19majkel94** [comment]
That's why I have a separate `bootstrap` file that takes care of `useContainer` and other `ts-config-paths` initialization - index.ts is then responsible for ApolloServer or something, not the base technical things.

**Comment by otbe** [comment]
Thats what we did too, but the import of this bootstrap file was moved to the bottom of the import section :/
