### ISSUE TITLE
Using union types to implement the Relay Global Object Identification Specification

### ISSUE THREAD

**Issue by MrBoolean** [19majkel94/type-graphql#275]
First of all: Thanks for that great piece of software.

We're building a GraphQL Endpoint which will be used by several Clients to display & mutate data.
To make it as easy as it is possible we've decided to make the GraphQL Endpoint relay compatible.

The most parts of the relay spec were easy to implement. But as you might guess, there is one part we're currently stuck with: the Relay Global Object Identification Specification.

The Global Object Identification Specification defines that each "main"-type must be identifiable by an unique id. The unique identifier can be used to load data from a query with the following schema:

```
node(id: ID!): ...
```

Some relay clients are using `Query.node` to extend their local cache with additional fields from the GraphQL endpoint. This usually happens if some pieces are already known.

We're using the TypeGraphQL `createUnionType` function to generate the "NodeQueryResult" union. All included types are implementing an interface called "Node".

Lets head over to the extracted example implementation.

The Node interface looks like this:

```typescript
import { InterfaceType, Field, ID } from "type-graphql";

@InterfaceType()
export abstract class Node {
  @Field(() => ID)
  id: string;
}
```

The "Node" interface is used by each "main" type:

```typescript
import { ObjectType, Field } from "type-graphql";

@ObjectType({ implements: Node })
export class User implements Node {
  id: string;

  @Field()
  emailAddress: string;
}
```

```typescript
import { ObjectType, Field } from "type-graphql";

@ObjectType({ implements: Node })
export class Account implements Node {
  id: string;

  @Field()
  name: string;
}
```

Both types are combined using createUnionType:

```typescript
import { createUnionType } from "type-graphql";

const NodeQueryResult = createUnionType({
  name: "NodeQueryResult",
  types: [User, Account]
});

export { NodeQueryResult };
```

The resolver looks like this:

```typescript
import { Resolver, Arg, ID, Query } from "type-graphql";
import { Inject } from "typedi";

@Resolver()
export class NodeResolver {
  @Query(() => NodeQueryResult, { nullable: true })
  async node(
    @Arg("id", () => ID) id: string
  ): Promise<null | typeof NodeQueryResult> {
    // ... load & return the data from our datastore

    // otherwise, return null
    return null;
  }
}
```

As described on top of the Relay Global Object Identification Specification page a node query looks like this:

```graphql
{
  node(id: "...") {
    id
    ... on User {
      emailAddress
    }
  }
}
```

With TypeGraphQL we're facing the following error:

> Cannot query field \"id\" on type \"NodeQueryResult\". Did you mean to use an inline fragment on ...

I was able to fix the issue by using `@Query(() => Node)` instead of `@Query(() => NodeQueryResult)`. But I think, it would be a great improvement if the library extracts the underlying interfaces and exposes the fields in the union type directly.

**Comment by 19majkel94** [comment]
> But I think, it would be a great improvement if the library extracts the underlying interfaces and exposes the fields in the union type directly.

It would be great but do you know how to make it?
TypeGraphQL only wraps `graphql-js` so it get's the metadata from decorators and build the schema using `graphql-js` constructs. And the union type constructor has following config:
```ts
export interface GraphQLUnionTypeConfig<TSource, TContext> {
    name: string;
    types: Thunk<GraphQLObjectType[]>;
    resolveType?: Maybe<GraphQLTypeResolver<TSource, TContext>>;
    description?: Maybe<string>;
    astNode?: Maybe<UnionTypeDefinitionNode>;
    extensionASTNodes?: Maybe<ReadonlyArray<UnionTypeExtensionNode>>;
}
```
https://github.com/graphql/graphql-js/blob/d2e29e9bfceaec0b6f66d4336dafd6ade543840d/src/type/definition.js#L1115-L1127

So the runtime is responsible for parsing the query and finding the `id` field in types. I can't do nothing about that, extends or something.

> I was able to fix the issue by using @Query(() => Node) instead of @Query(() => NodeQueryResult).

That's also the idiomatic GraphQL solution - if your query returns an interface, you can query its field and also all the implementing object types using the fragment syntax. Why don't you like that? 😕

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes as there's no response after a week 🔒
