### ISSUE TITLE
Please make an update that includes React client side support

### ISSUE THREAD

**Issue by dharric** [19majkel94/type-graphql#281]
**Is your feature request related to a problem? Please describe.**
I am using typegraphql now inside of a node express app. I would like to reuse my graphql entities inside of my react app, which is also using typescript. I don't want to use apollo code generator.

**Comment by 19majkel94** [comment]
You have to use graphql code generator because your query my use only a subset of the fields and all scalars like date or enum are serialized to strings.

**Comment by 19majkel94** [comment]
For other purposes (like reusing `class-validator` validation constraints) you can use the classes by using this trick:
https://typegraphql.ml/docs/browser-usage.html
