### ISSUE TITLE
Support for TypeORM with MongoDB

### ISSUE THREAD

**Issue by elie222** [19majkel94/type-graphql#288]
TypeORM has experimental MongoDB support. I’m wondering well this pairing works with TypeGraphQL or whether TypeGoose works better with this package if I’m using Mongo?

Apologies if this question has already been asked. On mobile.

**Comment by 19majkel94** [comment]
Please ask your question on project chat - Github issues are not a helpdesk for questions:

https://gitter.im/type-graphql/Lobby
