### ISSUE TITLE
Bug: value.toISOString is not a function

### ISSUE THREAD

**Issue by 4F2E4A2E** [19majkel94/type-graphql#29]
I am getting following error when quering for an object with an iso date field:

```typescript
serialize(value: Date) {
  return value.toISOString();
},
```

```typescript
// date type gets lost on transpile and leads to this error
serialize(value) {
  return value.toISOString();
},
```

**Comment by 19majkel94** [comment]
Please provide minimal reproduction example of this bug. Looks like you are not returning `Date` instance.

**Comment by 4F2E4A2E** [comment]
Sorry it took so long, but here it is:
```typescript
// integration.test.date.ts
// "type-graphql": "0.4.0",
import 'reflect-metadata';
import {graphql} from 'graphql';
import * as bodyParser from 'body-parser';
import * as express from 'express';
import * as graphqlHTTP from 'express-graphql';
import {buildSchema, Field, GraphQLISODateScalar, GraphQLObjectType, GraphQLResolver, Query} from 'type-graphql';

@GraphQLObjectType()
abstract class A {
    @Field(returnType => GraphQLISODateScalar)
    a: Date;
}

@GraphQLResolver(() => TestResolver)
class TestResolver {

    @Query(returnType => A, {description: ''})
    test() {
        return {
            a: '2018-02-15'
        };
    }
}

const schema = buildSchema({resolvers: [TestResolver], dateScalarMode: 'isoDate'});

function runExpress() {
    const port = 4000;
    const app = express();
    app.use('/graphql', bodyParser.json(), graphqlHTTP({schema, graphiql: true}));
    app.listen(port, () => {
        console.log(`Graphical started, http://localhost:${port}/graphql`);
    });

    graphql(schema, `{ test{ a } }`)
        .then(f => console.log(JSON.stringify(f)));
}

runExpress();
```

**Error**:
```typescript
{"errors":[{"message":"value.toISOString is not a function","locations":[{"line":1,"column":9}],"path":["test","a"]}],"data":null}
```

**Comment by 19majkel94** [comment]
As I said, your code is invalid. Your not returning `Date` object but string.
When you do:
```ts
    @Query(returnType => A, {description: ''})
    test(): A {
        return {
            a: '2018-02-15'
        };
    }
```
You will get compile error that '2018-02-15' is not a `Date` object. You need to return `a: new Date('2018-02-15'),` 😉

**Comment by 4F2E4A2E** [comment]
> You will get compile error that '2018-02-15' is not a Date object. You need to return a: new Date('2018-02-15'),

That can't be correct, this is only a test, image this value being passed by a JSON.

**Comment by 19majkel94** [comment]
> image this value being passed by a JSON

So you need to parse your JSON, eg. using [class-transformer](https://github.com/typestack/class-transformer).
GraphQL will transform all scalars by itself, so the iso string passed as input value will become `Date` object on the server (resolver) side.

**Comment by 4F2E4A2E** [comment]
Class-transformer is a big overhead for something like this. I can't imagine doing this for each necessary field on every class needing it.

**Comment by 4F2E4A2E** [comment]
> As I said, your code is invalid. Your not returning Date object but string.

The code has nothing to do with this, as said, this could be a response json from some endpoint.
This rather mean, that the way GraphQLISODateScalar is implemented, it _only_ supports Date objects, which JSON does not  🙄

**Comment by 19majkel94** [comment]
And I can't imagine that you have type `Date` on your class definition but have `string` as the data in runtime - it's such enormous source of bugs (like "toISOString is not a function")!

Bulit-in Date scalars support is for transforming `Date` object (received from Mongo or TypeORM) to the string (JSON) sent to client. Other date scalars implementations do the same:
https://github.com/tjmehta/graphql-date/blob/master/index.js#L13

If you need support for transforming Date, number, string and booleans to Date scalar, you have to create your own implementation and do this:
```ts
@GraphQLObjectType()
abstract class A {
    @Field(type => MyCustomUniversalDateScalar)
    a: Date | number | string | whatever;
}
```

**Comment by 4F2E4A2E** [comment]
> And I can't imagine that you have type Date on your class definition but have string as the data in runtime - it's such enormous source of bugs (like "toISOString is not a function")!

Again, this was only to simulate data fetching from an endpoint.
