### ISSUE TITLE
Adding instructions for Typescript/Babel 7 setup

### ISSUE THREAD

**Issue by Asim13se** [19majkel94/type-graphql#300]
Currently this framework does not work with Babel 7 and `@babel/preset-typescript` setup, the reasons are:
1- Parameter decorators is not supported by `@babel/plugin-proposal-decorators`
2- Babel strips type information thus `Reflect.getMetadata()` returns undefined, more explanation [url](https://stackoverflow.com/a/54360611)

After spending few hours to come to this conclusion i solved these issues by installing this babel plugin `babel-plugin-transform-typescript-metadata` [url](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata)

I liked this framework and i almost gave up on it because of these issues,
It will be good to include this in the installation guide, to make it easy for developers with Babel 7 and `@babel/preset-typescript` setup which is a common setup.

Thanks

**Comment by 19majkel94** [comment]
With #296 TypeGraphQL will turn more toward TypeScript compiler, so you will miss a lot new goodness by sticking to babel.

And feel free to create a PR with a new doc page in `Others` section with info how to setup Typescript/Babel correctly, maybe even with an example in the repository.

**Comment by Asim13se** [comment]
Great work on #296  
Since i am not using babel heavily on backend projects it will be reasonable to switch to Typescript compiler.

Thanks

**Comment by vjpr** [comment]
Use this plugin: https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata#readme

Also see bug in https://github.com/19majkel94/type-graphql/issues/323
