### ISSUE TITLE
Change how the "name" option works in the "Field" decorator

### ISSUE THREAD

**Issue by lukejagodzinski** [19majkel94/type-graphql#308]
Let's assume that we have the following type definition:

```ts
@ObjectType()
class MyType {
  @Field(type => JSON, { name: "xxx" })
  global: any;
}
```

After using the `typeorm` library I would assume that in the generated schema, I would end up with the type having the `global` field but value coming from the `xxx` property.

So it would be equivalent of the following resolver:
```ts
@FieldResolver()
global(@Root() root) {
  return root.xxx;
}
```

I think it would be much more beneficial than the other way around as it's now.
What do you think?

**Comment by 19majkel94** [comment]
The `field` is responsible for exposed schema field name. So if you query for `{ xxx }`, it will read `global` property of `MyType` object.

In TypeORM it's the same - you have a `global` runtime property but `xxx` column name in database.
