### ISSUE TITLE
Right way to have Authentication and PubSub in GraphQLServer

### ISSUE THREAD

**Issue by viniciusvieir** [19majkel94/type-graphql#310]
I'm trying to use subscriptions on my GraphQL server. The problem I'm facing is that I can't have both a middleware to extract my JWT and a PubSub when initializing the GraphQLServer.

This is what I have:
```js
const server = new GraphQLServer({
    schema,
    context: ({request}) => extractJWT(request),
  });
```

And it works just fine with this:
```js
@Mutation(returns => User)
    public async findUser(
        @Ctx() context: IContext,
        @PubSub() pubsub: PubSubEngine,
    ) {
        const user = await User.findById(context.tokenData.userId)
        pubsub.publish('user', { user })
        return user
    }
```

But if I register the PubSub on the GraphQLServer initialization context and change my code to the one below, I can't any longer access what I have in my @Ctx decorators.
```js
const pubSub = new PubSub();
const server = new GraphQLServer({
    schema,
    context: {
       ctx: ({request}) => extractJWT(request),
       pubSub
  },
  });
```

What is the proper way to initialize my GraphQLServer using both JWT extraction middleware and the PubSub?

**Comment by 19majkel94** [comment]
Sorry but your question is not about TypeGraphQL but Apollo Server. 

You should look for an answer in the docs:
https://www.apollographql.com/docs/apollo-server/features/subscriptions#context-with-subscriptions
