### ISSUE TITLE
Error: Expected value of type ... when using code from example

### ISSUE THREAD

**Issue by georgyfarniev** [19majkel94/type-graphql#311]
**Describe the bug**

I tried to use code from example called **generic-types**, and I ran into error like that:

```
Expected value of type \"PromoCodeResponse\" but got: { data: [{ enabled: true }], total: 3 }.
```

**To Reproduce**
Here is code to reproduce it:

Pagination function wrapper from example:

```
import { ClassType, Field, ObjectType, Int, InterfaceType } from 'type-graphql'

// tslint:disable
export default function PaginatedResponse<TItem>(TItemClass: ClassType<TItem>) {
  // `isAbstract` decorator option is mandatory to prevent registering in schema
  @ObjectType({ isAbstract: true })
  abstract class PaginatedResponseClass {
    @Field(type => [TItemClass])
    public data: TItem[]

    @Field(type => Int)
    public total: number
  }
  return PaginatedResponseClass
}
```

Used types:
```
import { Field, ObjectType, InputType, Int } from 'type-graphql'
import PaginatedResponse from '../paginated_response'

@ObjectType()
export class PromoCode {
  @Field(type => Boolean) public enabled: boolean
}

@ObjectType()
export class PromoCodeResponse extends PaginatedResponse(PromoCode) {
  // you can add more fields here if you need
}
```

Resolver:

```
  @Query()
  public  promoCodes(): PromoCodeResponse {
    return {
      data: [{
        enabled: true,
      }],
      total: 3
    }
  }
```

This is how I query graphql:
```
query PromoCodes {
  promoCodes {
		data {
      enabled
    }
  }
}
```
**Expected behavior**
Expected to work as example

**Logs**
```
Expected value of type \"PromoCodeResponse\" but got: { data: [{ enabled: true }], total: 3 }.
```

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node: 11
 - Package version: 0.17.0
 - TypeScript version: 3.2.2

**Additional context**

**Comment by georgyfarniev** [comment]
I just found a solution in https://github.com/19majkel94/type-graphql/issues/73, but I think it worth to be mentioned in example.

**Comment by 19majkel94** [comment]
It's already described in `examples` folder readme:

> **Note**: Be aware that the examples on master branch are designed to work with latest codebase that might not be released yet.
So if you are looking for examples that are compatible with the version you use, just browse the files by the git tag, e.g. [`tree/v0.16.0` for `0.16.0` release](https://github.com/19majkel94/type-graphql/tree/v0.16.0/examples).

![image](https://user-images.githubusercontent.com/10618781/56129255-fd80b000-5f81-11e9-9566-28dc8e6c276d.png)
