### ISSUE TITLE
The Date issue when returning cached data from Redis

### ISSUE THREAD

**Issue by laukaichung** [19majkel94/type-graphql#313]
I have created a middleware to cache database data using Redis.

Middleware:

````
export function DataCache(key) {
    return UseMiddleware(async (payload: ResolverData<GqlContext>, next) => {
            const redis = DBUtil.redis();
            let result = await redis.getAsync(key);
            if (result) {
                return JSON.parse(result);
            }
            result = await next();
            if(result) {
                await redis.setAsync(key, JSON.stringify(result), 'EX', maxAge);
            }
            return result;
    });
}
````

An example data returned from redis with `JSON.parse()`:

````
{
  "list": [
    {
      "id": 114,
      "userId": 3,
      "status": "Approved",
      "created": "2019-01-18T22:57:57.734Z",
      "updated": "2019-01-18T22:57:57.734Z"
    }
  ]
}
````

In the entity, I do not add anything to the `@Field` decorator, but I set the `Date` type to the fields

````
@ObjectType()
@Entity()
export class User {
    @Field()
    @CreateDateColumn()
    public created: Date;

    @Field()
    @UpdateDateColumn()
    public updated: Date;
}
````
There is no problem when the request first hits the database, but the second time it hits the redis cache instead, I'm getting this error :

````
Cannot return null for non-nullable field User.created 
````

It looks like the server doesn't recognize the the date string from the cache data. I'm sure to use `JSON.parse(redisData)` before returning. The only way to solve this is to change the `Date` type to `string`:

````
@ObjectType()
@Entity()
export class User {
    @Field()
    @CreateDateColumn()
    public created: string; 

    @Field()
    @UpdateDateColumn()
    public updated: string; 
}
````
But I don't understand why just changing the type would fix this issue.

**Comment by 19majkel94** [comment]
Because the `DateTime` scalar expects `Date` instances, not a string. You should transform it properly after `JSON.parse` or use a custom scalar that tries to convert the iso string to date and then serialize it.

**Comment by laukaichung** [comment]
@19majkel94 

I just created a custom scalar as you suggest:

````
export const CustomDate = new GraphQLScalarType({
    name: "CustomDate",
    description: "Convert ISO string from redis data",
    parseValue(value: string) {
        return moment(value).toDate(); // value from the client input variables
    },
    serialize(value: Date) {
        return moment(value).toISOString(); // value sent to the client
    },
    parseLiteral(ast) {
        if (ast.kind === Kind.STRING) {
            return moment(ast.value).toDate(); // value from the client query
        }
        return null;
    },
});
````
It seems to be working fine.

But I'd probably just change the `Date` type to `string` for `created` and `updated` fields of the entity. I just hope it won't create any potential issues for type-orm or type-graphql in the future.

**Comment by 19majkel94** [comment]
@laukaichung 
You should use Apollo Engine and Apollo Cache control:
https://github.com/19majkel94/type-graphql/tree/master/examples/apollo-engine

And data loaders for reducing database queries overload.

**Comment by SebaBoler** [comment]
@MichalLytek could you replace link to active ?  I have this same issue
