### ISSUE TITLE
@Arg with array of inputs

### ISSUE THREAD

**Issue by JohnatanNorman** [19majkel94/type-graphql#314]
Hi there! I had a problem with @arg.

I wanted to use @Arg with array of input objects, but get error like this:
`You need to provide explicit type for GetOrderResolver#addOrder parameter #1 `

Is there a way to do something like this?
@Arg('items') items: ItemInput[] (I know syntax like this wouldn't work)

**Comment by 19majkel94** [comment]
`@Arg('items', type => [ItemInput]) items: ItemInput[]`

**Comment by JohnatanNorman** [comment]
> `@Arg('items', type => [ItemInput]) items: ItemInput[]`

Thanks, that was fast! Was it in documentation and I simply couldn't find it or it wasn't here?

**Comment by Numbers-sa** [comment]
Im trying to replicate the same thing but however i'm not winning

**Comment by innoveltec** [comment]
for me it is also not working. @Args('postCreateInputList', type => [PostCreateInput])
    postCreateInputList: [PostCreateInput] is giving me the following error:

Argument of type '(type: any) => (typeof PostCreateInput)[]' is not assignable to parameter of type 'PipeTransform<any, any> | Type<PipeTransform<any, any>>'.
      Type '(type: any) => (typeof PostCreateInput)[]' is not assignable to type 'Type<PipeTransform<any, any>>'.
        Type '(type: any) => (typeof PostCreateInput)[]' provides no match for the signature 'new (...args: any[]): PipeTransform<any, any>'.
  Overload 3 of 4, '(options: ArgsOptions, ...pipes: (PipeTransform<any, any> | Type<PipeTransform<any, any>>)[]): any', gave the following error.
    Argument of type '"postCreateInputList"' is not assignable to parameter of type 'ArgsOptions'.
@Args('postCreateInputList', type => [PostCreateInput])

Kind regards, Gerry

**Comment by MichalLytek** [comment]
@innoveltec Because you use NestJS and it has a different syntax - `{ name: "name", type: () => [Type]}`

**Comment by innoveltec** [comment]
ok it's working fine now. Great job!

**Comment by theRocket** [comment]
What is the difference between @Args() and @Arg()? I have seen many examples with the latter, but I am using NestJS and only the plural seems to work.

I'm looking for the syntax @innoveltec wound up with, considering @MichalLytek provided curly braces. My example is this:

`async createHouseholdwithAddy(@Args('data') houseAdd: HouseAddyCreate)`

Where HouseAddyCreate is an intersection type of two @InputType() classes, like:
`type HouseAddyCreate = HouseholdCreate & AddressCreate;`

**Comment by MichalLytek** [comment]
> What is the difference between `@Args()` and `@Arg()`?

`@Args()` doesn't allow to pass an arg name as a parameter and it only works with `@ArgsType` classes.
`@Arg()` is for single named arguments and accepts input types or scalars, not `@ArgsType`.

However, NestJS uses only `@Args()`, so `@Arg("name")` = `@Args("name")` in that case.

> type HouseAddyCreate = HouseholdCreate & AddressCreate;

Types doesn't exist on runtime - you need to create an `@InputType` class that described all the fields and types using decorators.

**Comment by theRocket** [comment]
Thanks for the added info, Michal! I did try your suggestion which was to create a new InputType and I added the second type as a field. This works! However, can you advise how I might remove duplicate fields, since it is not quite an intersection.
`@InputType()
export class HouseholdWAddy extends HouseholdCreate {
  @Field(type => AddressCreate)
  addy: AddressCreate

  //TO-DO:
  // need to drop addresses requirement for HouseholdCreate (since creating)
  // and user within AddressCreate class since redundant
  // it's possible addressline2 is showing up as required?
}`

**Comment by MichalLytek** [comment]
@theRocket See #453 😉

**Comment by theRocket** [comment]
Got it, thanks! I was just looking at Omit: https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk
