### ISSUE TITLE
Ability to apply @Authorized decorator Resolver-wide

### ISSUE THREAD

**Issue by georgyfarniev** [19majkel94/type-graphql#317]
**Is your feature request related to a problem? Please describe.**
It would be nice to have option of applying @Authorized decorator to whole resolver, in case if entire resolver have same permissions. It's not very convenient to repeat @Authorized decorator with same parameters for every query and mutation

**Describe the solution you'd like**
Ability to apply @Authorized decorator to resolver

**Describe alternatives you've considered**
Probably implementing separate decorator for resolvers

**Additional context**
N\D

**Comment by 19majkel94** [comment]
Closing as a duplicate od #200 🔒
