### ISSUE TITLE
Query or Mutation returning Promise<void>

### ISSUE THREAD

**Issue by georgyfarniev** [19majkel94/type-graphql#318]
Hello. First of all, thank you for creating this library, it really saves lots of time.

I have question: what return type should I use for @Mutation or @Query decorator, if method returns Promise<void> ? I tried undefined and null, both of them results in runtime errors during schema parsing. Below is example code with question explaination.

```
  @Mutation(returns => SomeType) // << what type should be returned here?
  public async someMutation(): Promise<void> {
    return this.service.performMutation(ctx, input) // << this method returns Promise<void>
  }
```

**Comment by 19majkel94** [comment]
It's a bad practice to don't return anything from a mutation as GraphQL doesn't operate on HTTP codes like 200, 201, 204 or 4xx.

So to communicate with your client properly, you should return some status of the mutation - it can be e.g. a Boolean, so `return true` when everything went ok and `return false` or throwing error (null in data json) when there was some problems with handling the mutation.

**Comment by georgyfarniev** [comment]
@19majkel94 thanks for quick response. I just though about don't return anything, and just throw exception in case of error. I'm newbie in graphql and just started to integrate in in our project, so I will use your advice and return boolean value on operations.  Thank you.

**Comment by Billy-** [comment]
Hi @MichalLytek, I actually agree with @georgyfarniev's comment above.. The fact that we can throw an error means that if we don't throw an error, everything went OK by implication.

This is a perfectly valid thing to do in GraphQL and if I wasn't using `type-graphql`, I would be able to do this with the provided `Void` type. Does `type-graphql` not support it?

IMHO it doesn't make sense to omit compatibility with part of the GraphQL spec because it could be seen as a bad practice (which I respectfully disagree with).

**Comment by MichalLytek** [comment]
```ts
import { VoidScalar } from "graphql-void-scalar";

@Resolver()
class SampleResolver {
  @Query(returns => VoidScalar)
  voidQuery(): void {
    doNothing();
  }
}
```

**Comment by Billy-** [comment]
I just came back to correct myself, the `Void` type isn't provided, I was misinformed there 😅 

Thanks for the example, that's awesome! 🙌 👍

**Comment by Billy-** [comment]
Ah, not an existing package though. Are you thinking that `VoidScalar` would just have a single, nullable field?

**Comment by Billy-** [comment]
Sorry I haven't used custom Scalars before and having just done some reading I realised what I said there doesn't really make sense. I'll do some more reading and try and get it working before I ask any more questions 😄
