### ISSUE TITLE
build error: #319 not compatible with graphql-js v14.2.0

### ISSUE THREAD

**Issue by maplesteve** [19majkel94/type-graphql#320]
**Describe the bug**
#319 makes use of the (private) library under graphql/jsutils by importing `MaybePromise`. 
This has been renamed in version 14.2.0 [(in #1798)](https://github.com/graphql/graphql-js/pull/1798) to `PromiseOrValue`. Building a project which uses graphql >= 14.2.0 now breaks.

**To Reproduce**
Install graphql-js@14.2.0 and build.

**Expected behavior**
...builds without failure

They [state](https://github.com/graphql/graphql-js/pull/1798#issuecomment-475584033), that one shouldn't rely on things under jsutils.

**Comment by 19majkel94** [comment]
That's why peer dependency was a bad idea 😞 

It's hard to prevent that kind of regression with loose range of supported versions. I would have to create a matrix in Travis to test against all newer versions 😕 

I will fix it ASAP and release 0.17.3 🔥

**Comment by 19majkel94** [comment]
Solved by 4677f1a 🔒

**Comment by codeninja0x01** [comment]
I have this build error but thanks to @19majkel94 its solved. just updated to 0.17.3
