### ISSUE TITLE
Middleware - pass extra parameter to resolver

### ISSUE THREAD

**Issue by georgyfarniev** [19majkel94/type-graphql#324]
Hello. I would like to create middleware that handles mongodb transaction with it's creation and also handle it's rejection appropriately with try-catch block, so it's not necessary to implement same logic within every resolver. But how to pass session handle to resolver from middleware?

In Koa, I can just add custom property to koa Context, e.g. ctx.mongodbSession, and then use it in controller. 

Any advice how to achieve something similar with type-graphql middleware? Thanks.

**Comment by 19majkel94** [comment]
In middlewares you have access to the `ResolverData` which has `context` prop - it's shared beteween all resolvers just like in koa, so you can put there your session and access it in  resolver using `@Ctx()` decorator.
https://typegraphql.ml/docs/authorization.html#recipes

**Comment by georgyfarniev** [comment]
@19majkel94 thanks. Solved.
