### ISSUE TITLE
Feature: allow returning custom async iterators from `subscribe` method

### ISSUE THREAD

**Issue by rfermann** [19majkel94/type-graphql#327]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Prisma subscriptions in conjunction with TypeGraphQL. For that purpose Prisma is providing functions to return async iterators from the `subscribe` method of GraphQL subscriptions. Unfortunately these async iterators cannot be passed through TypeGraphQL because TypeGraphQL currently always creates and returns its own async iterators.

**Describe the solution you'd like**
I would like to have a possibility to create/return custom async iterators within the `Subscription` decorator instead of having TypeGraphQL creating the async iterators.

A solution for that topic could be a new `subscribe` property for the `Subscription` decorator, which takes any async iterators. When set, `generateSubscriptionsFields ` directly returns the content of this property to `fields[handler.schemaName].subscribe` instead of creating its own async iterator.

**Describe alternatives you've considered**
Another solution would be to plug in Prismas PubSub system as described [in the docs](https://typegraphql.ml/docs/subscriptions.html#using-a-custom-pubsub-system). But this alternative has some downsides:
- Prismas PubSub system seems not to be accessible from anywhere except the from the Prisma Client
- I would need to create all the events on my own instead of having Prisma creating events for creating, updating and deleting datasets automatically

**Additional context**
I already have a first draft of this feature working locally. Based on this I can create a pull request for this feature, if you like.

**Comment by 19majkel94** [comment]
>  a new subscribe property for the Subscription decorator, which takes any async iterators

It can be a good temporary solution for your problem. But it suffers from lack of access to class properties, so no easy DI possible. 

I am thinking about a new API for subscriptions that is all class based - one `@SubscriptionResolver` class per subscription, field/method for topics or method for `subscribe`, as well as normal resolver method like now. But it may take a while to polish that design and implement it.

> I already have a first draft of this feature working locally. Based on this I can create a pull request for this feature, if you like.

It's not a big change so feel free to create a PR with proper tests added and docs updated about this new feature 😉

**Comment by 19majkel94** [comment]
Closed by #328 🔒
