### ISSUE TITLE
Can I transform field's value before returning?

### ISSUE THREAD

**Issue by lukejagodzinski** [19majkel94/type-graphql#334]
Let's say I have types:

```gql
enum Role {
  ADMIN
}

type User {
  role: Role!
}
```

so an example object of the `User` type would be:

```ts
const user = {
  role: "ADMIN"
};
```

the problem is that in DB the role field is stored in lower case format:

```ts
const user = {
  role: "admin"
};
```

The question is, can I transform value before returning it? I would like to do it on the user type level and not in the resolver. I would use getter but I can't here:

```ts
@ObjectType()
class User {
  @Field(type => Role)
  get role(): Role {
    return this.role; // Can't return field with the same name as getter
  }
}
```

I know I could do it on the resolver level but in such case I would have to do it in every query I have and I would want something more elegant. I also don't want to change field name. I've also tried transforming it in the constructor but that didn't work either.

Any ideas?

**Comment by lukejagodzinski** [comment]
Hmm actually found out that in TypeORM there is the transformer column option that can do that for me. For anyone having this problem I will post here an example code:

```ts
@ObjectType()
class User {
  @Field(type => Role)
  @Column({
    /* ... */
    transformer: {
      to: role => role,
      from: role => role.toUpperCase()
    }
  })
  role: Role;
}
```

**Comment by 19majkel94** [comment]
It's easier to have mapping in enum itself:
```ts
enum Role {
  GRAPHQL_NAME = "yourValueInRuntimeOrDatabase"
}
```

**Comment by brunolm** [comment]
```ts
import { Field, InputType, MiddlewareFn, ObjectType, UseMiddleware } from 'type-graphql'

export function SomeInterceptor(): MiddlewareFn {
  return async (_, next) => {
    const result = await next()

    console.log('result', result)

    return result + ' aaaaaaaaa'
  }
}

@ObjectType()
class Something {
  @Field()
  @UseMiddleware(SomeInterceptor())
  someField: string
}
```
