### ISSUE TITLE
Schema generating error with Enums

### ISSUE THREAD

**Issue by valerio-battaglia** [19majkel94/type-graphql#336]
**Describe the bug**
When using an Enum type, even with manual registration, it is not possible to compile the code.

**To Reproduce**
```
import { Field, ObjectType, registerEnumType } from 'type-graphql'

// Ruler Enum
export enum Ruler {
  'JON' = 'JON',
  'DAENERYS' = 'DAENERYS'
}
// Register the Enum to GraphQL
registerEnumType(Ruler, {
  name: 'Ruler',
  description: 'The Ruler of the seven Kingdom.'
})
// Object type that uses the Ruler enum
@ObjectType()
export class KingsLanding {
  //@Field(type => null)
  //public currentRuler: null

  @Field(type => Ruler)
  public nextRuler: Ruler
}
```

**Expected behavior**
It should work as in the [example](https://typegraphql.ml/docs/enums.html).

**Logs**
`UnhandledPromiseRejectionWarning: Error: Generating schema error.`

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node 10.15.3
 - Package version 0.17.4
 - TypeScript version 3.4.5

**Comment by 19majkel94** [comment]
Try to catch the error and log the `details` property of it.

https://github.com/19majkel94/type-graphql/blob/fdb7e57b8e08fddb0535dd601f1c5505b3a95fb3/src/errors/GeneratingSchemaError.ts#L3-L5

```ts
@Field(type => null)
public currentRuler: null
```

There is no `null` scalar in GraphQL. It has to be at least a nullable boolean or other scalar, if you always want to return null.

**Comment by valerio-battaglia** [comment]
Sorry, it was actually commented the `null` field.
Found the culprit, the actual code contained a hypen which is not accepted by GraphQL.
Error message: `Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "JON-SNOW" does not.`
