### ISSUE TITLE
Can we use TypeGraphQL along with Express graphql ?

### ISSUE THREAD

**Issue by rvtarig7** [19majkel94/type-graphql#341]
Hi,
We already have a matured express graphql project and are wondering if we can use Typegraphql along with Express graphql. Instead of completely refactoring all the queries and mutations that were written using express graphql we would like to know if we can use TypeGraphQL for writing new queries and mutations keeping the already existing queries untouched. Is this setup possible ? Does TypegraphQL support this ?

Thanks,

**Comment by 19majkel94** [comment]
@rvtarig7 

You have an example of usage with `express-graphql` in examples:
https://github.com/19majkel94/type-graphql/blob/fdb7e57b8e08fddb0535dd601f1c5505b3a95fb3/examples/query-complexity/index.ts#L19-L22

> completely refactoring all the queries and mutations

So it looks like you use the apollo tools to build the typeDefs using SDL and then the standard resolver functions. In that case, you can use `mergeSchemas` function:
https://www.apollographql.com/docs/graphql-tools/schema-stitching

**Comment by DerZade** [comment]
I just stumbled upon this. 

Is there a way to access the context object from `express-graphql` (or the express request in any other way) within the resolver, just like it is possible when passing the resolvers in the `rootValue` to `express-graphql`.

The thing I want to achieve is to read the user authentication from a cookie and I therefore would need access to the request object.

**Comment by DerZade** [comment]
Never mind. Just stumbled across the solution while learning about [Input types](https://typegraphql.ml/docs/resolvers.html#input-types). 

> We may also need access to the context. To achieve this we use the @Ctx() decorator with the optional user-defined Context interface

I can't seem to find this anywhere else in the documentation. Which is not optimal 😉 

But other than that, outstanding work! so Thanks a lot! ❤️

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
