### ISSUE TITLE
Document site is down

### ISSUE THREAD

**Issue by chengjia0807** [19majkel94/type-graphql#343]
Document site cannot be opened

**Comment by 19majkel94** [comment]
@chengjia0807 
Cannot reproduce, for me it works ok. Can you post here a link that isn't working?
https://typegraphql.ml/

**Comment by chengjia0807** [comment]
> @chengjia0807
> Cannot reproduce, for me it works ok. Can you post here a link that isn't working?
> https://typegraphql.ml/

Thanks mate. It's working now :)
