### ISSUE TITLE
InputType field name

### ISSUE THREAD

**Issue by Nikamura** [19majkel94/type-graphql#346]
**Describe the bug**

Name provided for input field will create a new variable instead of assigning to the correct one.

**To Reproduce**

```
@InputType()
export class C {
  @Field(_type => ObjectIdScalar, { name: "buildId" })
  public buildObjectId!: ObjectId;
}
```	

```
@Arg("input") input: C
```

`input.buildObjectId` will be undefined, while `input.buildId` will have input value.

**Expected behavior**

`input.buildObjectId` to have input value.

**Comment by 19majkel94** [comment]
Duplicate of #263 🔒
