### ISSUE TITLE
Is it possible to generate dynamic arguments?

### ISSUE THREAD

**Issue by jesster2k10** [19majkel94/type-graphql#347]
I was wondering if it was possible to use some sort of function to generate a set of dynamic arguments on an abstract class decorated with "@ArgsType"

Take the code below for example:

```js
export function WhereArguments(type: string) {
  const properties = getConnection()
    .getMetadata(type)
    .ownColumns.map(column => ({
      type: column.type,
      name: column.propertyName
    }))
  const strings = properties.filter(
    property => property.type === String || property.type === 'text'
  )
  const booleans = properties.filter(
    property =>
      property.type === Boolean ||
      property.type === 'bool' ||
      property.type === 'boolean'
  )

  const baseFilters = properties
    .filter(
      property => !strings.includes(property) && !booleans.includes(property)
    )
    .map(({ name }) => [
      `${name}`,
      `${name}_gt`,
      `${name}_lt`,
      `${name}_gte`,
      `${name}_lte`,
      `${name}_not`
    ])

  const stringFilters = strings.map(({ name }) => [
    name,
    `${name}_gt`,
    `${name}_lt`,
    `${name}_gte`,
    `${name}_lte`,
    `${name}_not`,
    `${name}_contains`,
    `${name}_not_contains`,
    `${name}_starts_with`,
    `${name}_not_starts_with`,
    `${name}_ends_with`,
    `${name}_not_ends_with`
  ])
  const booleanFilters = booleans.map(({ name }) => name)
  const filters = [].concat.apply(
    [],
    [...stringFilters, ...booleanFilters, ...baseFilters]
  )

  @ArgsType
  class Abstract {
     // is it possible to define properties on this class, based on the filters array?
  }
  return Abstract
}
```

My question, is it possible to apply properties to this class based on the 'filters' array so the end result would be like:

```js
@ArgsType
class AbstractArgumentClass {
   @Field()
   public name_gte: string

  ...the other fields in the array
}
```

I'm not sure if this is possible, but it would save me a lot of time than having to define each of those for each of my entities/object types

**Comment by 19majkel94** [comment]
Technically it's possible (call the decorator function manually, like in transpilled JS code) but you will loose type safety in your code as TypeScript is not capable of handling dynamic property values.

Maybe in your case, you should just use a more static-type friendly way for declaring arguments? There was a discussion about it: https://github.com/19majkel94/type-graphql/issues/134#issuecomment-449516357

**Comment by jesster2k10** [comment]
Wow, the method suggested there is great. Hadn't thought of that. Much better than what I was trying to implmement

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
