### ISSUE TITLE
Using resolver functions sync

### ISSUE THREAD

**Issue by phal0r** [19majkel94/type-graphql#348]
Hi,

thanks for this nice project. It is really fun to work with it. I want to use it in a uncommon context. The database ArangoDB has a built-in business layer based on v8 javascript engine. They support most of modern javascript features with one exception: asynchronity. 

Nevertheless I tried to integrate type-graphql into ArangoDB. So far the schema can be build and graphiql also works as expected outlining my test query in the ui. When I try to make queries, the response is always empty. Is there some glue code which transforms all resolver functions to async functions?

I have a really small example with the following resolver code:

```
@Resolver()
export class UserResolver {

  @Query(returns => User)
  getUser(): User {
    const usr = plainToClass(User, {
      firstName: "ma",
      lastName: "mu"
    });
    console.log("returning user", usr)
    return usr;
  }
}
```

If you say resolving sync is not possible, I don't need to spend more time figuring out how to force it into the database :)

**Comment by 19majkel94** [comment]
> If you say resolving sync is not possible

I think it's not possible, by design all middlewares or validation is asynchronous so every generated resolver is asynchronous and waiting for them (even if you're not using them).

**Comment by phal0r** [comment]
@19majkel94 
Ok. Thanks for the insights. If everything is made to be asynchroneous, it makes no sense to investigate this further. Will close this ticket.

**Comment by 19majkel94** [comment]
@phal0r Your use case is very rare so I'm not sure if it's worth to support full sync mode in asynchronous (Promise, callbacks) Node.js world 😕

**Comment by phal0r** [comment]
yes, I fully understand. I just set it up in the database and could resolve all errors, that occured and I was curious if it makes sense to follow this route. 

For building backends I would always recommend not using sync mode, so it makes no sense to spend time on a sync mode. It is just a design choice for this specific runtime and I wanted to push this as far is can :)
