### ISSUE TITLE
Incorrect ObjectType name syntax in the Generic Types section

### ISSUE THREAD

**Issue by st3h3n** [19majkel94/type-graphql#353]
**Describe the issue**
In `/docs/generic-types.html` down at the bottom ``@ObjectType({ name: `Paginated${TItemClass.name}Response` })`` was used when ``@ObjectType(`Paginated${TItemClass.name}Response`)`` would have been correct.

**Are you able to make a PR that fix this?**
Sure.

**Comment by 19majkel94** [comment]
Looks like I should unify the options signature because even I as an author sometimes am mistaken 😞
