### ISSUE TITLE
Typo in DepreciationOptions

### ISSUE THREAD

**Issue by robations** [19majkel94/type-graphql#355]
**Describe the bug**
https://github.com/19majkel94/type-graphql/blob/523063e952e2192a18869d705f54138cb2c5304a/src/decorators/types.ts#L41

`DepreciationOptions` probably should be `DeprecationOptions`.

**Comment by 19majkel94** [comment]
@robations

> **Are you able to make a PR that fix this?**
If you can, it would be great if you create a pull request that fixes the docs, fills the gap with new chapter or new code example.

**Comment by 19majkel94** [comment]
Closing via 38035bd 🔒

**Comment by robations** [comment]
@19majkel94 sorry, was working to a deadline the past couple of weeks, probably could have made an adjustment earlier this week, but had forgotten by then 😐
