### ISSUE TITLE
[typegoose & type-graphql] Error: Cannot set property `prop` of #<`ObjectType`> which has only a getter

### ISSUE THREAD

**Issue by Drageaux** [19majkel94/type-graphql#360]
I'm implementing the Typegraphql integration with Typegoose, but the unsupported Mongoose virtual props have been giving me some troubles.

When I query for the Board entity below, it gives me the error `Cannot set property whiteKingLocation of #<Board> which has only a getter`

The context: the Board is a populated reference by another class called Session. Since this entity and its children have virtuals, I added the schemaOptions when exporting the BoardModel. This virtual prop implementation wasn't explained so clearly in the typegoose README so I'm not sure what exactly is the right way to do Mongoose virtuals; compounded with type-graphql now that's some extra complexity.

```js
import { prop, Typegoose, InstanceType, arrayProp, post } from 'typegoose';
import { ObjectType, Field, InterfaceType, ID } from 'type-graphql';
import { ObjectId } from 'mongodb';
import { Square } from './square';
import { Piece } from './piece';
import { File, Color, PieceType } from './enums';

@ObjectType()
@post<Board>('save', function(board) {
  console.log(board);
})
export class Board extends Typegoose {
  @Field(type => ID)
  readonly _id: ObjectId;

  @Field(type => [Square])
  @arrayProp({ items: Square, default: DEFAULT_BOARD })
  squares: Square[];

  @Field(type => [Piece], { nullable: true })
  @arrayProp({ items: Piece })
  capturedPieces?: Piece[];

  @Field(type => Square, { nullable: true })
  @prop()
  get whiteKingLocation(): Square {
    return this.squares.find((square: Square) => {
      return (
        square.piece &&
        square.piece.type === PieceType.King &&
        square.piece.color === Color.White
      );
    });
  }

  @Field(type => Square, { nullable: true })
  @prop()
  get blackKingLocation(): Square {
    return this.squares.find((square: Square) => {
      return (
        square.piece &&
        square.piece.type === PieceType.King &&
        square.piece.color === Color.Black
      );
    });
  }
}

export const BoardModel = new Board().getModelForClass(Board, {
  schemaOptions: {
    toObject: { getters: true, virtuals: true },
    toJSON: { getters: true, virtuals: true }
  }
});
```

EDIT: how I expose the query and how I queried using the doc
```js
  @Query(returns => Session, { nullable: true })
  async playGame(
    @Arg('gameId', type => ObjectIdScalar) gameId: ObjectId
  ): Promise<Session> {
    return await SessionModel.findById(gameId)
      .populate('board')
      .exec();
  }
```

```graphql
fragment basicSessionFields on Session {
  _id
  createdAt
  lastUpdated
}

fragment boardFields on Board {
  _id
  squares {
    ...squareXYFields
    name
    piece {
      ...pieceFields
    }
  }
  whiteKingLocation {
    ...squareXYFields
    name
  }
  blackKingLocation {
    ...squareXYFields
    name
  }
}

query GetBoard($gameId: ObjectId!) {
  playGame(gameId: $gameId) {
    ...basicSessionFields
    board {
      ...boardFields
    }
  }
}
```

**Comment by Drageaux** [comment]
I also tried to separate the getter and the field like this but still got the same error for the getter

```js
  @Field(type => Square, { nullable: true })
  whiteKingLocation(): Square {
    return this._whiteKingLocation;
  }

  @prop()
  get _whiteKingLocation(): Square {
    return this.squares.find((square: Square) => {
      return (
        square.piece &&
        square.piece.type === PieceType.King &&
        square.piece.color === Color.White
      );
    });
  }
```
Why? The getter isn't decorated with `@Field()`

**Comment by 19majkel94** [comment]
I'm not sure if it's TypeGraphQL fault - maybe virtual getters doesn't play well in Typegoose (which is a buggy lib btw).

Please try to create a minimal reproducible code example (one class with one getter or one field only), not a dump of half of your production codebase 😉

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒

**Comment by madmaxlax** [comment]
@MichalLytek I've been having this issue too today and it's been quite confusing. 
I am basically not able to use field resolvers

however, I am seeing this happen on ObjectTypes that are also designated as InputType s with a different string name.
could that be the issue?? input types can't have field resolves, and they can't be aliases of objecttypes that have field resolvers?

**Comment by MichalLytek** [comment]
There is no `@UniversalType` because of a huge differences between input types and output types. It's is recommended to have separate classes for that, so if you have any issue due to reusing, it's time to pay the tech debt and split the definitions.

**Comment by madmaxlax** [comment]
> There is no `@UniversalType` because of a huge differences between input types and output types. It's is recommended to have separate classes for that, so if you have any issue due to reusing, it's time to pay the tech debt and split the definitions.

Haha alrighty will do. I'll try to at least make a base class of everything that's mutual and have them both extend that with only their unique pieces

**Comment by MichalLytek** [comment]
@madmaxlax Please raise that in #12

**Comment by jgburet** [comment]
Having the same issue with

```typescript
import * as GQL from 'type-graphql';

import { Product } from './product.entity';

@GQL.ObjectType()
export class Application {
    _productName!: string;

    @GQL.Field()
    get productName(): string {
        return this._productName;
    }
}
```

```
{
  "errors": [
    {
      "message": "Cannot set property productName of #<Application> which has only a getter",
      "locations": [
        {
          "line": 17,
          "column": 7
        }
      ],
      "path": [
        "someResolverFunctionOfParentObject",
        0,
        "application",
        "supplierName"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot set property productName of #<Application> which has only a getter",
            "    at Function.assign (<anonymous>)",
            "    at Object.convertToType (~/node_modules/type-graphql/dist/helpers/types.js:78:19)",
            "    at ~/node_modules/type-graphql/dist/resolvers/create.js:50:40",
            "    at field.resolve (~/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at field.resolve (~/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
            "    at resolveField (~/node_modules/graphql/execution/execute.js:466:18)",
            "    at executeFields (~/node_modules/graphql/execution/execute.js:294:18)",
            "    at collectAndExecuteSubfields (~/node_modules/graphql/execution/execute.js:749:10)",
            "    at completeObjectValue (~/node_modules/graphql/execution/execute.js:739:10)",
            "    at completeValue (~/node_modules/graphql/execution/execute.js:592:12)",
            "    at completeValue (~/node_modules/graphql/execution/execute.js:558:21)",
            "    at resolveField (~/node_modules/graphql/execution/execute.js:474:19)",
            "    at executeFields (~/node_modules/graphql/execution/execute.js:294:18)",
            "    at collectAndExecuteSubfields (~/node_modules/graphql/execution/execute.js:749:10)",
            "    at completeObjectValue (~/node_modules/graphql/execution/execute.js:739:10)",
            "    at completeValue (~/node_modules/graphql/execution/execute.js:592:12)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

found https://github.com/apollographql/apollo-client/issues/4843 where people have the same error message but I don't have apollo-client / apollo-boost in my yarn.lock 🤔

**Comment by hi-usui** [comment]
> Having the same issue with
> 
> ```ts
> import * as GQL from 'type-graphql';
> 
> @GQL.ObjectType()
> export class Application {
>     _productName!: string;
> 
>     @GQL.Field()
>     get productName(): string {
>         return this._productName;
>     }
> }
> ```
> 
> ```
> {
>   "errors": [
>     {
>       "message": "Cannot set property productName of #<Application> which has only a getter",
>       "locations": [
>         {
>           "line": 17,
>           "column": 7
>         }
>       ],
>       "path": [
>         "someResolverFunctionOfParentObject",
>         0,
>         "application",
>         "supplierName"
>       ],
>       "extensions": {
>         "code": "INTERNAL_SERVER_ERROR",
>         "exception": {
>           "stacktrace": [
>             "TypeError: Cannot set property productName of #<Application> which has only a getter",
>             "    at Function.assign (<anonymous>)",
>             "    at Object.convertToType (~/node_modules/type-graphql/dist/helpers/types.js:78:19)",
>             "    at ~/node_modules/type-graphql/dist/resolvers/create.js:50:40",
>             "    at field.resolve (~/node_modules/graphql-extensions/src/index.ts:274:18)",
>             "    at field.resolve (~/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
>             "    at resolveField (~/node_modules/graphql/execution/execute.js:466:18)",
>             "    at executeFields (~/node_modules/graphql/execution/execute.js:294:18)",
>             "    at collectAndExecuteSubfields (~/node_modules/graphql/execution/execute.js:749:10)",
>             "    at completeObjectValue (~/node_modules/graphql/execution/execute.js:739:10)",
>             "    at completeValue (~/node_modules/graphql/execution/execute.js:592:12)",
>             "    at completeValue (~/node_modules/graphql/execution/execute.js:558:21)",
>             "    at resolveField (~/node_modules/graphql/execution/execute.js:474:19)",
>             "    at executeFields (~/node_modules/graphql/execution/execute.js:294:18)",
>             "    at collectAndExecuteSubfields (~/node_modules/graphql/execution/execute.js:749:10)",
>             "    at completeObjectValue (~/node_modules/graphql/execution/execute.js:739:10)",
>             "    at completeValue (~/node_modules/graphql/execution/execute.js:592:12)"
>           ]
>         }
>       }
>     }
>   ],
>   "data": null
> }
> ```
> 
> found [apollographql/apollo-client#4843](https://github.com/apollographql/apollo-client/issues/4843) where people have the same error message but I don't have apollo-client / apollo-boost in my yarn.lock 🤔
> 
> type-graphql@^1.1.1: version "1.1.1"
> 
> apollo-server-core@^2.19.2: version "2.19.2"
> 
> "@apollographql/apollo-tools@^0.4.3": version "0.4.8"

Did you ever figure this one out?

I have the same issue
```ts
  @GQL.Field(() => String)
  public get name_given(): String {
    if (this.name) {
      return this.name.split(" ")[0];
    }
  }
```
```
Cannot set property name_given of #<UserSchema> which has only a getter
```
