### ISSUE TITLE
Exclude .map files by default

### ISSUE THREAD

**Issue by JipSterk** [19majkel94/type-graphql#361]
when i build my schema like the following in production with source-maps on in my `tsconfig.json` it will also include `.map` extensions i think they should always be omitted:
```ts
await buildSchema({
      resolvers: [__dirname + "/modules/**/resolver.*"]
}
```

**Describe the solution you'd like**
exclude .map files by default.

**Alternative**
write the following
```ts
schema: await buildSchema({
  resolvers: [
    process.env.NODE_ENV === "production"
    ? __dirname + "/modules/**/resolver.js"
    : __dirname + "/modules/**/resolver.ts",
  ],
}
```

**Comment by 19majkel94** [comment]
`resolvers: [__dirname + "/modules/**/resolver.{ts, js}"]`
