### ISSUE TITLE
Uncaught TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by patrik-meixner** [19majkel94/type-graphql#365]
Hey,

I`ve been dealing with this problem for quite some time now. Today I decided to ask you here to what it means or if there is any solution to this problem. I already tried to follow the example but nothing seems to be working for me. 

This is the client.ts file: 

```ts
import "reflect-metadata";
import ApolloClient, { Resolvers, InMemoryCache } from "apollo-boost";
import { buildTypeDefsAndResolvers } from "type-graphql";
import TestResolver from "./TestResolver";

const cache = new InMemoryCache();

export default async function createApolloClient() {
  const { typeDefs, resolvers } = await buildTypeDefsAndResolvers({
    resolvers: [TestResolver],
    skipCheck: true
  });

  const client: ApolloClient<unknown> = new ApolloClient({
    cache,
    typeDefs,
    resolvers: resolvers as Resolvers
  });

  return client;
}
```

and this is the TestResolver file: 

```ts
import { gql } from "apollo-boost";
import { ApolloCache } from "apollo-cache";
import { Resolver, Mutation, Ctx } from "type-graphql";

import ApolloContext from "./apollo/context";
import CounterType from "./counter.type";

@Resolver(of => CounterType)
export default class TestResolver {
  @Mutation(returns => Boolean, { nullable: true })
  incrementCounter(@Ctx() { cache }: ApolloContext) {
    TestResolver.updateCounter(cache, value => value + 1);
  }

  @Mutation(returns => Boolean, { nullable: true })
  decrementCounter(@Ctx() { cache }: ApolloContext) {
    TestResolver.updateCounter(cache, value => Math.max(value - 1, 0));
  }

  private static updateCounter(
    cache: ApolloCache<any>,
    getNewValueCb: (value: number) => number
  ) {
    const query = gql`
      query {
        counter @client {
          __typename
          value
        }
      }
    `;
    const { counter } = cache.readQuery<{ counter: CounterType }>({ query })!;
    const data = {
      counter: {
        ...counter,
        value: getNewValueCb(counter.value)
      }
    };
    cache.writeQuery({ query, data });
  }
}
```

Any help is MUCH appreciated.

**Comment by 19majkel94** [comment]
Can you paste here the whole error with a stacktrace?

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒

**Comment by cstffx** [comment]
I have the same error. I'm using this (template)[https://github.com/a-tarasyuk/webpack-typescript-babel] with the steps in the (Getting started)[https://typegraphql.ml/docs/getting-started.html] section

**Comment by MichalLytek** [comment]
@cstffx 
Can you create a repository with a minimal reproducible code example?
`TypeError: The "original" argument must be of type Function` tells me nothing about the problem that might be related to tsconfig, setup, bundler or everything 😉

**Comment by cstffx** [comment]
Yep, here is the complete [example](https://github.com/cstffx/typegraphql-test).

**Comment by MichalLytek** [comment]
@cstffx You can't use the babel without providing proper plugins - see #55.

**Comment by cstffx** [comment]
> Also, you are trying to bundle node_modules which you can't for Node.js project - TypeGraphQL is not a frontend framework.
Tell me more about it. I'm excluding node_modules in my tsconfig.json and and in the babel-loader in webpack.config.js.

**Comment by MichalLytek** [comment]
I mean node native modules like `crypto`, `path`, and others 😉 

TypeGraphQL doesn't officially support JS nor babel, so I can't help you with configuring webpack. Please ask the community on gitter chat:
https://gitter.im/type-graphql/Lobby

**Comment by cstffx** [comment]
Thanks for your time. As beginner I discovered that at the end it has not much sense to use babel in the backend. But it is possible and if some one need to do it I left this [example](https://github.com/cstffx/typegraphql-babel-ts)

**Comment by SaiRS** [comment]
I met the same problem when I  tried to use type-graphql with web client.
Here is my solution.

> Since TypeGraphQL is a Node.js framework, it doesn't work in a browser environment, so we may quickly get an error, e.g. ERROR in ./node_modules/fs.realpath/index.js, while trying to build our app with Webpack. To correct this, we have to configure Webpack to use the decorator shim instead of the normal module. We simply add this plugin code to our webpack config:

```
  plugins: [
    // ... here are any other existing plugins that we already have
    new webpack.NormalModuleReplacementPlugin(/type-graphql$/, resource => {
      resource.request = resource.request.replace(/type-graphql/, "type-graphql/dist/browser-shim.js");
    }),
  ];
```

and here is the [doc link](https://github.com/MichalLytek/type-graphql/blob/master/docs/browser-usage.md)
