### ISSUE TITLE
Cannot determine GraphQL input type for 

### ISSUE THREAD

**Issue by VirtuousDeath** [19majkel94/type-graphql#371]
throw new Error(Cannot determine GraphQL input type for ${typeOwnerName}`);
^

Error: Cannot determine GraphQL input type for company`
having this error
my resolver
```
@Resolver()
export class CategoriesResolver {
  @Query(() => CategoriesData)
  async get_category_by_id(@Arg('company', type => CompanyData) company: CompanyData, @Arg('id') id: String): Promise<any> {
    let cat = new GetCategoryByIdLib()
    return cat.getCategoryById(company, id)
  }
}
```
My Data Fields
```
@ObjectType('CompanyData')
export class CompanyData {

    @Field(type => ID)
    _id : String

    @Field(type => String, {nullable: true})
    name: String;

    @Field(type => String, {nullable: true})
    email: String;

    @Field(type => String, {nullable: true})
    api_key: String;

    @Field(type => DocumentsData, {nullable: true})
    document: DocumentsData;

    @Field(type => [String], {nullable: true})
    phones: String[];

    @Field(type => AddressData, {nullable: true})
    address: AddressData;

    @Field(type => ImagesData, {nullable: true})
    avatar: ImagesData;

    @Field(type => [CustomerData], {nullable: true})
    customers: CustomerData[];

}
```

**Comment by 19majkel94** [comment]
Please paste more code, or maybe even better - create a repository with a minimal reproducible code example.

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes as there's no response from the issue author 🔒

**Comment by iamlothian** [comment]
_For future readers_

This may have been due to using an `@ObjectType() CompanyData `  as an `@InputType()` in the resolver.

See docs for: [inputType](https://github.com/MichalLytek/type-graphql/blob/master/docs/resolvers.md#input-types)

**Comment by merko30** [comment]
Could you help me with this: 
```

@InputType()
class OrderInputType implements Partial<Order> {
  @Field(type => [Item])
  items: Item[];

  @Field(() => Int)
  totalPrice: number;
}
```

I get `Error: Cannot determine GraphQL input type for items`

**Comment by MichalLytek** [comment]
@merko30 
`@Item` also has to be an `@InputType`

**Comment by merko30** [comment]
How can I declare ObjectType as InputType at the same time ? 

For example, I have an order model, it has many products. OrderInput needs to have many products, but it has to be InputType, I tried  `ProductType implements Product`, but it doesn't work.

**Comment by MichalLytek** [comment]
@merko30
Please read the docs before asking questions 😉 
https://typegraphql.ml/docs/faq.html#situations-frequently-arise-where-inputtype-and-objecttype-have-exactly-the-same-shape-how-can-i-share-the-definitions

**Comment by aurinxki** [comment]
This error is also triggered when providing objectType as argument for a resolver function. 

@Arg("argument") argumentInput: Argument

instead of 

@Arg("argument") argumentInput: ArgumentInput

where Argument is @ObjectType and ArgumentInput is @InputType

**Comment by TBG-FR** [comment]
@MichalLytek your link is dead, it send on a "scam" website... Do you have another link for the docs ?

**Comment by TBG-FR** [comment]
@MichalLytek you should edit your link, looks like typegraphql.ml sends on a "scam" website

**Comment by DespertaWeb** [comment]
> @MichalLytek you should edit your link, looks like typegraphql.ml sends on a "scam" website

Yep! It's sends to "scam" website

**Comment by glitchgirl** [comment]
I am having the same issue as @aurinxki. Is there a way around this? My InputType and ObjectType versions of my model are slightly different, the input doesn't have an id, but the object does. I need to use the id in my resolver, is there a way to use ObjectType as an argument?

**Comment by aurinxki** [comment]
> I am having the same issue as @aurinxki. Is there a way around this? My InputType and ObjectType versions of my model are slightly different, the input doesn't have an id, but the object does. I need to use the id in my resolver, is there a way to use ObjectType as an argument?

@glitchgirl, you could partially extend your InputType from your ObjectType and then specify that the ID is not required by the InputType (nullable), this will require you to add nullable (?) to your id property, but if you're using an ORM (I'm using TypeORM), this can be handled with a primary key/autoincrement id.

```
@ObjectType()
export class Record {
  @Field(type => Int)
  @PrimaryGeneratedColumn() // typeORM
  recordId?: number;

...
}
```

```
@InputType()
export class RecordInput implements Partial<Record> { 
  @Field(type => Int, {nullable: true})
  recordId?: number | undefined

..
}
```

**Comment by glitchgirl** [comment]
@aurinxki that's exactly what I ended up doing. Thanks for your response! I do understand that object types can hold "weird" data and that's probably why it can't be used in this way, but I do wish it worked that way or was better documented that it can't be used that way.

**Comment by habhabsafi** [comment]
use ``` GraphQLJSONObject

  @Field(() => [GraphQLJSONObject], { nullable: true })
  employees: UserObject[];
```

**Comment by jeronimoek** [comment]
For the record, this error also shows when you try using an enum without registering it:

registerEnumType(MyEnum, {
  name: 'MyEnum',
  description: 'MyEnum description',
});

**Comment by daniloras** [comment]
> use GraphQLJSONObject if you want to pass an object as an input type property
> 
> ```
>  @Field(() => GraphQLJSONObject, { nullable: true })
>  employee: UserObject;
> ```

GOOD, Work for me!
