### ISSUE TITLE
Support for TypeORM Embedded Entities

### ISSUE THREAD

**Issue by Dakki97** [19majkel94/type-graphql#374]
Currently Embedded Entities in TypeORM cannot be handled
```
export class TimeRange {
  @Column('timestamptz')
  public start!: Date

  @Column('timestamptz')
  public end!: Date
}
```
which are then used like this
```
  @Column(type => TimeRange)
  public timeRange!: TimeRange
```
This would be useful for TypeORM users, since embededded entities are a great way to reduce duplication inside code

**Comment by 19majkel94** [comment]
Why you won't place `@ObjectType()` and `@Field()` decorators on your entities?

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
