### ISSUE TITLE
Jest coverage not working for FieldResolver decorator

### ISSUE THREAD

**Issue by tristanMatthias** [19majkel94/type-graphql#377]
**Describe the bug**
Coverage for the `@FieldResolver(() => SomeEntity)` is not working using `jest --coverage`

![image](https://user-images.githubusercontent.com/2550138/61157411-ad9b8180-a4bb-11e9-9086-76c7c08fa90d.png)

The field resolver is run in the test (and covered just fine), however the parameter of the decorator is not. Is there a way to fix this? It's making the file show not 100% coverage, and is misleading in the coverage report.

**To Reproduce**
Use a parameter for `@FieldResolver(() => SomeEntity)` where `() => SomeEntity` is not covered.

**Expected behavior**
The coverage report should somehow cover this function. May be an issue for ts-jest

**Logs**
Not needed

**Environment (please complete the following information):**
 - OS: `OSX`
 - Node `v10.9.0`
 - Package version `0.17.4` (latest)
 - TypeScript version `3.5.1`

**Additional context**
- `jest@24.8.0`
- `ts-jest@24.0.2`
- `ts-node@8.2.0`

**Comment by 19majkel94** [comment]
Looks like you already defined the field in the object type class. In that case, TypeGraphQL omit the return type parameter of the decorator as you can't overwrite it.

The return type parameter is taken into account only when you define new field for the selected object type using a field resolver.

**Comment by tristanMatthias** [comment]
Thanks for the reply @19majkel94. So am I correct in assuming these can be safely removed as the type is already inferred?

**Comment by 19majkel94** [comment]
I you remove the unused code and it works, then yes, it can be safely removed 😄

**Comment by tristanMatthias** [comment]
OK sweet! Thanks mate :)
