### ISSUE TITLE
Order the fields in the query type alphabetically

### ISSUE THREAD

**Issue by websolutions-hamburg** [19majkel94/type-graphql#379]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this functionality exists, I searched but didn't found it.
I would like to have the fields in the `type Query` sorted alphabetically. At the moment they are not sorted and then they are also unsorted in the Prisma Playground Docs.

**Describe the solution you'd like**
This is my current generated `type Query` from the schema:

```graphql
type Query {
  area(id: String!): AreaModel!
  areas(filter: AreasFilterInput): [AreaModel!]!
  room(id: String!): RoomModel!
  rooms(orderBy: RoomsOrderByInput = ASC): [RoomModel!]!
  session(id: String!): SessionModel!
  sessions: [SessionModel!]!
  topic(id: String!): TopicModel!
  topics: [TopicModel!]!
  timeframe(id: String!): Timeframe!
  timeframes(withoutGaps: Boolean = true): [Timeframe!]!
  partner(id: String!): PartnerModel!
  partners: [PartnerModel!]!
  booth(id: String!): BoothModel!
  booths: [BoothModel!]!
  speaker(id: String!): Speaker!
  speakers: [Speaker!]!
}
```
And the Docs in Prisma Playground looks like this:

![image](https://user-images.githubusercontent.com/26099903/61171006-b2bb0800-a571-11e9-9d8d-eb5f421d17e7.png)

I want the `type Query` to be sorted like this:

```graphql
type Query {
  area(id: String!): AreaModel!
  areas(filter: AreasFilterInput): [AreaModel!]!
  booth(id: String!): BoothModel!
  booths: [BoothModel!]!
  partner(id: String!): PartnerModel!
  partners: [PartnerModel!]!
  room(id: String!): RoomModel!
  rooms(orderBy: RoomsOrderByInput = ASC): [RoomModel!]!
  session(id: String!): SessionModel!
  sessions: [SessionModel!]!
  speaker(id: String!): Speaker!
  speakers: [Speaker!]!
  timeframe(id: String!): Timeframe!
  timeframes(withoutGaps: Boolean = true): [Timeframe!]!
  topic(id: String!): TopicModel!
  topics: [TopicModel!]!
}
```

**Comment by 19majkel94** [comment]
Sorry but this is out of scope  - please create an issue in `graphql-js` repository as it provides introspection query handling, as well as printing the schema:

https://github.com/graphql/graphql-js

**Comment by websolutions-hamburg** [comment]
I follwed the hint from @19majkel94 and asked at the [graphql-js](https://github.com/graphql/graphql-js) repo (https://github.com/graphql/graphql-js/issues/2036).
I solved it now with:

```javascript
transformSchema: (schema: GraphQLSchema) => lexicographicSortSchema(schema)
```
