### ISSUE TITLE
tsconfig min target 

### ISSUE THREAD

**Issue by tbrannam** [19majkel94/type-graphql#38]
It would appear that there are requirements of `type-graphql` which requires a target higher than I had originally been using.  My project was stuck at `es5`, and resolvers for non-scalar types where not being called.   Only after bumping that up to `es6` or higher seemed to resolve this issue.

Along with the other `tsconfig` file suggestions, it may be helpful to specify what the min target language is.

**Comment by 19majkel94** [comment]
TypeGraphQL is designed to work with Node 6, 8 and latest stable:
https://travis-ci.org/19majkel94/type-graphql

It uses ES6 features like `Function.name` to get the name of the class and the ES2016 features like `Array.prototype.includes`. It could work with ES5 (explicit names in decorators + polyfills) but it makes no sense as it works in Node.js 6.

So as the ES specifications doesn't introduce breaking changes, you can safely set `ES2016` (or newer for Node 9.x) in your tsconfig and everything will be working ok 😉

**Comment by tbrannam** [comment]
Great, it was an oversight on my part. Just thought it was a troubleshooting hint for others as I couldn't figure out originally why your example was working and mine wasn't.
