### ISSUE TITLE
How to import models from external module?

### ISSUE THREAD

**Issue by georgyfarniev** [19majkel94/type-graphql#381]
Hello. I moved part of my models (ObjectType, InputType) to separate module (with it's own package.json) and then import it in my application. I get the following error: 
`Error: Cannot determine GraphQL input type for myFieldName`

Is it supported to import models from external modules? If yes, which criteria this module should meet?

UPD: already tried to enable both typescript decorator options and importing `reflect-metadata` in entry points of both modules.

**Comment by 19majkel94** [comment]
Metadata storage is attached to a global scope, so it should work fine.

Please paste some code snippets or create a reproducible code example.

**Comment by 19majkel94** [comment]
From my quick look up it look's like you have `graphql-js` in both node_modules, so all GraphQL built-in scalars like Int or Float are different (fails `instance of` check).
You should switch to monorepo with hoisted dependencies to avoid this.

**Comment by georgyfarniev** [comment]
@19majkel94 you are right. Running lerna bootstrap command with —hoist option did the trick. But what if it will be completely different repositories (possible in near future, as monorepo gets really big)? Any ideas how to make it possible? Because there are many applications that will reuse some models. 

As first idea I got creating factory method that will take parameter of type and create model using this type (passed from consumer), but maybe there’s better approaches?

**Comment by 19majkel94** [comment]
> But what if it will be completely different repositories (possible in near future, as monorepo gets really big)? Any ideas how to make it possible? Because there are many applications that will reuse some models.

They should be bundled and distributed without node_modules. So `import xyz from "graphql"` will look only into the root node_modules where your app code is, so no multiple graphql packages error will occur.

**Comment by georgyfarniev** [comment]
@19majkel94 good idea. Thank you. I think it worth to mention in documentation about this specifics of using type-graphql in different modules.

**Comment by rchl** [comment]
So there is no way to have one package with undecorated models and decorate them after importing from other package, right?

I would like to have a `core` package that would define plain models and controllers that could do plain axios requests to the API and then I wold like to have separate `graphql` package that would generate schema from models defined in `core` and expose a graphql server. But I would like `core` package to not have anything to do with graphql (no dependencies or type-graphql decorators).

I suspect this is conceptually impossible right?

**Comment by 19majkel94** [comment]
It is possible but you have to install the `core` package from package registry (npm or private registry) or use monorepo (lerna) with hoisted dependencies (only one `graphql-js` package in root `node_modules`).

It won't work with symlinks, `file://` and `npm link` in developers environment.

**Comment by rchl** [comment]
@19majkel94 OK, can you give a small example code? Those would be two separate packages installed from private package registry, but I still don't know how would that look like...

I guess I could create and decorate class that `implements` model import from `core` package but as far as I know, that would mean that I would have to duplicate models in two places basically. Is there better solution?

**Comment by 19majkel94** [comment]
> Those would be two separate packages installed from private package registry

Exactly. The will have `graphql-js` as a dependency but during `npm install` it will deduplicate this dep, so you will have only one `graphql` package in the project's `node_modules`.

**Comment by rchl** [comment]
Yeah, but I feel like you are suggesting to add graphql decorators in `core` package while my requirement was to:
> But I would like core package to not have anything to do with graphql (no dependencies or type-graphql decorators).

**Comment by 19majkel94** [comment]
So you think about #294?

> So there is no way to have one package with undecorated models and decorate them after importing from other package, right?

You can import the class and implement it with adding decorators.

**Comment by rchl** [comment]
Yes, #294 is exactly what I'm thinking.
So basically if I follow that idea, I will have to define fields separately from models which is not great for maintainability.

In #294 you've mentioned using a shim with webpack but my `core` package is just pure typescript and I wouldn't want to introduce webpack there. I think I'll just need to add decorators in `core` package directly.

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
