### ISSUE TITLE
Empty `@Resolver()` should work

### ISSUE THREAD

**Issue by JipSterk** [19majkel94/type-graphql#382]
**Describe the bug**
empty resolver decorator throws error about being empty. in the examples (e.g. enums-and-unions) this is allowed but when i try the same in my codebase it throws an error.

**Expected behavior**
empty `@Resolver()` decorator should work without providing an explicit type

**Logs**
(node:68310) UnhandledPromiseRejectionWarning: Error: No provided object type in '@Resolver' decorator for class 'UserResolver!'
    at Object.getObjectType (/Users/jipsterk/Repos/project/node_modules/type-graphql/dist/decorators/Resolver.js:17:23)
    at /Users/jipsterk/Repos/project/node_modules/type-graphql/dist/metadata/metadata-storage.js:130:22
    at Array.forEach (<anonymous>)
    at MetadataStorage.buildFieldResolverMetadata (/Users/jipsterk/Repos/project/node_modules/type-graphql/dist/metadata/metadata-storage.js:122:21)
    at MetadataStorage.build (/Users/jipsterk/Repos/project/node_modules/type-graphql/dist/metadata/metadata-storage.js:77:14)
    at Function.generateFromMetadataSync (/Users/jipsterk/Repos/project/node_modules/type-graphql/dist/schema/schema-generator.js:29:51)
    at Function.<anonymous> (/Users/jipsterk/Repos/project/node_modules/type-graphql/dist/schema/schema-generator.js:16:33)
    at Generator.next (<anonymous>)
    at /Users/jipsterk/Repos/project/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
(node:68310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:68310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Environment (please complete the following information):**
 - OS: macOS
 - Node: v12.6.0
 - Package version: 0.17.4
 - TypeScript version: 3.5.3

**Comment by 19majkel94** [comment]
https://typegraphql.ml/docs/resolvers.html

![image](https://user-images.githubusercontent.com/10618781/61305094-82ca6980-a7ea-11e9-8660-cc1e13721362.png)

**Comment by JipSterk** [comment]
how stupid of me now it works like a charm. thanks for the help

**Comment by justinmchase** [comment]
What if Recipe is an `@InterfaceType()` the interface example doesn't seem to be quite complex enough.

Getting lots of null reference errors out of type-graphql which are really hard to debug.

**Comment by 19majkel94** [comment]
@justinmchase 
For now interface type only supports fields/properties, not methods with args - related to #261.

**Comment by theseyi** [comment]
Seems resolvers do not support union types? 

```js
const RecipeUnion = createUnionType({ types: () => [SaladRecipe, SpicyRecipe], resolveType: () => {/**resolve*/}})l

@Resolver(of => RecipeUnion)
class RecipeUnionResolver {
// ...field resolvers, queries, mutations
}

**Comment by MichalLytek** [comment]
@theseyi GraphQL spec doesn't support union resolvers. Union is a set of object types. You should create separate resolvers for those object types if you want to add field resolvers for them.

**Comment by theseyi** [comment]
> @theseyi GraphQL spec doesn't support union resolvers. Union is a set of object types. 

Thanks
> You should create separate resolvers for those object types if you want to add field resolvers for them.

I will give this a shot. Seems I should able to do this using the [mixin pattern](https://github.com/MichalLytek/type-graphql/tree/v1.1.1/examples/mixin-classes)? So I can dynamically share the `@FieldResolver` method between them
