### ISSUE TITLE
FieldResolver @Root() return undefined

### ISSUE THREAD

**Issue by ydomenjoud** [19majkel94/type-graphql#389]
Hi there,

**Describe the bug**
I can't get @Root value from FieldResolver. It's always "undefined". with type-graphql , typeorm, nestjs. 

**To Reproduce**
 champ.ts
```typescript
@Entity()
@ObjectType()
export class Champ {

  @PrimaryGeneratedColumn()
  @Field()
  id: number;

  @Field(type => Beneficiaire)
  @ManyToOne(type => Beneficiaire, beneficiaire => beneficiaire.champs)
  @JoinColumn()
  beneficiaire: Beneficiaire;
}
```
beneficiary.ts
```typescript
@Entity()
@ObjectType()
export class Beneficiaire {
  @Field(type => ID)
  @PrimaryGeneratedColumn()
  id: number;

  @Field(type => Champ, { nullable: true })
  @OneToMany(() => Champ, champ => champ.beneficiaire, { cascade: true })
  champs: Champ[];
```

beneficiaire.resolver.ts
```typescript
@Resolver(of => Beneficiaire)
export class BeneficiaireResolver {

  constructor(@InjectRepository(Beneficiaire) private readonly beneficiaireRepository: Repository<Beneficiaire>) {
  }

  @FieldResolver(type => Champ)
  async champs(@Root() beneficiaire: Beneficiaire) {
    console.log(beneficiaire);
  }

  @Query(returns => [Beneficiaire])
  beneficiaires(): Promise<Beneficiaire[]> {
    return this.beneficiaireRepository.find({take: 10});
  }
}
```

Graphql request
```
{
  beneficiaires{
  id
  champs {
    id
    }
  }
}
```

results : 
```json
{
  "data": {
    "beneficiaires": [
      {
        "id": "1",
        "champs": null
      }
    ]
  }
}
```

and console.log() print "undefined" in my console althought graphql return Beneficiaire(id: 1)

**Expected behavior**
I expect that console.log() to print root entity

**Logs**
log of my console 
```
query: SELECT `Beneficiaire`.`id` AS `Beneficiaire_id` FROM `beneficiaire` `Beneficiaire` LIMIT 10
undefined
```

**Enviorment (please complete the following information):**
 - OS: ubuntu 18.04
 - Node: 10.16.0 
 - Packages version: 
    "type-graphql": "^0.17.4",
    "graphql": "^14.4.2",
    "typeorm": "^0.2.18"
    "@nestjs/graphql": "^6.4.2",
 - TypeScript version:
    "typescript": "3.4.3"

same behavior with mssql and mysql

Did I miss anything? 

Thanks for your time

**Comment by ydomenjoud** [comment]
Found solution about this issue : 
I was importing Root decorator from "@nestjs/graphql" instead of "type-graphql" .

**Comment by KROSF** [comment]
I have the same issue but i'm using typegoose and express
