### ISSUE TITLE
context parameter is undefined in Subscription filter method

### ISSUE THREAD

**Issue by georgyfarniev** [19majkel94/type-graphql#391]
**Describe the bug**
A context parameter is undefined in my **Subscription** **filter** function. However. @Ctx decorator injection works well in mutations and queries. I didn't see any examples of using context in Subscription filter, it present in **filter** args, but has undefined value.

I need to access my context passed from Koa to filter notifications for specific users, so I need access to it inside **filter**

**To Reproduce**
Try to access context param in Subscription filters function. Example:

```js
 @Subscription(() => MyData, {
    topics: 'MY_TOPIC',
    filter: ({ context }: ResolverFilterData<MyData>) => {
      // context undefined here
      return true
    }
  })
```

**Expected behavior**
Context are properly passed in parameters

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

**Enviorment (please complete the following information):**
 - OS: Windows 10
 - Node 12
 - Package version 0.17.4
 - TypeScript 3.5.3

**Comment by georgyfarniev** [comment]
I checked code of type-graphql, turns out problem probably in apollo side. Closing.

**Comment by pellejacobs** [comment]
For anyone trying to understand how to solve this: https://github.com/apollographql/apollo-server/issues/1796#issuecomment-429237068

**Comment by electrovir** [comment]
Latest solution is to pass in a `context` property when calling `useServer` from the `graphql-ws` library:

https://www.apollographql.com/docs/apollo-server/data/subscriptions/#operation-context
