### ISSUE TITLE
Give a resolver's parameter to a middleware

### ISSUE THREAD

**Issue by Nooka10** [19majkel94/type-graphql#394]
Hi,

Is there a way to give a resolver's parameter to a middleware?

I create a middleware that ask for an _id_ parameter like that:
```ts
export function isYourself(id: number): MiddlewareFn<MyContext> {
	return async(action, next) => {
		if(id && id !== action.context.user.id) {
			throw new Error('You can\'t modify information of another user than yourself!');
		}
		return next();
	};
}
```

In my resolver, I'm trying to use the id parameter I receive to give it to the middleware:

```ts
@Query(returns => UserModel, {nullable: true, description: 'Return the user corresponding to the received userId.'})
@UseMiddleware(isAuthenticated, isYourself(userId))
user(@Arg('userId', type => IdScalar) userId: number, @Ctx() context: Context): Promise<UserModel> {
	return this.userServices.getUserById(userId);
}
```

But TypeScript doesn't compile as he doesn't know _userId_...

How can I do that?
I know that I can access the args directly in my middleware, but the problem is that the name of my args change depending on the resolver... So I was thinking to give the id by myself so in my middleware, I use only one name...

Thanks for the help!

**Comment by 19majkel94** [comment]
>  but the problem is that the name of my args change depending on the resolver

So just pass it as a middleware factory parameter:

```ts
export function isYourself(idArgKey: string): MiddlewareFn<MyContext> {
	return async(action, next) => {
		if(action.args[idArgKey] !== action.context.user.id) {
			throw new Error('You can\'t modify information of another user than yourself!');
		}
		return next();
	};
}
```

**Comment by Nooka10** [comment]
Ooooh! 
So easy! That's perfect!
Thank you very much!
