### ISSUE TITLE
Using graphql rate limiter (directive - alternative way ?)

### ISSUE THREAD

**Issue by appsolutegeek** [19majkel94/type-graphql#398]
**Describe the issue**

Hi, we currently use the following added to the graphql sdl as a directive. https://github.com/teamplanes/graphql-rate-limit . 

Directives are not supported currently with type-graphql but reading the issues it appears it maybe possible to use middleware to apply the graphql rate limiter but no additional details could be found.

Can anyone help ? bascially wanting to use the following https://github.com/teamplanes/graphql-rate-limit but with type-graphql

**Comment by 19majkel94** [comment]
This might help you:

https://www.youtube.com/watch?v=OEqkFl1-G7Y

**Comment by appsolutegeek** [comment]
Great, thank you.
