### ISSUE TITLE
"Property '0' is missing" error when FieldResolver function returns an array

### ISSUE THREAD

**Issue by promethe42** [19majkel94/type-graphql#400]
**Describe the bug**

Field resolvers returning array types cannot build without using the [`--transpile-only` option of `ts-node`](https://github.com/TypeStrong/ts-node#cli-and-programmatic-options). But using this option completely disable type checking, which defeats one of the major reasons to use TS in the first place.

I'm very new to TS, but my guess is the field decorator generates a getter that returns a tuple instead of an array.

**To Reproduce**

```typescript
@Service()
@Resolver(of => Bill)
export class BillResolver implements ResolverInterface<Bill> {
  // ...
  @FieldResolver(returns => [Article])
  async articles(@Root() bill: Bill) : Promise<Article[]> {
    let mergeRequests = await gitlabClient.MergeRequests.all({ projectId: bill.id }) as any[];

    return mergeRequests.map((b) => Article.fromGitlabMergeRequest(b));
  }
}
```

**Expected behavior**

This code should build an run fine.

**Logs**

```
api_1     | [ERROR] 19:17:44 ⨯ Unable to compile TypeScript:
api_1     | src/bill-resolver.ts(123,9): error TS2416: Property 'articles' in type 'BillResolver' is not assignable to the same property in base type 'ResolverInterface<Bill>'.
api_1     |   Type '(bill: Bill) => Promise<Article[]>' is not assignable to type '(root: Bill, ...args: any[]) => [Article] | Promise<[Article]>'.
api_1     |     Type 'Promise<Article[]>' is not assignable to type '[Article] | Promise<[Article]>'.
api_1     |       Type 'Promise<Article[]>' is not assignable to type 'Promise<[Article]>'.
api_1     |         Property '0' is missing in type 'Article[]' but required in type '[Article]'.
```

**Environment (please complete the following information):**

 - OS: Alpine
 - Node: 10.16.0
 - Package version: 0.17.4
 - TypeScript version: 3.5.3

**Comment by 19majkel94** [comment]
Please paste the `Bill` class code - I bet you have 
```
@Field(type => [Article])
articles: [Article];
```
It should be `articles: Article[]`;

**Comment by promethe42** [comment]
Bingo! Thanks a lot!
