### ISSUE TITLE
TypeORM relations based on field selection in GraphQL

### ISSUE THREAD

**Issue by voslartomas** [19majkel94/type-graphql#402]
**Is your feature request related to a problem? Please describe.**
Imagine query which returns for example list of `User`, user has relation to another table `Status`, this is Lazy loaded, so if you make request and don't ask for status, it will not do the SQL query, but if you query status in your graphql, it will do as many SQL queries as many users.

Obviously you can always prefetch status when querying users, but that is not the solution we want.

**Describe the solution you'd like**
So we would like to have something like Decorator, which would read info about query (specifically selections) and would return this info to resolver, where you could use it in TypeORM (relations: [ 'status' ], to optimize SQL query.

I am not sure if this should be part of type-graphql as some helper decorator, or should be outside as library. But first I would like to ask if anyone already solved this problem?

**Comment by 19majkel94** [comment]
> I am not sure if this should be part of type-graphql 

No, TypeGraphQL is not related to TypeORM nor mongoose.

> But first I would like to ask if anyone already solved this problem?

https://github.com/Webtomizer/typeorm-loader

**Comment by voslartomas** [comment]
typeorm-loader does not seem like solution, because it for example cannot have skip, limit, there is only where condition. But parsing graphql selections is exactly what I meant, thanks.

**Comment by 19majkel94** [comment]
> But parsing graphql selections is exactly what I meant, thanks.

See #10 😉 

Using info for limiting `select` fields in query is powerful yet dangerous technique so must be used wisely. E.g. your field resolver might use a field like `id` but if it's not present in the query, it won't be fetched and will be undefined.
