### ISSUE TITLE
maybe a bug: resolveType union wrong when return type class @ObjectType

### ISSUE THREAD

**Issue by quaj** [19majkel94/type-graphql#406]
Hi
i have a problem with union but problem has been solved by change

![image](https://user-images.githubusercontent.com/16853175/63541196-cb8ee400-c547-11e9-8797-3c7984eae834.png)

to

![image](https://user-images.githubusercontent.com/16853175/63541210-d21d5b80-c547-11e9-94af-23a4fb8afb68.png)

at first node query return empty object, but fixed bug by above 😷

![image](https://user-images.githubusercontent.com/16853175/63541356-17da2400-c548-11e9-9d0d-bc2f70ea9afe.png)

```graphql
{
  node(id: "VHJlZTo2NTc4NDI3NjUyNjcxMTcyNjA4") {
    ... on Tree {
      id
      version
    }
  }
}

```

**Comment by quaj** [comment]
Maybe cuz in my class @ObjectType not placing a name 🤔

**Comment by quaj** [comment]
> Maybe cuz in my class @ObjectType not placing a name 🤔

it's not

**Comment by 19majkel94** [comment]
Once again - what is the problem? Can you show me your object type classes or create a minimal reproducible code example repository? :confused:

**Comment by quaj** [comment]
maybe my dictation not very right
with code in `img1`, graphql server return "{"node":{}}" ( an empty object )
then i has changed to `img2`, graphql server return as expected
so i said "maybe a bug with `returnType` function"

**Comment by 19majkel94** [comment]
Covered by tests:

https://github.com/19majkel94/type-graphql/blob/2a391160170805d78d307dd721927eae24bd25a9/tests/functional/unions.ts#L65-L77

https://github.com/19majkel94/type-graphql/blob/2a391160170805d78d307dd721927eae24bd25a9/tests/functional/unions.ts#L123-L129

https://github.com/19majkel94/type-graphql/blob/2a391160170805d78d307dd721927eae24bd25a9/tests/functional/unions.ts#L246-L264

Please create a repository with a minimal reproducible code example.

**Comment by quaj** [comment]
I have created a repo: https://github.com/quaj/reproduce-bug-type-graphql
guess this bug come with typegoose, tested regular class then nothing happend

Query test:

```
{
  node(id: "5d5da8ace13a526cf80fc264") {
    ... on Tree {
      version
    }
  }
}
```

**Comment by 19majkel94** [comment]
Cannot reproduce:

```graphql
# Write your query or mutation here
{
  node(id: "5d602b0caf25c15fa0f7fe67") {
    ... on Tree {
      version
    }
    ... on Repo {
      source_id
    }
  }
}
```
```json
{
  "data": {
    "node": {
      "source_id": "test"
    }
  }
}
```
It will return `node: {}` when the returned type is not covered by the `... on` fragment syntax for this type.

**Comment by quaj** [comment]
sorry my bad, at first i covered with fragment but it's fragement of Tree so it return not correct

dont know why but in my production code bug still happened but in reproduce code is not
![image](https://user-images.githubusercontent.com/16853175/63615242-10318280-c60f-11e9-9550-7ed50a0e9a8f.png)
![image](https://user-images.githubusercontent.com/16853175/63615254-16276380-c60f-11e9-8174-612534248156.png)

i can't move all source of production to reproduce this bug
anyway problem solved to me

many thanks @19majkel94, sorry for taking your time

**Comment by quaj** [comment]
Ah sorry, upload wrong image :D 
![image](https://user-images.githubusercontent.com/16853175/63616249-5687e100-c611-11e9-96d5-a0bbf156bc14.png)
