### ISSUE TITLE
Typeorm lazyload promises 

### ISSUE THREAD

**Issue by mindonline** [19majkel94/type-graphql#42]
Is possible to use this library with typeorm lazyload promises?

**Comment by 19majkel94** [comment]
@mindonline I've just pushed the lazy-loading example:
https://github.com/19majkel94/type-graphql/tree/c941a120948d37e927520f68040837dac8fc1eca/examples/07-typeorm-lazy-relations

However I'm thinking about the transparent lazy-load for field resolvers. With this feature you can keep your entities relation sync (not promise) and under the hood `TypeGraphQL` would lazy load the relation on demand when there's no defined resolver for this field.
I could use this class for typeorm:
https://github.com/typeorm/typeorm/blob/d24835001d4e6a22682b5a5d318ebfc1934ee392/src/lazy-loading/LazyRelationsWrapper.ts
However I don't want to integrate TypeGraphQL with TypeORM as a hard dependency - it can work without DB or with mongoose, etc. So I need to think how to implement this feature.
