### ISSUE TITLE
Does mutation requires all inputs in a specific field (e.g "input")?

### ISSUE THREAD

**Issue by stonecold123** [19majkel94/type-graphql#49]
The mutation examples show that the inputs have to be put under a specific field e.g (@Arg("input")). When I use @Args() instead, I'm getting this error  when the server starts

````
(node:15051) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'target' of undefined
    at params.reduce (/web/node_modules/type-graphql/schema/schema-generator.js:240:69)
````
Is it a must to use @Arg("input")?

This example won't work:
````
    @Mutation(returnType => ItemLike)
    async updateItemLikes(@Args() {id, userId}: UpdateItemLikesArgs) {
               return ....
    }
````

**Comment by 19majkel94** [comment]
No,  inputs doesn't have to be put under a specific field:
https://github.com/19majkel94/type-graphql/blob/master/tests/functional/resolvers.ts#L61
https://github.com/19majkel94/type-graphql/blob/master/tests/functional/resolvers.ts#L379

Do you have `ES6` or newer set in your tsconfig.json?

**Comment by 19majkel94** [comment]
The problem is here:
```ts
const argumentType = metadata_storage_1.MetadataStorage.argumentTypes.find(it => it.target === param.getType());
let superClass = Object.getPrototypeOf(argumentType.target);
```
Looks like `UpdateItemLikesArgs` has not been found in `MetadataStorage.argumentTypes` - have you decorate the class with `@ArgsType` decorator?

**Comment by stonecold123** [comment]
@19majkel94 
Yes, using InputType() instead of ArgsType() fixes the error. 
Is `InputType()` different from `ArgsType()`? The doc shows that the use of `@InputType()` for mutaton
https://github.com/19majkel94/type-graphql/blob/master/docs/validation.md
````
@InputType()
export class UpdateItemLikeArgs {
    @IsInt()
    @Field(type => Int)
    id: number;

    @IsInt()
    @Field(type => Int)
    userId: number;
}
````

**Comment by 19majkel94** [comment]
> Is InputType() different from ArgsType()?

Of course! `InputType` will generate real `GraphQLInputType` and should be used when you want to have nested object in args:
```ts
@InputType()
export class UpdateItemLikeArgs {
    @IsInt()
    @Field(type => Int)
    id: number;

    @IsInt()
    @Field(type => Int)
    userId: number;
}
class Resolver {
    @Mutation(returnType => ItemLike)
    async updateItemLikes(@Arg("payload") {id, userId}: UpdateItemLikesArgs,@Ctx() context:any) {}
}
```
will generate:
```graphql
input UpdateItemLikesArgs {
  id: Int!
  userId: Int!
}
type Mutation {
  updateItemLikes(payload: UpdateItemLikesArgs!): ItemLike!
}
```
But ArgsType is virtual, it will be flattened in schema:
```ts
@ArgsType()
export class UpdateItemLikeArgs {
    @IsInt()
    @Field(type => Int)
    id: number;

    @IsInt()
    @Field(type => Int)
    userId: number;
}
class Resolver {
    @Mutation(returnType => ItemLike)
    async updateItemLikes(@Args() {id, userId}: UpdateItemLikesArgs,@Ctx() context:any) {}
}
```
So it will look like this in SDL:
```graphql
type Mutation {
  updateItemLikes(id: Int!, userId: Int!): ItemLike!
}
```
So you can use `@Args()` directly with input type, it can be nested as a field of `ArgsType`. To mount input field directly to mutation, use `@Arg("name")` decorator.

**Comment by davewasmer** [comment]
Just ran into this myself - might be worth checking when `@Args()` is used, and providing a helpful error message explaining (or even just linking to this issue thread).

**Comment by 19majkel94** [comment]
It's described in FAQ:
https://19majkel94.github.io/type-graphql/docs/faq.html#is-inputtype-different-from-argstype

So if the problem is that people use `@Args` with `@InputType` or without `@ArgsType`, I can check and handle that 😉
