### ISSUE TITLE
Default values in schema

### ISSUE THREAD

**Issue by j** [19majkel94/type-graphql#53]
I want optional args that have default values defined in GraphQL (not just nullable types with default variable values).  Is this possible?

**Comment by 19majkel94** [comment]
Right now defaults are handled on JS side. You want to reflect that default in schema?
AFAIK, it affects only the visual aspect of graphiql docs:

![image](https://user-images.githubusercontent.com/10618781/38130779-a394bdb0-3404-11e8-94b9-b72460d964cc.png)

The behavior is the same as now with defaults in JS.
Technically I could do this for input and args classes but not for inline `@Arg()` - I would have to introduce the `defaultValue` decorator option which doesn't look good for me 😕

**Comment by j** [comment]
Yeah, just schema default values.  As of now, I'm just doing nullable with default JS values as you said.  But it'd be nice to use the built-in version to get doc support.  Although for internal APIs, I'm okay with having nullable args with internal defaults.  Can @Arg() take options to set defaultValue?

**Comment by 19majkel94** [comment]
Yes, I will emit the `defaultValue` in schema for `@ArgsType()` and `@InputType()` from JS defaults and add an option for `@Arg()` decorator. But it's a minor feature with easy workaround so it has low prio for now.

If you want help, you can create a PR for `@Arg()` - it should be only a few lines of code for that, but you would also need to add one test case for that. I would be grateful 😉
