### ISSUE TITLE
Old version of "@types/graphql"

### ISSUE THREAD

**Issue by newtack** [19majkel94/type-graphql#58]
The latest version is 0.13.2, but type-graphql is using "@types/graphql": "^0.12.7".

Could you upgrade to the latest? Also, unless there is a good reason, it would be great to keep the libraries up to date. In my projects I use https://www.npmjs.com/package/npm-check-updates.

I love the library so far, great job!

**Comment by 19majkel94** [comment]
I've updated the deps [a few days ago](https://github.com/19majkel94/type-graphql/commit/cb1916a5c19d6259ce4bd8b9318871bca683295a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) but sure, I will update again soon!
Thanks for reporting 😉

**Comment by pkeuter** [comment]
Thanks @19majkel94 for this library! Could this issue be the reason that I'm unable to assign the schema to express-graphql? ```Argument of type '{ schema: GraphQLSchema; graphiql: true; }' is not assignable to parameter of type 'Options'.
  Type '{ schema: GraphQLSchema; graphiql: true; }' is not assignable to type 'Promise<OptionsData>'.
    Property 'then' is missing in type '{ schema: GraphQLSchema; graphiql: true; }'.```.

**Comment by 19majkel94** [comment]
I don't think so. Can you show the whole code for buildSchema and express-graphql?

**Comment by KevinGong2013** [comment]
this issue has some progress?

**Comment by 19majkel94** [comment]
Yes, we have to wait for other packages:
https://github.com/apollographql/subscriptions-transport-ws/issues/398

In the meantime I recommend downgrading to:
```js
{
  "@types/graphql": "^0.12.7",
  "@types/express-graphql": "^0.6.1",
  "express-graphql": "^0.6.12",
  "subscriptions-transport-ws": "^0.9.7"
}
```

**Comment by 19majkel94** [comment]
Closing by b6131b6.
