### ISSUE TITLE
Synchronous version of buildSchema 

### ISSUE THREAD

**Issue by dsebastien** [19majkel94/type-graphql#59]
Hello,

Nice project!

`buildSchema` currently only returns promises. 

For my uses case, this is a problem because I'm writing Firebase functions, which are supposed to export something from the module: `export const api: firebaseFunctions.HttpsFunction = firebaseFunctions.https.onRequest(app);`, where "app" is an "express" app in which I'm using Apollo GraphQL, which.. needs the GraphQL schema.

For this reason I can't apply your approach with an async ``bootstrap` function..

I don't find an easy work around for this issue; do you have any ideas or think a synchronous version of the "buildSchema" function could be added?

**Comment by 19majkel94** [comment]
Technically it's possible. I've changed it to async a few weeks ago to perform additional check of schema integrity - incorrect implementations of interfaces when someone overrides fields with decorators:
https://github.com/19majkel94/type-graphql/commit/1b6af9a8f908ffd60af2cc0a7fe89943f024240e#diff-48f4a1f7b529a17d4579df20f8af7af1R51

I may introduce the sync, unsafe version of `buildSchema` but there's really no way to make the app bootstraping async/lazy on Firebase? 😕

**Comment by dsebastien** [comment]
Ok then it would be nice to introduce a synchronous version.

As far as I can see the only way to work with firebase cloud functions is to use the export keyword and from there, I don't see a way to build the express app and be able to do the `export const api: firebaseFunctions.HttpsFunction = firebaseFunctions.https.onRequest(app);`.

**Comment by 19majkel94** [comment]
Technically you could do this:
```ts
export const api = firebaseFunctions.https.onRequest(async (...args) => {
    const app = await appPromise;
    return appPromise(...args);
  );
```

**Comment by 19majkel94** [comment]
Closing via a212fd1 🎉
