### ISSUE TITLE
GraphQL interface type and class extending support 

### ISSUE THREAD

**Issue by 19majkel94** [19majkel94/type-graphql#6]
- [x] support for `GraphQLInterface`
- [x] support for extending classes with definitions

**Comment by 19majkel94** [comment]
> Does this mean that this issue #6 is obsolete? What is planed to support there?

@4F2E4A2E
No, this task is about support interfaces in GraphQL schema:
http://graphql.org/learn/schema/#interfaces

I've only created the task issue but I haven't thought about the API design and use cases yet.
However I think it will look like this:
```ts
@GraphQLInterfaceType()
export abstract class Character {
  @Field(type => ID)
  id: string;

  @Field()
  name: string;

  @Field(type => Character)
  friends: Character[];

  @Field(type => Episode)
  appearsIn: Episode[];
}

@GraphQLObjectType()
export class Human implements Character {
  @Field(type => ID)
  id: string;

  @Field()
  name: string;

  @Field(type => Character)
  friends: Character[];

  @Field(type => Episode)
  appearsIn: Episode[];

  @Field(type => Starship)
  starships: Starship[];

  @Field(type => Int)
  totalCredits: number;
}

@GraphQLObjectType()
class Droid implements Character {
  @Field(type => ID)
  id: string;

  @Field()
  name: string;

  @Field(type => Character)
  friends: Character[];

  @Field(type => Episode)
  appearsIn: Episode[];

  @Field({ nullable: true })
  primaryFunction: string;
}
```

It is possible to do this without repeating the decorators:
```ts
@GraphQLObjectType({ implements: Character })
export class Human implements Character {
  id: string;
  name: string;
  friends: Character[];
  appearsIn: Episode[];

  @Field(type => Starship)
  starships: Starship[];

  @Field(type => Int)
  totalCredits: number;
}
```
However I'm not convinced it's a good choose. I prefer explicitness but decorator duplication means N times doing the same changes in every implementation so it's easy to make a mistake, but the correctness of interface implementation might be checked on schema-build time of course.
What do you think?

**Comment by 4F2E4A2E** [comment]
I prefer explicitness too and the fact that you can duplicate decorators, but don't have too is just great and very useful in many cases, so thanks for that! 👍

**Comment by 4F2E4A2E** [comment]
This is maybe worth noticing: https://github.com/graphql/graphql-js/pull/1235
