### ISSUE TITLE
Use ObjectType and InputType decorators together

### ISSUE THREAD

**Issue by winuxue** [19majkel94/type-graphql#62]
I want to use **ObjectType** and **InputType** decorators in the same class.
But i'm getting this error at runtime:
Schema must contain unique named types but contains multiple types named "xyz".

**Comment by 19majkel94** [comment]
This should work:
```ts
@InputType("PersonInput")
@ObjectType("PersonType")
export class Person {
  @Field()
  name: string;

  @Field()
  dateOfBirth: Date;
}
```

However, be aware that GraphQL has separate type for input for reasons.
According to the spec: http://facebook.github.io/graphql/October2016/#sec-Input-Objects
> The Object type defined above is inappropriate for re‐use here, because Objects can contain fields that express circular references or references to interfaces and unions, neither of which is appropriate for use as an input argument. For this reason, input objects have a separate type in the system.

So you should have different classes for input and output types, even if it partially violate DRY rule.
You can use `implement Partial<XYZ>` to have typesafe on fields (no field type mismatch between input and entity/output).

**Comment by 19majkel94** [comment]
@winuxue Does the solution work for your problem? Can I close this issue for housekeeping purposes?

**Comment by 19majkel94** [comment]
Closing for housekeeping purposes.
@winuxue please reopen the issue if the problem still exist.

**Comment by ap-vasu** [comment]
When integrating it with typeorm entities using the Nullable HOC concept which u have mentioned in other issue getting the same this error Schema must contain uniquely named types but contains multiple types named "CreateGroupInput".
`export const GroupWrapper = (nullable: boolean) => {

  @InputType(nullable ? "UpdateGroupInput" : "CreateGroupInput")
  @ObjectType('GroupType')
  @Entity()
  class Group extends DefaultEntity {
    @Field({
      nullable: !nullable,
    })
    @PrimaryGeneratedColumn("uuid")
    _id: string;

    @Field({
      nullable,
    })
    @Column({
      unique: true,
    })
    name: string;
}
return Group`;

`export const GroupPlanWrapper = (nullable: boolean) => {
  @InputType(nullable ? "UpdateGroupPlanInput" : "CreateGroupPlanInput")
  @ObjectType("GroupPlanType")
  @Entity("group_plan")
  class GroupPlan extends DefaultEntity {
    @Field((type) => Group)
    @ManyToOne(
      () => Group,
      (group) => group._id,
      {
        cascade: true,
        eager: true,
      }
    )
    @JoinColumn({ name: "group_id" })
    group: Promise<Group>;

    @Field({ nullable })
    @Column()
    name: string;
return GroupPlan;
}`
