### ISSUE TITLE
An example of the nested mutation

### ISSUE THREAD

**Issue by limenutt** [19majkel94/type-graphql#64]
Hi!
First of all, great library, thanks a lot!
I'm currently building a graphql API and want to make it as generic as possible.
I have many objects and want to have same generic mutations for each object type (create, update and delete). At the moment, I have implemented a resolver for each of my object types, each with it's methods so I can update my objects like this:
```graphql
mutation {
   addBook(input: $bookInput) {
     id
  }
}
```
```graphql
mutation {
   addUser(input: $userInput) {
     id
  }
}
```
```graphql
mutation {
   addProject(input: $projectInput) {
     id
  }
}
```
Is there a way to instead nest the mutation under the object name, like so

```graphql
mutation {
   book 
     add(input: $bookInput) {
       id
    }
}
```
```graphql
mutation {
   user 
     add(input: $userInput) {
       id
    }
}
```
```graphql
mutation {
   project 
     add(input: $projectInput) {
       id
    }
}
```
In this case I could implement the basic mutations (add, update and delete) in the base resolver class and just inherit from it in object-specific resolvers, maybe use some decorators to override the input types.

**Comment by 19majkel94** [comment]
Nested mutations sound nice, I haven't thought about it but it seems possible to do.

However, about the resolver inheritance part:
> I could implement the basic mutations (add, update and delete) in the base resolver class and just inherit from it in object-specific resolvers

We've already discussed it:
https://github.com/19majkel94/type-graphql/issues/47
And it's just better to have less magic and inheritance problem. Decorator duplication is not an issue, it's like a documentation for your API. You can move your common CRUD logic to generic service and inject the specific extended services per entity type.

**Comment by chrisdostert** [comment]
Just adding my opinion this would be awesome to have. There are examples of [mainstream API's taking this tact](https://graphql-api.com/guides/optin/using-nested-mutations/) successfully. In my experience, having resolvers at root level results in an [anemic domain model](https://martinfowler.com/bliki/AnemicDomainModel.html) and should be avoided.

**Comment by MichalLytek** [comment]
> having resolvers at root level results in an anemic domain model

I have no idea why nesting might help you with domain model.

If you want to have:

```graphql
query {
  user {
    create(...) {
      # ...
    }
  }
}
```
you can just join the two words into a one camelCase'd:
```graphql
mutation {
  userCreate(...) {
    # ...
  }
}
```

TypeGraphQL let define such schema in a decoupled fashion. Instead of adding `@FieldResolver` decorator just use `@Mutation` and the rest of the code stays the same.

> In my experience, having resolvers at root level results in an anemic domain model and should be avoided if possible.

GraphQL is designed around root level queries and mutations and you need to live with this.
Trying to introduce REST patterns of `/resources/subresources/action` makes no sense.
There's no need to fight against it.

**Comment by mwalkerr** [comment]
It wasn't immediately clear to me how to make this work, so here's some example code to help anyone else trying to do this:
```
@ObjectType()
class BookQuery {
  @Field(() => Book)
  async add(@Arg("id") id: string) {
    return ...
  }
}
@ObjectType()
class BookMutation {
  @Field(() => Boolean)
  async add(@Arg('book') book: Book) {
    return ...
  }
}


@Resolver()
export class BookResolver {
  @Query(() => BookQuery, { name: 'book' })
  bookQuery() {
    return {};
  }

  @Mutation(() => BookMutation, { name: 'book' })
  bookMutation() {
    return {};
  }
}
```

**Comment by MoSattler** [comment]
It would be cool to be able to nest mutations to get work done in fewer requests. Imagine you want to add an `Author` and one of his `Book`s in one request:
```graphql
createAuthor(input: $authorInput) {
  name
  createBook(input: $bookInput) {
    title
  }
}
```

That'd be neat. But it is not currently part of the Graphql spec, see the discussion [here](https://github.com/graphql/graphql-spec/issues/252).
