### ISSUE TITLE
Is there any global error handler to catch the error from @Service()

### ISSUE THREAD

**Issue by stonecold123** [19majkel94/type-graphql#67]
Is there a global error handler like `ExpressErrorMiddlewareInterface` in  `routing-controller`?  I found that `apollo-server-express` isn't able to catch any error thrown from  `@Service()`, for example:

````

@Service()
class someService{
    throwError(){
        throw new Error('xxxxx') 
    }
}

@Resolver()
class Resolver{

    public constructor(private someService: someService) {}

    @Mutation(returnType => GraphQLBoolean)
    async createDocuments() {
            this.someService.throwError();
            return true;
    }
}
````
The error would crash the app instead of catching it and showing it in the graphql response.

However, if the error is directly thrown in `createDocuments` method, the server is able to catch that.

 Any way to prevent that other than wrapping every service's method in a try catch statement?

**Comment by 19majkel94** [comment]
Soon you will be able to catch errors in middlewares:
https://github.com/19majkel94/type-graphql/blob/middlewares/examples/middlewares/middlewares/error-logger.ts

I am writing docs for this feature and I'm going to release this feature by the end of this week 😉

**Comment by 19majkel94** [comment]
> The error would crash the app instead of catching it and showing it in the graphql response.

There's something wrong with `apollo-server-express`. By design all errors are wrapped into `GraphQLError` class instance and should be returned to the user as `errors` field in JSON.

**Comment by stonecold123** [comment]
@19majkel94 
Yes, I'm worried about that. I'm hoping that your new error middlewares can fix this issue.

**Comment by 19majkel94** [comment]
I use `graphql-yoga` here in examples, it's all-in-one library for graphql server 😀

**Comment by 19majkel94** [comment]
I've modified the `using-container` example:
```ts
@Service()
export class RecipeService {
  // ...
  async getOne(id: string) {
    throw new Error(`Recipe with id ${id} has not been found!`);
    // return this.items.find(it => it.id === id);
  }
}
```
```graphql
query GetRecipe1 {
  recipe(recipeId: "1") {
    title
    description
    ingredients
    numberInCollection
  }
}
```
![image](https://user-images.githubusercontent.com/10618781/39082624-886db36c-4556-11e8-8471-a1c7efe48f1e.png)

I think you need to create a repository with a minimal reproducible  example.

**Comment by stonecold123** [comment]
@19majkel94 
It has nothing to do with @Service. It happens when I return `true` too early and there's no way for the server to catch an error that happens thereafter in a async/await loop.
For example:
````
    @Mutation(returnType => GraphQLBoolean)
    async createDocuments() {
            let list = ["A","B"];
            list.map(async (item)=>{
                    throw new Error(`error`)
                    await dbAction(item);
            })
            return true;
    }
````
The error would not be caught and my app just crashes.

**Comment by 19majkel94** [comment]
You should just do:
```ts
await list.map(async item => {
  throw new Error(`error`);
  await dbAction(item);
});
```
If there's no await, no try-catch or promise.catch can catch the error, so it will crash the node process.
However you can catch them globally to prevent crashing your app:
```ts
process.on("uncaughtException", err => {
  console.error("uncaughtException", err);
});
```
