### ISSUE TITLE
Apollo's schema hints (apollo cache integration)

### ISSUE THREAD

**Issue by capaj** [19majkel94/type-graphql#75]
I'd like to create my schema with: https://www.apollographql.com/docs/engine/caching.html#hints-to-schema so it would be nice if I could define any arbitrary graphql directive to be passed to the compiled schema.
Maybe like:

```javascript
@directive('@cacheControl(maxAge: 240)')
@ObjectType()
class MyClass {
  ...
}
```

Which should result in

```
type MyClass @cacheControl(maxAge: 240) {
  ...
}
```

**Comment by 19majkel94** [comment]
AFAIK, `graphql-js` doesn't allow for easy registering server-side directives to schema.
There's `extensionASTNodes` field in `ObjectType` config but I need some research on this whether this is possible. 

For things like caching and other stuff there is a [middlewares feature](https://19majkel94.github.io/type-graphql/docs/middlewares.html) with [custom decorators support](https://19majkel94.github.io/type-graphql/docs/middlewares.html#custom-decorators) :wink:

**Comment by 19majkel94** [comment]
Ok, I've done some research and looks like right now there's now way to register directives using `graphql-js` way:
> Right now directives are purely a feature of the GraphQL language and IDL, so a schema not created using IDL definitionally won't contain directives. When building a schema in code, you have the full power of the host programming environment, so directives shouldn't be necessary. Directives are a tool for supplying additional intent to be later interpreted by the host programming environment.

However there's possibility to add an integration with Apollo Cache, just like in #36. `apollo-cache-control` sets `cacheControl` key on `GraphQLResolveInfo`:
https://github.com/apollographql/apollo-cache-control-js/blob/master/src/index.ts

But in that case I will have to first, develop a way to create plugins for schema creating with some hooks and then create the complexity and cache integration plugins.

**Comment by stonecold123** [comment]
@19majkel94 

I've made a middleware for apollo-cache-control after reading this post, but I still don't understand how it's supposed to work. I've set the maxAge to 60 seconds. The middleware seems to be working because I can see the cacheControl data  in the extension field from the response.

But  when I refresh the page within seconds, the DB queries are still being made. `apollo-cache-control` has no effects at all.

````
import {MiddlewareFn} from "type-graphql";

export function CacheControl(maxAge:number = 60): MiddlewareFn {
    return ({info:{cacheControl}}, next) => {
        cacheControl.setCacheHint({maxAge,scope:"PUBLIC"})
        return next();

    };
}
````

````
    @Query(returnType => [ItemModel])
    @UseMiddleware(CacheControl())
    public getItems() {
       return dbGetData();
    }

````

**Comment by stonecold123** [comment]
I just read that apollo engine is required in order to work with cache control. I haven't set up apollo engine config in graphql yoga so I will try it later.

**Comment by stonecold123** [comment]
The caching finally works by adding Apollo Engine. But the yoga example leaves out some settings. https://github.com/graphcool/graphql-yoga/blob/master/examples/apollo-engine/index.js

I have to set the endpoint and port twice  in `ApolloEngine` and `graphQLServer.createHttpServer` to get the server starts.

````
    const port = 3000;
    
    const serverOptions: Options = {
        port,
        endpoint: "/graphql",
        playground: "/playground",
        tracing: true,
        cacheControl: true
    };


    const engine = new ApolloEngine({
        apiKey: process.env.APOLLO_ENGINE_KEY
    });

    const httpServer = graphQLServer.createHttpServer(serverOptions);

    engine.listen(
        {
            port,
            httpServer,
            graphqlPaths: ['/graphql'],

        },
        () =>
            console.log(
                `Server with Apollo Engine is running on http://localhost:3000`,
            ),
    )
````

**Comment by 19majkel94** [comment]
Thanks for the research 😉 I am going to add integration with `apollo-cache-control` and `apollo-engine` to the examples section, along with custom `@CacheControl` decorator.

**Comment by stonecold123** [comment]
@19majkel94 
Have you started using `apollo-cache-control`?
My caching middleware example above no longer works anymore. 
The `setCacheHint` method doesn't update the `cacheHint`. 
In the apollo engine dashbroad, it still says `No cache policy was defined for this operation. `

````
import {MiddlewareFn} from "type-graphql";

export function CacheControl(maxAge:number = 60): MiddlewareFn {
    return ({info:{cacheControl}}, next) => {
        cacheControl.setCacheHint({maxAge,scope:"PUBLIC"})
        console.log(cacheControl.cacheHint)
        return next();

    };
}
````

**Comment by damons-sportsbet** [comment]
I really can't work out what the syntax would be for adding cache directives, are there any good examples of this yet?

**Comment by clayrisser** [comment]
Does anyone have an example for cache control with type-graphql?

**Comment by oddgrd** [comment]
The apollo-cache-control package has been deprecated. Do you still use this solution @omar-dulaimi , or did you figure out another way?

**Comment by Distortedlogic** [comment]
bump
