### ISSUE TITLE
be used in production ?

### ISSUE THREAD

**Issue by athemb** [19majkel94/type-graphql#78]
Hello, can type-graphql be used in production ? for a real project ?
thank you

**Comment by 19majkel94** [comment]
Of course 😉 
The core is stable and well tested (95% coverage, 4400 lines of test code), so you can use it without a fear. If some bugs appear, I will fix them ASAP when you report them.
However all the remaining features have no ETA yet, so the 1.0 release will arrive sooner or later 😜
