### ISSUE TITLE
Question: How to generate a schema.graphql file using type-graphql

### ISSUE THREAD

**Issue by ajmath** [19majkel94/type-graphql#81]
I'm currently working on setting up a graphql server using AWS AppSync and lambda.  Part of the requirement is to have a schema.graphql written to disk at deploy time.  Is this possible with **type-graphql**?  I know there isn't any CLI tool available for this library but could this be done with the `GraphQLSchema` object returned from `buildSchema`?  Thanks

**Comment by 19majkel94** [comment]
`graphql-js` has a `printSchema` helper:
http://graphql.org/graphql-js/utilities/#printschema

**Comment by omatrot** [comment]
@ajmath Are you in the gutter lobby ? I'ld like to discuss this topic with you because I'm doing the same

**Comment by 19majkel94** [comment]
I've used this approach (schema in SDL, generating TS interfaces, writing resolvers using `graphql-tools`) in my earlier GraphQL projects and keeping things in sync was a real pain, as I described in article:
https://medium.com/@19majkel94/graphql-typescript-typegraphql-ba0225cb4bed
That's why TypeGraphQL has been created, to have one source of truth - only classes in the code.

If you need the SDL schema file for deployment purposes, you can create a simple npm script for that and you can run this even as a git commit hook.

```ts
// createSchema.ts
export function createSchema() {
  return buildSchema({
    // ...
  }
}

// generate.ts
(async () => {
  const schema = await createSchema();
  const sdl = printSchema(schema);
  await fs.writeFile(__dirname + '/schema.graphql', sdl);
})();
```

```json
{
  "scripts": {
    "generate-schema": "ts-node ./generate.ts"
  }
}
```

**Comment by 19majkel94** [comment]
FYI, done in #170 🎉

**Comment by msieorbus** [comment]
> I've used this approach (schema in SDL, generating TS interfaces, writing resolvers using `graphql-tools`) in my earlier GraphQL projects and keeping things in sync was a real pain, as I described in article: https://medium.com/@19majkel94/graphql-typescript-typegraphql-ba0225cb4bed That's why TypeGraphQL has been created, to have one source of truth - only classes in the code.
> 
> If you need the SDL schema file for deployment purposes, you can create a simple npm script for that and you can run this even as a git commit hook.
> 
> ```ts
> // createSchema.ts
> export function createSchema() {
>   return buildSchema({
>     // ...
>   }
> }
> 
> // generate.ts
> (async () => {
>   const schema = await createSchema();
>   const sdl = printSchema(schema);
>   await fs.writeFile(__dirname + '/schema.graphql', sdl);
> })();
> ```
> 
> ```json
> {
>   "scripts": {
>     "generate-schema": "ts-node ./generate.ts"
>   }
> }
> ```

is it possible to do the same but for queries written in ts ?
