### ISSUE TITLE
Proposal: allow AuthChecker to process not only strings as roles, but any type

### ISSUE THREAD

**Issue by alexey-pelykh** [19majkel94/type-graphql#82]
This would allow to implement request-aware checks, if role is used as permission (e.g. `read:something@id`)

Would be happy to provide PR for that

**Comment by alexey-pelykh** [comment]
PR #83

**Comment by 19majkel94** [comment]
I'm not convinced about replacing the type with `any`. It would have to be possible to narrow the type by the users.

Could you describe your use case in more details? What do you mean by "request-aware checks, if role is used as permission (e.g. read:something@id)"?

Maybe your use case is more than a simple authorization and you can just [create your own middleware](https://19majkel94.github.io/type-graphql/docs/middlewares.html#guards) with [custom decorator](https://19majkel94.github.io/type-graphql/docs/middlewares.html#custom-decorators) for that? 😉

**Comment by alexey-pelykh** [comment]
In my case, role is a composite object, that has own method to check if user object is allowed to perform that action.

Custom - definitely can be implemented, though making a 99.9% copy-paste seems not awesome as well. What you'd say for making that a generic type that is string by default?

**Comment by 19majkel94** [comment]
So you think that `Authorized` decorator would be generic? Something like:
```ts
class SampleResolver {
  
  @Mutation()
  @Authorized<Permission>({ readonly: true })
  sampleMutation() {
    // ...
  }
}
```
where users could create own aliases like `export const Authorized = TypeGraphQL.Authorized<Permission>`? 

So also the `AuthChecker` type would have to be generic with `RoleType = string`... if think that can work 😉 I will try to implement it today or tomorrow.

**Comment by alexey-pelykh** [comment]
Looks awesome!

**Comment by alexey-pelykh** [comment]
@19majkel94 I'd still change to `any` over here, since with generic you can not be sure what will be there https://github.com/19majkel94/type-graphql/blob/ed318d6ef40ee958d9567dc2e9a3da2f9c4015ea/src/metadata/metadata-storage.ts#L204

**Comment by 19majkel94** [comment]
Right, I've fixed that, thanks!
So is that works for you? Can I release that?

**Comment by 19majkel94** [comment]
It's just a types change, no runtime code affected, all tests passed. Maybe the problem is that you have multiple copies of `graphql` package in project `node_modules` or something? There is a problem with `instance of` then 😕

**Comment by alexey-pelykh** [comment]
Yeah, I thought of this as well, so I guess we're safe to release 👍
