### ISSUE TITLE
Returning Object type

### ISSUE THREAD

**Issue by madshargreave** [19majkel94/type-graphql#84]
Hi

I have some unstructured json data I'd like to return to the client. I've written the entity as a combined object type and typeorm entity

```ts
@Entity()
@ObjectType()
export class Document {

    @PrimaryGeneratedColumn()
    @Field(type => ID)
    id: string

    @Field(type => Object)
    data: object

}
```

However the above will throw the following exception at runtime due to `@Field(type => Object)`

```
Unhandled promise rejection (rejection id: 2): Error: Cannot determine GraphQL output type for data
```

**Comment by 19majkel94** [comment]
`Object` or `any` is not a valid GraphQL output type. GraphQL is strongly typed and you can't return anything you want.

For that case, you need to serialize the data. To do that, use have to use custom scalar that will transform the object to string:
https://github.com/taion/graphql-type-json

```ts
import GraphQLJSON from 'graphql-type-json';

@Entity()
@ObjectType()
export class Document {
    @PrimaryGeneratedColumn()
    @Field(type => ID)
    id: string

    @Field(type => GraphQLJSON)
    data: object
}
```

**Comment by madshargreave** [comment]
Thanks that worked!

**Comment by mikebm** [comment]
Hello, I am doing this exact same thing. My API returns a Map<String, String> from Java and so I tried adding:
import GraphQLJSON from 'graphql-type-json'; 

and decorating the field like so: 
  @Field(type => GraphQLJSON, { nullable: true })
  imagePaths?: { [key: string]: string };

Unfortunately, I still get this error: 
Cannot determine GraphQL output type for imagePaths

Did you do something different to make this work? I am using grapql-type-json version 0.2.1.

Thanks.

**Comment by 19majkel94** [comment]
@mikebm 
I think it should work. Please provide a minimal reproducible code example so I could investigate the problem 😉

**Comment by mikebm** [comment]
I was able to get it to work by changing the import from:
import GraphQLJSON from 'graphql-type-json';
to:
import * as GraphQLJSON from "graphql-type-json";

I even have  "allowSyntheticDefaultImports": true
so I am not sure why the first one didn't work. Thanks though!
