### ISSUE TITLE
Resolver helper methods

### ISSUE THREAD

**Issue by davewasmer** [19majkel94/type-graphql#85]
Sorry for the super vague title, couldn't think of anything better :wink:

So there might be a way to accomplish this right now, but I don't see it. I'd like to be able to extract common actions in my resolvers out into helper methods, i.e.:

```ts
@Resolver()
class RecipeResolver extends BaseResolver {

  authorize() {
    // this could even be defined on a base class
  }
  
  @Query(returns => [Recipe])
  async recipes() {
    this.authorize();
    // ...
  }

}
```

The problem here is that as soon as the helper method needs the context object (for example), it's a lot more verbose because I have to pass around the values manually each time:

```ts
  authorize(context: Context) {
    // ...
  }

  async recipes(@Ctx context: Context) {
    this.authorize(context);
    // ...
```

The above example is slightly trivial, but it highlights the fact that resolvers basically cannot have any "implied" or "default" behavior - because of the use of parameter decorators, I have to explicitly include every needed parameter on every resolver method, and explicitly hand those down through every layer.

What would be great is if I could access all the normal GraphQL parameters via `this`, or at least the context, i.e.:

```ts
  authorize() {
    this.context.foo
  }

  async recipes() {
    this.authorize();
    // ...
```

Hopefully this makes some sense. And normally I run away from "magic" or "implicit" behavior, but when applied cautiously, it's super useful.

Thanks for a great project!

**Comment by davewasmer** [comment]
Hmm, digging into the source, it looks like resolvers are singletons, which would make it tough to attach any state to the instance.

Without changing it so that a resolver is created per query, I don't think this will be possible ...

**Comment by 19majkel94** [comment]
Yes, resolver classes are taken from IOC container to take benefits of dependency injection.
Creating new instance of every resolver for each request is against single threaded Node.js idea.

For common code I can recommend two solutions:
1. If the code domain is your business logic, you should extract it to the service classes and inject instance of them into resolvers:
https://github.com/19majkel94/type-graphql/tree/master/examples/using-container

2. If the code is related to common things, like the infrastructure one, e.g. `authorize` based on context, you can use the middlewares feature - they have full access to resolver data, like the `context`:
https://github.com/19majkel94/type-graphql/tree/master/examples/middlewares

So your example would look like this:
```ts
@Resolver()
class RecipeResolver {
  @UseMiddleware(authorize)
  @Query(returns => [Recipe])
  async recipes() {
    this.authorize();
    // ...
  }
}
```

**Comment by davewasmer** [comment]
> Creating new instance of every resolver for each request is against single threaded Node.js idea

I'm curious to understand this better - are you saying that creating an instance would be CPU intensive enough to potentially block the thread for a non-trivial amount of time? If so, that seems surprising.

> If the code domain is your business logic, you should extract it to the service classes and inject instance of them into resolvers:

Hm, but it seems like services don't have any access to the Context without passing it in manually, which was my main frustration. Am I misunderstanding how the injection works there?

In other words, I'd still have to call `this.someService.someMethod(context)`.

> If the code is related to common things, like the infrastructure one, e.g. authorize based on context, you can use the middlewares feature - they have full access to resolver data, like the context

I tried this route, and the difficulty I'm facing is that middleware decorators seem a bit too isolated for my goals.

For example, imagine the following resolver:

```
recipe() {
  let recipe = await Recipe.find(1);
  if (can('show-full-recipe')) {
    return recipe;
  } else (can('show-public-recipe')) {
    return recipe.publicSummary();
  }
  throw new Error('Forbidden!');
}
```

Ignoring where the `can()` method comes from for now, this example is difficult to replicate with a middleware decorator because the main business logic of the resolver needs to vary depending on the authorization results. Middleware seems more "binary" - either I invoke `next()` or I don't.

**Comment by 19majkel94** [comment]
@davewasmer 
If you have more question, please reopen this issue or ask on gitter chat room:
https://gitter.im/type-graphql/Lobby
