### ISSUE TITLE
Typeorm returns a date string instead of a date object for date column

### ISSUE THREAD

**Issue by stonecold123** [19majkel94/type-graphql#86]
If I set a date column with   `@CreateDateColumn({type:'Date'})` in an entity. Typeorm would return a string `{created: "2018-05-18"}` instead of a date object

Is it possible for type-graphql or typeorm to automatically convert that date string into a date object? I thought Typeorm would automatically do so like a `dateTime` column but it won't.

````
@Entity()
@ObjectType()
export class Rate {
  @PrimaryGeneratedColumn()
  readonly id: number;

  @Field()
  @CreateDateColumn({type:'Date'})
  created: Date;

}
````

**Comment by 19majkel94** [comment]
AFAIK, this should be a `Date` instance:
https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#createdatecolumn

Please ask on TypeORM gitter or create an issue on TypeORM repository about the type of `@CreateDateColumn`.
