### ISSUE TITLE
Does this lib support getters as Fields? 

### ISSUE THREAD

**Issue by capaj** [19majkel94/type-graphql#88]
Today I've implemented support for [getters into typegql](https://github.com/capaj/typegql/commit/33cb7ba06ac71f3efb6f7ffb79952f6d20635f99) and I was wondering-does this library support getters?

**Comment by 19majkel94** [comment]
Yes, from the first release 3 months ago :wink:
https://github.com/19majkel94/type-graphql/blob/67b9c413e92c04fd3bd4fcdbd7ee8050f989afae/tests/functional/resolvers.ts#L58
