### ISSUE TITLE
Resolver inheritance/extending

### ISSUE THREAD

**Issue by alexey-pelykh** [19majkel94/type-graphql#89]
The project I'm working on right now has a lot of super-similar CRUD-alike resolvers, and amount of copy-paste is huge. I've come up with something like this:

```ts
export type ResourceRepositoryServiceClass<
  TService extends ResourceRepositoryService<TEntity, TId, TContent>,
  TEntity = {},
  TId = {},
  TContent = {}
> = Function & { prototype: TService }

export interface DtoClassType<TDto extends Dto<TDto, TObject>, TObject = {}> {
  new (): TDto
}

export function ResourceResolver<
  TDto extends Dto<TDto, TObject>,
  TContentDto extends Dto<TContentDto, TContentObject>,
  TService extends ResourceRepositoryService<TEntity, TId, TContent>,
  TEntity = {},
  TId = {},
  TContent = {},
  TObject = {},
  TContentObject = {}
> (
  resourceType: Resource,
  resourceServiceIdentifier: ResourceRepositoryServiceClass<TService>,
  dtoClass: DtoClassType<TDto>,
  contentDtoClass: DtoClassType<TContentDto>
) {
  const resourceNameUpper = upperFirst(camelCase(resourceType))

  abstract class ResourceResolver<
    TResolver
  > {
    protected readonly packDto = Dto.pack.bind(dtoClass)
    protected readonly unpackDto = Dto.unpack.bind(dtoClass)
    protected readonly packContentDto = Dto.pack.bind(contentDtoClass)
    protected readonly unpackContentDto = Dto.unpack.bind(contentDtoClass)

    constructor (
      @inject(resourceServiceIdentifier) protected readonly resourceService: TService
    ) {}

    @Mutation(returns => dtoClass)
    @Authorized(Permissions.canCreate(resourceType))
    async [`create${resourceNameUpper}`] (
      @Arg('data', type => contentDtoClass) data: TContentDto
    ): Promise<TDto> {
      const resource = await this.resourceService.create(this.unpackContentDto(data))
      return this.packDto(resource)
    }
  }

  return ResourceResolver
}

@injectable()
@Resolver(of => ThingDto)
export default class ThingResolver extends ResourceResolver(
  Resource.Thing,
  ThingService,
  ThingDto,
  ThingContentDto
)<ThingResolver> {
  constructor (
    @inject(ThingService) thingService: ThingService
  ) {
    super(thingService)
  }

  // Here goes any resource-specific thing
}
```

Yet the approach won't work, since `@Mutation` gets a `ResourceResolver` as target, that can not be resolved via DI.

What are your thoughts on making this approach possible? Options I see so far:
* `Resolver` should support something like "extends" to override the target of inherited annotations?

**Comment by 19majkel94** [comment]
It has been discussed in #47. I will pase the quote from similar discussion in `routing-controllers`:

> code you provided does not look good even if it was implementable. In my experience inheritance in controllers never bring somethings really valuable, its only makes things complex and unpredictable. Controllers should be simple as hell and if you have duplication in logic - simply extract this logic into services - thats correct places for such logic. If you have duplication in decorators and routes - thats not an issue, having duplicated route decorators just makes things more explicit. Really really no need to make things complex (and make life harder for everyone except you) with such patterns.

And I agree that decorators duplication is not an issue, it just makes things more explicit. Remember that you don't have SDL schema, only your classes acts as a schema definition. So generating it implicitly will make life harder for everyone except you.

If you have common logic, just put them in generic services that will be injected to resolver classes, as they should be super simple and just calling the helper service.

**Comment by alexey-pelykh** [comment]
To be exact, the suggestion is:
* `Resolver` should support `extends: Function[]` in order to be able to collect things from extended classes and substitute `target` for those

**Comment by alexey-pelykh** [comment]
I totally agree that controllers should be as simple as hell and such approach should be treated as "advanced". In my situation, it's closer to being a necessity rather than "why not?". This is how it works right now:
```
import Bluebird from 'bluebird'
import { upperFirst, lowerFirst, camelCase } from 'lodash'
import { Request } from 'express'
import { GraphQLInt, GraphQLID } from 'graphql'
import { Mutation, Arg, Query, Ctx } from 'type-graphql'
import ResourceRepositoryService from '../services/ResourceRepositoryService'
import Dto, { DtoClassType } from './Dto'

export type ResourceRepositoryServiceClass<
  TService extends ResourceRepositoryService<TEntity, TId, TContent>,
  TEntity = {},
  TId = {},
  TContent = {}
> = Function & { prototype: TService }

export default function ResourceResolver<
  TDto extends Dto<TDto, TObject>,
  TContentDto extends Dto<TContentDto, TContentObject>,
  TService extends ResourceRepositoryService<TEntity, TId, TContent>,
  TEntity = {},
  TId = {},
  TContent = {},
  TObject = {},
  TContentObject = {}
> (
  resourceSingle: string,
  resourcePlural: string,
  resourceServiceIdentifier: ResourceRepositoryServiceClass<TService>,
  dtoClass: DtoClassType<TDto>,
  contentDtoClass: DtoClassType<TContentDto>
) {
  const resourceName = camelCase(resourceSingle)
  const resourcePluralName = camelCase(resourcePlural)
  const resourceNameUpper = upperFirst(resourceName)
  const resourceNameLower = lowerFirst(resourceName)
  const resourcePluralNameUpper = upperFirst(camelCase(resourcePluralName))
  const resourcePluralNameLower = lowerFirst(camelCase(resourcePluralName))

  abstract class ResourceResolver<
    TResolver
  > {
    protected readonly packDto = Dto.pack.bind(dtoClass)
    protected readonly unpackDto = Dto.unpack.bind(dtoClass)
    protected readonly packContentDto = Dto.pack.bind(contentDtoClass)
    protected readonly unpackContentDto = Dto.unpack.bind(contentDtoClass)

    constructor (
      protected readonly resourceService: TService
    ) {}

    @Mutation(returns => dtoClass)
    async [`create${resourceNameUpper}`] (
      @Arg('data', type => contentDtoClass) data: TContentDto
    ): Promise<TDto> {
      const resource = await this.resourceService.create(this.unpackContentDto(data))
      return this.packDto(resource)
    }

    @Query(returns => [dtoClass])
    async [resourcePluralNameLower] (
      @Ctx() request: Request
    ): Promise<TDto[]> {
      const resources = this.resourceService.query()

      return Bluebird.map(resources, resource => this.packDto(resource))
    }

    @Query(returns => GraphQLInt)
    async [`count${resourcePluralNameUpper}`] (
      @Ctx() request: Request
    ): Promise<number> {
      return this.resourceService.count()
    }

    @Query(returns => dtoClass, { nullable: true })
    async [resourceNameLower] (
      @Arg('id', type => GraphQLID) id: number
    ): Promise<TDto | null> {
      const resource = await this.resourceService.get(id as any)
      if (!resource) {
        return null
      }

      return this.packDto(resource)
    }

    @Mutation(returns => dtoClass)
    async [`update${resourceNameUpper}`] (
      @Arg('id', type => GraphQLID) id: number,
      @Arg('data', type => contentDtoClass) data: TContentDto
    ): Promise<TDto> {
      const resource = await this.resourceService.update(id as any, this.unpackContentDto(data))
      return this.packDto(resource)
    }

    @Mutation(returns => dtoClass)
    async [`delete${resourceNameUpper}`] (
      @Arg('id', type => GraphQLID) id: number
    ): Promise<TDto> {
      const resource = await this.resourceService.get(id as any)
      await this.resourceService.delete(id as any)
      return this.packDto(resource)
    }
  }

  return ResourceResolver
}
```

and

```
import { injectable, inject } from 'inversify'
import { Resolver } from 'type-graphql'
import ThingService from '../../services/Thing.service'
import ResourceResolver from '../ResourceResolver'
import ThingDto from './Thing.dto'
import ThingContentDto from './ThingContent.dto'

export const ThingBaseResolver = ResourceResolver(
  'Thing',
  'Things',
  ThingService,
  ThingDto,
  ThingContentDto
)

@injectable()
@Resolver(of => ThingDto)
export default class ThingResolver extends ThingBaseResolver<ThingResolver> {
  constructor (
    @inject(ThingService) /*private readonly*/ thingService: ThingService
  ) {
    super(thingService)
  }
}
```

I've managed to get this working only thanks to this:
```
container
  .bind(ThingBaseResolver)
  .to(ThingResolver)
```
as a workaround for `target` being resolved as `ThingBaseResolver`

Apart of this workaround, everything else seems perfectly legal

**Comment by 19majkel94** [comment]
I'm afraid your API is not implementable.

Decorators are not supported in class mixins.
And your workaround with creating new abstract class ends with `Return type of exported function has or is using private name 'ResourceResolver` so you don't have access to `resourceService` in child resolver class (`ThingResolver`).
As decorators are evaluated on module parsing time, there's also no way to pass the resource info in constructor and normal inheritance.

So as you see, decorator-based API is intendent to be explicit.
And from the "simple" example you've showed, I think that's over-engineered and I would rather not to fix some bug digging in this monster. KISS 😜 

> Resolver should support extends: Function[] in order to be able to collect things from extended classes and substitute target for those

This can be achieved easily with `Object.getPrototypeOf`, no need to inform about extending.

**Comment by alexey-pelykh** [comment]
Hmm, how I may share an entire project archive with you? Since it works for me™, for any odd reason there!

**Comment by 19majkel94** [comment]
"works"? It's not supposed to generate correct schema even with container bind workaround 😕 

You can add me to your repo but I would prefer a simpler, reproducible inheritance example rather that a big project 😄

**Comment by alexey-pelykh** [comment]
There are two projects, one big and commercial, other one is demo. Please share a bitbucket ID then! =)

**Comment by 19majkel94** [comment]
The same as here - `19majkel94` 😉

**Comment by alexey-pelykh** [comment]
Done :)

**Comment by alexey-pelykh** [comment]
Please let me know if I may help anyhow =)

**Comment by 19majkel94** [comment]
You can go on https://gitter.im, it's a better place to discuss about this code 😉 
I've send you a private message there.

**Comment by 19majkel94** [comment]
After showing a few code samples and discussing the use cases, I've agreed to introduce this new feature 🎉 

Closing in favor of #90 😉

**Comment by lookapanda** [comment]
Hm, this does not quite seem to work for me:

```typescript
export function createNodeResolver<TNode extends INode>(): typeof BaseNodeResolver {
    @Resolver({ isAbstract: true })
    abstract class NodeResolver extends BaseNodeResolver<TNode> {
        @FieldResolver(() => ID)
        public id(): string {
            return '123'; // ignore this, just some debug stuff, it was WIP
        }
    }

    return NodeResolver;
}
```

And then I get:
`No provided object type in '@Resolver' decorator for class 'NodeResolver!'` :/

**Comment by 19majkel94** [comment]
@lookapanda 
You need to provide object type class to `of => ClassType` `@Resolver` decorator parameter.
Without this TypeGraphQL is not able to figure out of which object type you've created the `id` field resolver. Take a look at the example from tests:
https://github.com/19majkel94/type-graphql/blob/master/tests/functional/resolvers.ts#L1236

**Comment by lookapanda** [comment]
Well, this is definitely not documented the, neither in the examples nor in the actual documentation: https://19majkel94.github.io/type-graphql/docs/interfaces-and-inheritance.html#resolvers-inheritance

It only shows it like I have it already, that's why I also did it like that.
Thanks for the heads up, will try if it works now.

**Comment by 19majkel94** [comment]
Yes, it's documented - inherited resolvers are resolvers in the end, so read the resolvers docs, especially the "field resolvers" part:

https://19majkel94.github.io/type-graphql/docs/resolvers.html#field-resolvers
> Firstly, we need to declare which object type's fields we are resolving by providing the type to @Resolver decorator

Documentation can't describe every possible combination and use cases - you have to merge the knowledge of "Resolvers inheritance" with the base knowledge of "field resolvers". These are examples, not "copy-paste" solutions 😉

**Comment by lookapanda** [comment]
Well, I'm still learning how to use `type-graphql` and still reading through all of the docs, but I didn't have the time to read 100% of it yet :P

I know that they are no "copy-paste" solutions, but I have to start somewhere to understand all of it, right? :)

That still leaves the question: If the code like I have it above doesn't work like that, why is it documented like that?

**Comment by 19majkel94** [comment]
> If the code like I have it above doesn't work like that, why is it documented like that?

The code from documentations works. It just show inheritance on simple example with only queries and mutation, so the `of => Type` parameter is not needed in that case. You need to provide it only if you use `@FieldResolver`.

The order and division between "Beginner guides" and "Advanced guides" is for a reason 😃

**Comment by lookapanda** [comment]
Ah, I see, thanks. I got it to work in my use case now.

I know that github issues are not a helpdesk, that being said, is there a Slack, Discord, Gitter or similar for this project where I could ask for help?

**Comment by 19majkel94** [comment]
![image](https://user-images.githubusercontent.com/10618781/41405819-fb7c2700-6fca-11e8-854c-1ac4d572f7c1.png)

https://gitter.im/type-graphql/Lobby

**Comment by christopherdupont** [comment]
Maybe simpler & cleaner ?

```typescript
import { ClassType, Resolver, Query, Int, Arg, Mutation, Args } from 'type-graphql';

import { CrudResolver } from './crud-resolver.interface';
import { CrudService } from '../services/crud-service.interface';

export class CrudResolverFactory {
  static create<T>(Clazz: ClassType, DtoClazz: ClassType) {
    const clazzName = Clazz.name.toLocaleLowerCase();
    
    @Resolver(of => Clazz, { isAbstract: true })
    abstract class AbstractCrudResolver implements CrudResolver<T> {
      constructor(private readonly service: CrudService<T>) {}
      
      @Mutation(returns => Clazz, { name: `save${Clazz.name}` })
      async save(@Arg('data', type => DtoClazz) data: Partial<T>): Promise<T> {
        return await this.service.save(data);
      }
      
      @Query(returns => [Clazz], { name: `${clazzName}` })
      async getAll(): Promise<T[]> {
        return await this.service.getAll();
      }
      
      @Query(returns => Clazz, { name: `${clazzName}ById`, nullable: true })
      async getOne(@Arg('id', type => Int) id: number): Promise<T | undefined> {
        return await this.service.getOne(id);
      }
      
      @Mutation(returns => Boolean, { name: `delete${Clazz.name}` })
      async delete(@Arg('id', type => Int) id: string): Promise<boolean> {
        return await this.service.delete(id);
      }
    }
    
    return AbstractCrudResolver as any;
  }
}
```

**Comment by 19majkel94** [comment]
> Maybe simpler & cleaner ?

What do you mean? Why do you think that
```ts
export class CrudResolverFactory {
  static create<T>(Clazz: ClassType, DtoClazz: ClassType) {
```
is simpler than
```ts
export function CrudResolver<T>(Clazz: ClassType, DtoClazz: ClassType) {
```

**Comment by christopherdupont** [comment]
Yeah, that's more concise thanks @19majkel94 !

**Comment by guguji5** [comment]
> Hm, this does not quite seem to work for me:
> 
> ```ts
> export function createNodeResolver<TNode extends INode>(): typeof BaseNodeResolver {
>     @Resolver({ isAbstract: true })
>     abstract class NodeResolver extends BaseNodeResolver<TNode> {
>         @FieldResolver(() => ID)
>         public id(): string {
>             return '123'; // ignore this, just some debug stuff, it was WIP
>         }
>     }
> 
>     return NodeResolver;
> }
> ```
> 
> And then I get: `No provided object type in '@Resolver' decorator for class 'NodeResolver!'` 😞

after add `of => ClassType @Resolver`, it works as you expect ? @Ponjimon
