### ISSUE TITLE
Generating schema error

### ISSUE THREAD

**Issue by snaquaye** [19majkel94/type-graphql#94]
Attempts to load all resolvers fail with `Generating schema error`
```
async function bootstrap() {
  const schema = await buildSchema({
    resolvers: [__dirname + "/**/*.resolver.ts"],
  });

  // other initialization code, like creating http server
}
```

**Comment by 19majkel94** [comment]
`GeneratingSchemaError` has a `details` property of type `ReadonlyArray<GraphQLError>`.
I think that it might be useful in debugging the reason of this error 😉

**Comment by 19majkel94** [comment]
@snaquaye 
Have you figured out what was the problem?
Could you paste here the content of `details` property with GraphQL errors?

**Comment by snaquaye** [comment]
Trying to debug it, i noticed it is now working. My bad

**Comment by snaquaye** [comment]
My bad! Trying to debug it, i noticed it is now working.

**Comment by brspurri** [comment]
@snaquaye Do you remember what your actually solution was here?

**Comment by leonlafa** [comment]
@snaquaye are you still having issues with this?  Happy to give a helping hand if you're...

**Comment by johnmcveigh** [comment]
It appears that `GeneratingSchemaError.details` needs to be logged explicitly under these circumstances since it is not logged when a UnhandledPromiseRejectionWarning occurs.

# Workaround
## Before
```ts
export async function generateSchema(): Promise<GraphQLSchema> {
  return buildSchema({
    resolvers: [FunResolver]
  })
```
```
UnhandledPromiseRejectionWarning: Error: Generating schema error
... (no details)
```

## After
```ts
export async function generateSchema(): Promise<GraphQLSchema> {
  try {
    const schema = await buildSchema({
      resolvers: [FunResolver]
    })

    return schema
  } catch (e) {
    console.error(e)
    throw e
  }
}
```

```
GeneratingSchemaError: Generating schema error
...
details: [
    GraphQLError: Type Query must define one or more fields.
```

**Comment by sittingbool** [comment]
Hi, I am having this too and I have no clue how to solve it. I followed the Getting Started Instructions but removed all Authorization code. 

model/user.model.ts
```import "reflect-metadata";
import {ObjectType, Field, ID, Resolver, Query, Arg, Args, Mutation, Authorized, Ctx} from "type-graphql";
import {UserService} from "../services/user.service";

@ObjectType()
export class UserModel {

    @Field(type => ID)
    id?: string;
    @Field({ description: 'The users first name' })
    firstName: string;
    @Field({ description: 'The users last name' })
    lastName: string;
}



@Resolver(UserModel)
class UserResolver {
    constructor(private userService: UserService) {}

    @Query(returns => UserModel, { nullable: true })
    async recipe(@Arg("id") id: string) {
        return this.userService.findById(id);
    }

    @Query(returns => [UserModel], { nullable: true })
    users() {
        return this.userService.findAll(null);
    }

    @Mutation(returns => UserModel, { nullable: true })
    //@Authorized()
    addUser(
        @Arg("newUserData") newUserData: UserModel,
        //@Ctx("user") user: User,
    ): Promise<UserModel> {
        return this.userService.addNew({ data: newUserData/*, user*/ });
    }

    @Mutation(returns => Boolean)
    //@Authorized(Roles.Admin)
    async removeUser(@Arg("id") id: string) {
        try {
            await this.userService.removeById(id);
            return true;
        } catch {
            return false;
        }
    }
}```

app.ts
```
import * as express from 'express';
import {ApolloServer, gql} from 'apollo-server-express';
import './model/user.model';

import "reflect-metadata";

import {buildTypeDefsAndResolvers} from "type-graphql";
import {UserModel} from "./model/user.model";

const app: express.Express = express();

buildTypeDefsAndResolvers({
    resolvers: [UserModel],
}).then(result => {
    const { typeDefs, resolvers } = result;

    const server = new ApolloServer({typeDefs, resolvers});
    server.applyMiddleware({app});

    console.log('Apollo Server listening for:')
    console.log(server.graphqlPath);
}).catch(console.error);```

I start using node bin/www which then loads the app from app.js
