### ISSUE TITLE
Overriding resolver methods in extending classes.

### ISSUE THREAD

**Issue by IgorSzymanski** [19majkel94/type-graphql#95]
Currently there is no way to override methods of extended BaseResolver class.
Here's an example:

```ts
import { Arg, Int, Query, Resolver } from 'type-graphql'
import { ObjectID, Repository }      from 'typeorm'
import { InjectRepository }          from 'typeorm-typedi-extensions'
import * as pluralize  from 'pluralize'



export default function createBaseResolver<T extends object> (suffix: string, objectTypeCls: new() => T)
{

	@Resolver({ isAbstract: true })
	abstract class BaseResolver
	{
		@InjectRepository(objectTypeCls)
		protected readonly repository: Repository<T>

		@Query(type => [objectTypeCls], { name: `${pluralize(suffix)}` })
		async getAll (): Promise<T[]>
		{
			return this.repository.find()
		}

		@Query(type => objectTypeCls, { nullable: true, name: `${suffix}` })
		async getOne (@Arg('id', type => Int) id: string | number | ObjectID): Promise<T>
		{
			return this.repository.findOne(id, { cache: true })
		}
	}

	return BaseResolver
}

```

Two example methods that don't do what I think should be expected. (Issue explained in the comment above the method declarations).

```ts
import {
	Resolver,
	Query,
	Arg,
	Mutation,
}                         from 'type-graphql'
import createBaseResolver from '../../basics/resource.resolver'
import { Language }       from './language'
import { LanguageInput }  from './language.input'

const LanguageBaseResolver = createBaseResolver('language', Language)

@Resolver(Language)
export class LanguageResolver extends LanguageBaseResolver
{

// Method override attempt #1

// This method gets overriden by one generated by BaseResolver,
// and still procudes [language(id: Int!): Language]
// instead of [language(identifier: String!): Language]
	@Query(returns => Language)
	language (@Arg('identifier') identifier: string): Promise<Language>
	{
		return this.repository.findOne({ identifier })
	}

// Method override attempt #2

// Even though this method shares the name with the one in BaseResolver and technically overrides it,
// the query it produces is [getOne(identifier: String!): Language!]
// instead of [language(identifier: String!): Language]
	@Query(returns => Language)
	getOne (@Arg('identifier') identifier: string): Promise<Language>
	{
		return this.repository.findOne({ identifier })
	}

}
```

**type-graphql: 0.12.0**

**Comment by 19majkel94** [comment]
Overriding method from generated base resolver class...

![](https://media0.giphy.com/media/2rqEdFfkMzXmo/giphy.gif)

That's why I thought that introducing this feature isn't a good idea as it overcomplicates things 😞 

It should be fixable as now I concat the inherited resolvers after building child resolvers metadata but detecting overriding in JS/TS... I'm not sure whether should I detect only schema name overriding or also the class method name should supress the base one 😕

**Comment by IgorSzymanski** [comment]
> Overriding method from generated base resolver class...

It might sound a bit funky, but once in a while, overriding one of many inherited methods comes in handy. :smile: 
Wouldn't `mixins + interface` be a better approach than inheritance anyway?

**Comment by 19majkel94** [comment]
What do you mean by `mixins + interface`? Can you show an example API? 😉

**Comment by 19majkel94** [comment]
Closing for now via 6debc6e 🎉 

@IgorSzymanski 
If you have a proposal mixins API, please open a new feature when we could discuss that.

**Comment by dimensi** [comment]
@IgorSzymanski hi, i use your example in my code. I can't understand why InjectRepository not working in constructor, do you know why?
