### ISSUE TITLE
Boolean re-export?

### ISSUE THREAD

**Issue by lookapanda** [19majkel94/type-graphql#99]
Hello,

I'm sorry, I need to open an issue again :P

```typescript
    @FieldResolver()
    public async blocked(@Root() { id: targetUserId }: User, @Ctx() { viewer }: GraphQLContext): Promise<boolean> {
        if (!viewer) {
            return false;
        }

        const { id: userId } = fromGlobalId(viewer.user.id);

        const blockage = await getComparedBlockage(userId, targetUserId);

        if (!blockage) {
            return false;
        }

        return (
            blockage.userId === userId &&
            blockage.blockedUserId === targetUserId
        );
    }
```

I have this field in my user resolver but I get the following error:
`You need to provide explicit type for UserResolver#blocked !`

I'm not sure how to fix this, like, what does `@FieldResolver` expect here? There are only three exported scalars from `type-graphql` but I would need `Boolean` here, since the promise returns a boolean value. `graphql` exports a `GraphQLBoolean` object type, but it is not re-exported from `type-graphql` just like `ID` is.

**Comment by 19majkel94** [comment]
Please read the all the docs before creating multiple issues about things that are described in docs 😉 

https://19majkel94.github.io/type-graphql/docs/scalars.html
> However in some cases you will have to explicitly declare the string/bool scalar type. Use JS constructor functions (String, Boolean) then:

https://19majkel94.github.io/type-graphql/docs/resolvers.html
> The second is to provide the return type - the method is async so reflection metadata system shows that the return type is Promise of sth, so we have to add returns => [Recipe] decorator's parameter to declare that it will be an array of Recipe object types.
